buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/8a64863081703d4b7721253e8b44c2e7384921e7/C/CJieba/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.5"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "CJieba"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir\nmkdir $libdir $prefix/share\ncd cjieba\ninstall_license LICENSE \nc++ -o \"$libdir/libcjieba.$dlext\" lib/jieba.cpp -shared -fPIC -I./deps/ -std=c++11\ncp -va dict $prefix/share/\n"""
version = "v0.3.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libcjieba"]
    type = "lib"
    variable_name = "libcjieba"
    [[metadata.products]]
    paths = ["share/dict/hmm_model.utf8"]
    type = "file"
    variable_name = "hmm_model"
    [[metadata.products]]
    paths = ["share/dict/idf.utf8"]
    type = "file"
    variable_name = "idf"
    [[metadata.products]]
    paths = ["share/dict/jieba.dict.utf8"]
    type = "file"
    variable_name = "jieba_dict"
    [[metadata.products]]
    paths = ["share/dict/stop_words.utf8"]
    type = "file"
    variable_name = "stop_words"
    [[metadata.products]]
    paths = ["share/dict/user.dict.utf8"]
    type = "file"
    variable_name = "user_dict"

    [[metadata.sources]]
    hash = "1db462d33255aff08802c248b6d6e59202b5619e"
    type = "git"
    unpack_target = ""
    url = "https://github.com/yanyiwu/cjieba.git"
