buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/114cea50241b71e3298465893c22003a166d35e7/F/fts/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.6"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "fts"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/musl-fts/\n./bootstrap.sh\nCFLAGS=\"-fPIC\" ./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j${nproc}\nmake install\ninstall_license ./COPYING\n"""
version = "v1.2.8"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libfts"]
    type = "lib"
    variable_name = "libfts"

    [[metadata.sources]]
    hash = "0bde52df588e8969879a2cae51c3a4774ec62472"
    type = "git"
    unpack_target = ""
    url = "https://github.com/void-linux/musl-fts.git"
