buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a22305a9ae25ec9810725b30092bd34c8cddfaf6/H/HDF4/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.4"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "HDF4"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/hdf*\n\n# We need to build without NetCDF support. This is necessary to avoid\n# a name clash when using HDF4_jll and NetCDF_jll together.\ncmake -B build \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DTEST_LFS_WORKS_RUN=0 \\\n    -DH4_PRINTF_LL_TEST_RUN=0 \\\n    -DH4_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT= \\\n    -DHDF4_BUILD_NETCDF_TOOLS=0 \\\n    -DHDF4_ENABLE_NETCDF=0 \\\n    -DHDF4_ENABLE_SZIP_SUPPORT=1\n\n# On Windows, HDF4 finds libaec, but the generated Makefile still says \"NOTFOUND\".\n# (This problem exists also for HDF5 and is described in detail there.)\n# We fix the generated Makefile etc manually.\n\nfiles=(\n    build/hdf/src/CMakeFiles/hdf-shared.dir/build.make\n    build/hdf/src/CMakeFiles/hdf-shared.dir/linklibs.rsp\n    build/hdf/test/CMakeFiles/testhdf.dir/build.make\n    build/hdf/test/CMakeFiles/testhdf.dir/linklibs.rsp\n    build/mfhdf/hrepack/CMakeFiles/hrepack.dir/build.make\n    build/mfhdf/hrepack/CMakeFiles/hrepack.dir/linklibs.rsp\n    build/mfhdf/hrepack/CMakeFiles/test_hrepack.dir/build.make\n    build/mfhdf/hrepack/CMakeFiles/test_hrepack.dir/linklibs.rsp\n)\nfor file in ${files[@]}; do\n    perl -pi -e 's+libaec::aec-NOTFOUND+/workspace/destdir/lib/libaec.dll.a+' ${file}\n    perl -pi -e 's+libaec::sz-NOTFOUND+/workspace/destdir/lib/libsz.dll.a+' ${file}\ndone\n\ncmake --build build --parallel ${nproc}\ncmake --install build\n"""
version = "v4.3.2"

    [[metadata.dependencies]]
    compat = "3.1.1"
    name = "JpegTurbo_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.2.12"
    name = "Zlib_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.1.3"
    name = "libaec_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "477f73a3-ac25-53e9-8cc3-50b2fa2566f0"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["hdfed"]
    type = "exe"
    variable_name = "hdfed"
    [[metadata.products]]
    binnames = ["hdfimport"]
    type = "exe"
    variable_name = "hdfimport"
    [[metadata.products]]
    binnames = ["hdfls"]
    type = "exe"
    variable_name = "hdfls"
    [[metadata.products]]
    binnames = ["hdiff"]
    type = "exe"
    variable_name = "hdiff"
    [[metadata.products]]
    binnames = ["hdp"]
    type = "exe"
    variable_name = "hdp"
    [[metadata.products]]
    binnames = ["hrepack"]
    type = "exe"
    variable_name = "hrepack"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libhdf"]
    type = "lib"
    variable_name = "libhdf"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libmfhdf"]
    type = "lib"
    variable_name = "libmfhdf"

    [[metadata.sources]]
    hash = "a2c69eb752aee385b73d4255e4387134dd5e182780d64da0a5cb0d6e1d3dea3b"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/HDFGroup/hdf4/releases/download/hdf4.3.1/hdf4.3.1.tar.gz"
