buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/b567bb395e8d5a4253fce01102c4ad9f7316c738/I/ICU/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.6"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "ICU"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/icu/\n\n# Apply patch to link `libicudata` against the default standard libraries\n# to avoid toolchain weirdness when you have a dynamic library that has\n# _no_ dependencies (not even `libc`).  See this bug report for more:\n# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=653457\natomic_patch -p1 $WORKSPACE/srcdir/patches/yes_stdlibs.patch\n\n# Do the native build\n(\n    cp -r source/ native_build/\n    cd native_build\n    CC=\"${CC_BUILD}\"\n    CXX=\"${CXX_BUILD}\"\n    AR=\"${AR_BUILD}\"\n    LD=\"${LD_BUILD}\"\n    RANLIB=\"${RANLIB_BUILD}\"\n\n    # See https://git.alpinelinux.org/aports/tree/main/icu/APKBUILD?id=334ebffde9dec34becdd628ad56007699e98ea81\n    update_configure_scripts\n    sed -i -e 's,DU_HAVE_STRTOD_L=1,DU_HAVE_STRTOD_L=0,' configure.ac\n    sed -i -e 's,DU_HAVE_STRTOD_L=1,DU_HAVE_STRTOD_L=0,' configure\n    for x in ARFLAGS CFLAGS CPPFLAGS CXXFLAGS FFLAGS LDFLAGS; do\n        sed -i -e \"/^${x} =.*/s:@${x}@::\" \"config/Makefile.inc.in\"\n    done\n\n    ./configure --prefix=$prefix --build=${MACHTYPE} \\\n        ac_cv_prog_ac_ct_AR=${AR} \\\n        ac_cv_prog_ac_ct_RANLIB=${RANLIB}\n    make -j${nproc}\n)\n\n# Do the cross build\ncd source/\n\nif [[ \"${target}\" == *-apple-* ]]; then\n    # Do not append `-c` flag to ar, which isn't supported by LLVM's ar\n    atomic_patch -p1 $WORKSPACE/srcdir/patches/argflags-no--c.patch\n    export LDFLAGS=\"-headerpad_max_install_names\"\nfi\n\nupdate_configure_scripts\n./configure --prefix=$prefix --host=$target \\\n    --with-cross-build=\"/workspace/srcdir/icu/native_build\"\nmake -j${nproc}\nmake install\n"""
version = "v74.1.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = true
    libnames = ["libicudata", "icudt74"]
    type = "lib"
    variable_name = "libicudata"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libicui18n", "icuin74"]
    type = "lib"
    variable_name = "libicui18n"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libicuio", "icuio74"]
    type = "lib"
    variable_name = "libicuio"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libicutest", "icutest74"]
    type = "lib"
    variable_name = "libicutest"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libicutu", "icutu74"]
    type = "lib"
    variable_name = "libicutu"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libicuuc", "icuuc74"]
    type = "lib"
    variable_name = "libicuuc"

    [[metadata.sources]]
    hash = "86ce8e60681972e60e4dcb2490c697463fcec60dd400a5f9bffba26d0b52b8d0"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/unicode-org/icu/releases/download/release-74-1/icu4c-74_1-src.tgz"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
