dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "ghr"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/ghr/\nmkdir -p ${bindir}\ngo build -o ${bindir}\n"""
version = "v0.13.0"

[[products]]
binnames = ["ghr"]
type = "exe"
variable_name = "ghr"

[[sources]]
hash = "d43a5d2dae1573e03dec545a2103f1bc61a3e0d6"
type = "git"
unpack_target = ""
url = "https://github.com/tcnksm/ghr.git"
