init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Aria2"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "aarch64-apple-darwin", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11"]
script = """cd $WORKSPACE/srcdir/aria2-*/\n\nexport CPPFLAGS=\"-I${includedir}\"\nexport LDFLAGS=\"-L${libdir}\"\n\n./configure \\\n    --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    --with-pic --enable-shared --enable-libaria2 \\\n    --with-openssl --with-libxml2 --with-libz --with-libssh2\n\nmake -j${nproc}\nmake install\n\ninstall_license COPYING\ninstall_license LICENSE.OpenSSL\n"""
version = "v1.36.0"

[[dependencies]]
compat = ""
name = "LibSSH2_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MbedTLS_jll"
type = "builddependency"
version-major = 2
version-minor = 24
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenSSL_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "XML2_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zlib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["aria2c"]
type = "exe"
variable_name = "aria2c"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libaria2"]
type = "lib"
variable_name = "libaria2"

[[sources]]
hash = "58d1e7608c12404f0229a3d9a4953d0d00c18040504498b483305bcb3de907a5"
type = "archive"
unpack_target = ""
url = "https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.xz"
