buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/cd767ec5b2839745e9214d35f99b382b77d1aa5c/S/sdsl_lite/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
system = "Yggdrasil"
version = "0.2.2"

[metadata]
dependencies = []
name = "sdsl_lite"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "arm-linux-gnueabihf-cxx03", "arm-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "arm-linux-musleabihf-cxx03", "arm-linux-musleabihf-cxx11", "x86_64-apple-darwin14-cxx03", "x86_64-apple-darwin14-cxx11", "x86_64-unknown-freebsd11.1-cxx03", "x86_64-unknown-freebsd11.1-cxx11"]
script = """cd $WORKSPACE/srcdir/sdsl-lite/\nsed -ri \\\n\t-e \"s/^cmake /cmake -DCMAKE_TOOLCHAIN_FILE=\\\\$\\\\{CMAKE_TARGET_TOOLCHAIN\\\\} -DBUILD_SHARED_LIBS=ON /\" \\\n\t-e \"s/^make sdsl/make -j\\\\$nprocs sdsl/\" \\\n\tinstall.sh \n./install.sh $prefix\n"""
version = "v2.1.1"

    [[metadata.products]]
    dir_paths = []
    dont_dlopen = false
    libnames = ["libsdsl"]
    type = "lib"
    variable_name = "libsdsl"

    [[metadata.sources]]
    "https://github.com/simongog/sdsl-lite.git" = "0546faf0552142f06ff4b201b671a5769dd007ad"
