augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libzenohc"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "powerpc64le-linux-gnu"]
script = """cd $WORKSPACE/srcdir/zenoh-c\ncmake -B build -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DZENOHC_CUSTOM_TARGET=$CARGO_BUILD_TARGET\ncmake --build build --parallel ${nproc}\ncmake --build build --target install\n"""
version = "v1.0.3"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libzenohc"]
type = "lib"
variable_name = "libzenohc"

[[sources]]
hash = "d70de64e007d471d54ead930dbe0df333372e679"
type = "git"
unpack_target = ""
url = "https://github.com/eclipse-zenoh/zenoh-c.git"
