["33.1.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v33.1.0+0/rdma_core.v33.1.0.x86_64-linux-musl.tar.gz"]
registered = 2021-01-31T01:52:51.000Z

["57.0.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.x86_64-linux-musl.tar.gz"]
registered = 2025-06-13T23:53:06.000Z

    [["57.0.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v57.0.0+0/rdma_core.v57.0.0.x86_64-linux-musl.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/b16783e1d87c25280cd0d72a4e2f484ec9b0979c/R/rdma_core/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        ["57.0.0+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "rdma_core"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl"]
        script = """cd $WORKSPACE/srcdir\ncd rdma-core-*\ncmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DNO_MAN_PAGES=ON\nmake -j\nmake install\n"""
        version = "v57.0.0"

            [["57.0.0+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "libnl_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            uuid = "7c700954-19d3-5208-81e2-8fa5fe7c0bd8"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["57.0.0+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libibverbs"]
            type = "lib"
            variable_name = "libibverbs"
            [["57.0.0+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["librdmacm"]
            type = "lib"
            variable_name = "lbrdmacm"

            [["57.0.0+0".artifact_metadata.metadata.sources]]
            hash = "5f94c463c931e4a9273f366ca7cb446b54d8bd4732288ade04679886be06862d"
            type = "archive"
            unpack_target = ""
            url = "https://github.com/linux-rdma/rdma-core/releases/download/v57.0/rdma-core-57.0.tar.gz"

["58.0.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-musl.tar.gz"]
registered = 2025-06-25T23:18:06.000Z

    [["58.0.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-musl.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/5ed03c1114c4e8e8a6cbb06e6952c490245478ae/R/rdma_core/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        ["58.0.0+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = """if !haskey(ENV, \"JULIA_IBV_CONFIG_DIR\")\n        ENV[\"JULIA_IBV_CONFIG_DIR\"] = joinpath(artifact_dir, \"etc\", \"libibverbs.d\")\n    end\n"""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "rdma_core"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl"]
        script = """cd $WORKSPACE/srcdir\ncd rdma-core-*\n# Apply patches\nfor f in ${WORKSPACE}/srcdir/patches/*.patch; do\n\tatomic_patch -p1 ${f}\ndone\ncmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DNO_MAN_PAGES=ON\nmake -j\nmake install\n"""
        version = "v58.0.0"

            [["58.0.0+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "libnl_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            uuid = "7c700954-19d3-5208-81e2-8fa5fe7c0bd8"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["58.0.0+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libibverbs"]
            type = "lib"
            variable_name = "libibverbs"
            [["58.0.0+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["librdmacm"]
            type = "lib"
            variable_name = "lbrdmacm"

            [["58.0.0+0".artifact_metadata.metadata.sources]]
            hash = "88d67897b793f42d2004eec2629ab8464e425e058f22afabd29faac0a2f54ce4"
            type = "archive"
            unpack_target = ""
            url = "https://github.com/linux-rdma/rdma-core/releases/download/v58.0/rdma-core-58.0.tar.gz"
            [["58.0.0+0".artifact_metadata.metadata.sources]]
            follow_symlinks = false
            path = "./bundled"
            target = ""
            type = "directory"
