["4.2.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.2.0+0/rocBLAS.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.2.0+0/rocBLAS.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2022-09-08T17:47:27.000Z

    [["4.2.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.2.0+0/rocBLAS.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.2.0+0/rocBLAS.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/23954770c485a5b9230ae828cf0e242bd4f20619/R/rocBLAS/rocBLAS@4.2.0/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocblas/rocblas@4.2.0/build_tarballs.jl/23954770c485a5b9230ae828cf0e242bd4f20619.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

["4.5.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2022-09-09T13:59:04.000Z

    [["4.5.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/566e1b64f4fcf301b2cc57e82ffff31a2085c160/R/rocBLAS/rocBLAS@4.5.2/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocblas/rocblas@4.5.2/build_tarballs.jl/566e1b64f4fcf301b2cc57e82ffff31a2085c160.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

["5.2.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+0/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2022-09-21T20:59:05.000Z

    [["5.2.3+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+0/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3da3cc66bd8682b6030d32fe563d8690d3dc9253/R/rocBLAS/rocBLAS@5.2.3/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocblas/rocblas@5.2.3/build_tarballs.jl/3da3cc66bd8682b6030d32fe563d8690d3dc9253.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

["5.2.3+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+1/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2022-09-22T11:50:32.000Z

    [["5.2.3+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+1/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/96cbef75000bcb39b286e797b3a8235413b3d8ba/R/rocBLAS/rocBLAS@5.2.3/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocblas/rocblas@5.2.3/build_tarballs.jl/96cbef75000bcb39b286e797b3a8235413b3d8ba.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

["5.2.3+2"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+2/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2022-11-07T13:51:34.000Z

    [["5.2.3+2".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+2/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/47b25245588ff9adacf45aaaa0923436f90657bb/R/rocBLAS/rocBLAS@5.2.3/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocblas/rocblas@5.2.3/build_tarballs.jl/47b25245588ff9adacf45aaaa0923436f90657bb.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"
