["4.0.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-musl-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2021-07-14T18:27:39.000Z

    [["4.0.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-musl-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.0.0+0/rocm_cmake.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/97ef334919edd4805b3b78f7b38dcfa97f8901db/R/rocm_cmake/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/build_tarballs.jl/97ef334919edd4805b3b78f7b38dcfa97f8901db.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.4.0"

        [["4.0.0+0".artifact_metadata.sources]]
        hash = "4577487acaa6e041a1316145867584f31caaf0d4aa2dd8fd7f82f81c269cada6"
        type = "archive"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake/archive/rocm-4.0.0.tar.gz"

["4.2.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2022-08-15T19:57:13.000Z

    [["4.2.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/44a1bc90674881642b887e173fe27f72fef28aa1/R/rocm_cmake/rocm_cmake@4.2.0/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@4.2.0/build_tarballs.jl/44a1bc90674881642b887e173fe27f72fef28aa1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

        [["4.2.0+0".artifact_metadata.sources]]
        hash = "299e190ec3d38c2279d9aec762469628f0b2b1867adc082edc5708d1ac785c3b"
        type = "archive"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake/archive/rocm-4.2.0.tar.gz"

["4.5.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.5.2+0/rocm_cmake.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.5.2+0/rocm_cmake.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2022-08-23T21:13:30.000Z

    [["4.5.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.5.2+0/rocm_cmake.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.5.2+0/rocm_cmake.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/44a1bc90674881642b887e173fe27f72fef28aa1/R/rocm_cmake/rocm_cmake@4.5.2/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@4.5.2/build_tarballs.jl/44a1bc90674881642b887e173fe27f72fef28aa1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

        [["4.5.2+0".artifact_metadata.sources]]
        hash = "85f2ef51327e4b09d81a221b4ad31c97923dabc1bc8ff127dd6c570742185751"
        type = "archive"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake/archive/rocm-4.5.2.tar.gz"

["5.2.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.2.3+0/rocm_cmake.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.2.3+0/rocm_cmake.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2022-09-12T19:04:19.000Z

    [["5.2.3+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.2.3+0/rocm_cmake.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.2.3+0/rocm_cmake.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ed9cbf0e68d1cd15cd4992e3995fcd2554ce65ce/R/rocm_cmake/rocm_cmake@5.2.3/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@5.2.3/build_tarballs.jl/ed9cbf0e68d1cd15cd4992e3995fcd2554ce65ce.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

        [["5.2.3+0".artifact_metadata.sources]]
        hash = "c63b707ec07d24fda5a2a6fffeda4df4cc04ceea5df3b8822cbe4e6600e358b4"
        type = "archive"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake/archive/rocm-5.2.3.tar.gz"

["5.4.4+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2023-08-08T16:35:19.000Z

    [["5.4.4+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2e5539feb05d6fa0a11fe52ef2d2f3be58bdc7aa/R/rocm_cmake/rocm_cmake@5.4.4/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@5.4.4/build_tarballs.jl/2e5539feb05d6fa0a11fe52ef2d2f3be58bdc7aa.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["5.4.4+0".artifact_metadata.sources]]
        hash = "2e823f7604a965e7d56cff48d58fb666354bbfeb"
        type = "git"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake.git"

["5.5.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.5.1+0/rocm_cmake.v5.5.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.5.1+0/rocm_cmake.v5.5.1.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2023-10-02T16:05:11.000Z

    [["5.5.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.5.1+0/rocm_cmake.v5.5.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.5.1+0/rocm_cmake.v5.5.1.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/b7ff928294d07d20418284f0880e1b8b2fad4ae0/R/rocm_cmake/rocm_cmake@5.5.1/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@5.5.1/build_tarballs.jl/b7ff928294d07d20418284f0880e1b8b2fad4ae0.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["5.5.1+0".artifact_metadata.sources]]
        hash = "2e823f7604a965e7d56cff48d58fb666354bbfeb"
        type = "git"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake.git"

["5.6.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.6.1+0/rocm_cmake.v5.6.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.6.1+0/rocm_cmake.v5.6.1.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2023-10-04T09:40:29.000Z

    [["5.6.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.6.1+0/rocm_cmake.v5.6.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.6.1+0/rocm_cmake.v5.6.1.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ee8b1269e0f1ab5fb2be78e441bf452e84553c66/R/rocm_cmake/rocm_cmake@5.6.1/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@5.6.1/build_tarballs.jl/ee8b1269e0f1ab5fb2be78e441bf452e84553c66.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["5.6.1+0".artifact_metadata.sources]]
        hash = "07ec4c536108ae943e37985915ef279529ac693f"
        type = "git"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake.git"

["6.0.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"]
registered = 2023-12-17T19:28:05.000Z

    [["6.0.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f2b75a278977d0a055a7395b33ada62f133e1e79/R/rocm_cmake/rocm_cmake@6.0.0/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/rocm_cmake/rocm_cmake@6.0.0/build_tarballs.jl/f2b75a278977d0a055a7395b33ada62f133e1e79.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["6.0.0+0".artifact_metadata.sources]]
        hash = "5a34e72d9f113eb5d028e740c2def1f944619595"
        type = "git"
        url = "https://github.com/RadeonOpenCompute/rocm-cmake.git"
