["6.32.8+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+0/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
registered = 2025-03-07T01:35:03.000Z

    [["6.32.8+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+0/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/658ecbe7bb11371aea49e8abbb0090d530612949/R/ROOT/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/root/build_tarballs.jl/658ecbe7bb11371aea49e8abbb0090d530612949.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

["6.32.8+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+1/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
registered = 2025-06-29T23:04:05.000Z

    [["6.32.8+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+1/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/709de1757437724a5b293297623fb49522d360d8/R/ROOT/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/root/build_tarballs.jl/709de1757437724a5b293297623fb49522d360d8.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

["6.32.8+2"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+2/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
registered = 2026-01-06T11:38:41.000Z

    [["6.32.8+2".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ROOT_jll.jl/releases/download/ROOT-v6.32.8+2/ROOT.v6.32.8.x86_64-linux-gnu.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a6e4c0fe3e70c97526f336a2233841d3c812daa0/R/ROOT/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/r/root/build_tarballs.jl/a6e4c0fe3e70c97526f336a2233841d3c812daa0.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"
