init_block = ""
lazy_artifacts = false
name = "Libtiff"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/tiff-*/\nexport CPPFLAGS=\"-I${prefix}/include\"\n\n./configure --prefix=$prefix --host=$target\nmake -j${nproc}\nmake install\n"""
version = "v4.1.0"

[[dependencies]]
name = "JpegTurbo_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Zlib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Zstd_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtiff"]
type = "lib"
variable_name = "libtiff"

[[sources]]
hash = "5d29f32517dadb6dbcd1255ea5bbc93a2b54b94fbf83653b4d65c7d6775b8634"
type = "archive"
unpack_target = ""
url = "https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz"
