buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f900c288778227fc8157b72fdba79f88b5ba1cf9/R/RadeonProRender/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.8"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "RadeonProRender"
platforms = ["x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """echo ${target}\ncd $WORKSPACE/srcdir/RadeonProRenderSDK/RadeonProRender\nif [[ ${target} == x86_64-linux-gnu ]]; then\n    cp -v binUbuntu*/* ${libdir}/\nelif [[ ${target} == *-apple-darwin* ]]; then\n    cp binMacOS/* ${libdir}/\nelif [[ ${target} == *-mingw* ]]; then\n    cp binWin64/* ${libdir}/\nfi\n\nmkdir -p \"${includedir}\"\ncp -Rv inc/* \"${includedir}\"\n"""
version = "v3.1.5"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["Northstar64", "libNorthstar64"]
    type = "lib"
    variable_name = "libNorthstar64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["ProRenderGLTF", "libProRenderGLTF"]
    type = "lib"
    variable_name = "libProRenderGLTF"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["RadeonProRender64", "libRadeonProRender64"]
    type = "lib"
    variable_name = "libRadeonProRender64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["RprLoadStore64", "libRprLoadStore64"]
    type = "lib"
    variable_name = "libRprLoadStore64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["Tahoe64", "libTahoe64"]
    type = "lib"
    variable_name = "libTahoe64"

    [[metadata.sources]]
    hash = "40cfdbcb7362927f833a2ee09458a63f029ee69d"
    type = "git"
    unpack_target = ""
    url = "https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK.git"
