buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/65c3842ff2e2ed2c95e9a42978ef9452a3c3797c/R/RadeonProRender/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.2"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "RadeonProRender"
platforms = ["x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """echo ${target}\ncd $WORKSPACE/srcdir/RadeonProRenderSDK/RadeonProRender\nif [[ ${target} == x86_64-linux-gnu ]]; then\n    cp binUbuntu18/* ${libdir}/\nelif [[ ${target} == *-apple-darwin* ]]; then\n    cp binMacOS/* ${libdir}/\nelif [[ ${target} == *-mingw* ]]; then\n    cp binWin64/* ${libdir}/\nfi\n"""
version = "v2.2.12"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["Northstar64", "libNorthstar64"]
    type = "lib"
    variable_name = "libNorthstar64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["ProRenderGLTF", "libProRenderGLTF"]
    type = "lib"
    variable_name = "libProRenderGLTF"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["RadeonProRender64", "libRadeonProRender64"]
    type = "lib"
    variable_name = "libRadeonProRender64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["RprLoadStore64", "libRprLoadStore64"]
    type = "lib"
    variable_name = "libRprLoadStore64"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["Tahoe64", "libTahoe64"]
    type = "lib"
    variable_name = "libTahoe64"

    [[metadata.sources]]
    hash = "e284dfac04ee3a142603ba955a2bf8d11a78d945"
    type = "git"
    unpack_target = ""
    url = "https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK.git"
