augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Libtool"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libtool-*\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake\nmake install\n"""
version = "v2.4.7"

[[products]]
paths = ["bin/libtool"]
type = "file"
variable_name = "libtool"
[[products]]
paths = ["bin/libtoolize"]
type = "file"
variable_name = "libtoolize"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libltdl"]
type = "lib"
variable_name = "libltdl"

[[sources]]
hash = "04e96c2404ea70c590c546eba4202a4e12722c640016c12b9b2f1ce3d481e9a8"
type = "archive"
unpack_target = ""
url = "https://ftpmirror.gnu.org/libtool/libtool-2.4.7.tar.gz"
