dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "libplist"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libplist*/\n\n# This project uses bash-isms in its configuration\nexport CONFIG_SHELL=/bin/bash\nautoreconf -f -i\n\n# Build without python bindings\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n            --without-cython --enable-shared\n\nmake -j${nproc}\nmake install\n"""
version = "v2.2.0"

[[products]]
binnames = ["plistutil"]
type = "exe"
variable_name = "plistutil"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libplist", "libplist-2", "libplist-2.0"]
type = "lib"
variable_name = "libplist"

[[sources]]
hash = "c5a30e9267068436a75b5d00fcbf95cb9c1f4dcd"
type = "git"
unpack_target = ""
url = "https://github.com/libimobiledevice/libplist.git"
