augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "nghttp2"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/nghttp2-*\n\n./configure --prefix=$prefix --host=$target --build=${MACHTYPE} --enable-lib-only\nmake -j${nproc}\nmake install\n"""
version = "v1.47.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libnghttp2"]
type = "lib"
variable_name = "libnghttp2"

[[sources]]
hash = "68271951324554c34501b85190f22f2221056db69f493afc3bbac8e7be21e7cc"
type = "archive"
unpack_target = ""
url = "https://github.com/nghttp2/nghttp2/releases/download/v1.47.0/nghttp2-1.47.0.tar.xz"
