dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = true
name = "CUDA_compat"
platforms = ["x86_64-linux-gnu", "powerpc64le-linux-gnu", "aarch64-linux-gnu"]
script = """apk add rpm2cpio\nrpm2cpio compat.rpm | cpio -idmv\n\nmkdir -p ${libdir}\n\nmv usr/local/cuda-*/compat/* ${libdir}\n"""
version = "v11.6.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcuda"]
type = "lib"
variable_name = "libcuda"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libnvidia-ptxjitcompiler"]
type = "lib"
variable_name = "libnvidia_ptxjitcompiler"

[[sources]]
filename = "compat.rpm"
hash = "348bb6cd66042bd90bc58f7dd909962c3bc9c3eb7a4ef75aa3178aad9fc00d5a"
type = "file"
url = "https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-compat-11-6-510.39.01-1.x86_64.rpm"
[[sources]]
filename = "compat.rpm"
hash = "7407dec3754ac416f6e10b5448756c463e9ab068f588bd30afbfc8fd600c3b45"
type = "file"
url = "https://developer.download.nvidia.com/compute/cuda/repos/rhel8/ppc64le/cuda-compat-11-6-510.39.01-1.ppc64le.rpm"
[[sources]]
filename = "compat.rpm"
hash = "7d8eacda7955677839694ffb02f6d1444e2c66a0ff68327e5a82d2f0d8d994ac"
type = "file"
url = "https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-compat-11-6-510.39.01-1.aarch64.rpm"
