["1.1.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-linux-musl.tar.gz"]
registered = 2021-05-05T21:27:02.000Z

    [["1.1.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.0+0/ABC.v1.1.0.x86_64-linux-musl.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/04fc78a66f5149ee7d459e9e5a568dedd2b7214a/A/ABC/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.2"

        ["1.1.0+0".artifact_metadata.metadata]
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "ABC"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin"]
        script = """\nEXFLGS=\"-Wall -Wno-unused-function -Wno-write-strings -Wno-sign-compare -DSIZEOF_INT=4 -DABC_USE_CUDD=1 -DABC_USE_PTHREADS -Wno-unused-but-set-variable -fPIC\"\n\nif [[ ${nbits} == 32 ]]; then\n    EXFLGS=\"${EXFLGS} -DSIZEOF_VOID_P=4\"\n    EXFLGS=\"${EXFLGS} -DSIZEOF_LONG=4\"\n    EXFLGS=\"${EXFLGS} -DLIN\"\nelse\n    EXFLGS=\"${EXFLGS} -DSIZEOF_VOID_P=8\"\n    EXFLGS=\"${EXFLGS} -DSIZEOF_LONG=8\"\n    EXFLGS=\"${EXFLGS} -DLIN64\"\nfi\n\n# musl doesn't like readline\nif [[ ${target} != *\"musl\"* ]]; then\n    EXFLGS=\"${EXFLGS} -DABC_READLINE\"\nfi\n\ncd ${WORKSPACE}/srcdir/abc\n\n# it appears necessary to have the file(s) for the FileProduct(s) live in the destdir\ncp abc.rc ${prefix}/.\n\nmake -j${nproc} ABC_USE_STDINT_H=1 CFLAGS+=\"${EXFLGS}\" libabc.so\n# the abc Makefile always makes a .so  Fix that here.\nmv libabc.so libabc.${dlext}\nmkdir -p \"${libdir}\"\ncp libabc.${dlext} ${libdir}\n\nmake -j${nproc} ABC_USE_STDINT_H=1 CFLAGS+=\"${EXFLGS}\"\nmkdir -p \"${bindir}\"\ncp abc${exeext} ${bindir}\nchmod +x ${bindir}/*\ninstall_license copyright.txt\nexit\n"""
        version = "v1.1.0"

            [["1.1.0+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Readline_jll"
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["1.1.0+0".artifact_metadata.metadata.products]]
            binnames = ["abc"]
            type = "exe"
            variable_name = "abc"
            [["1.1.0+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libabc"]
            type = "lib"
            variable_name = "libabc"
            [["1.1.0+0".artifact_metadata.metadata.products]]
            paths = ["abc.rc"]
            type = "file"
            variable_name = "abc_rc"

            [["1.1.0+0".artifact_metadata.metadata.sources]]
            hash = "645752f7d651b07a0ebd7cac827d6ce5dd5bd266"
            type = "git"
            unpack_target = ""
            url = "https://github.com/berkeley-abc/abc.git"

["1.1.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv6l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv6l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-linux-musl.tar.gz"]
registered = 2023-03-29T23:56:28.000Z

    [["1.1.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv6l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv6l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/ABC_jll.jl/releases/download/ABC-v1.1.1+0/ABC.v1.1.1.x86_64-linux-musl.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/31c7e325ca53cb63db7414c4da2e9753c739547b/A/ABC/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        ["1.1.1+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.6"
        lazy_artifacts = false
        name = "ABC"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin"]
        script = """\nEXFLGS=\"-Wall -Wno-unused-function -Wno-write-strings -Wno-sign-compare -DSIZEOF_INT=4 -DABC_USE_CUDD=1 -DABC_USE_PTHREADS -Wno-unused-but-set-variable -fPIC\"\n\nif [[ ${nbits} == 32 ]]; then\n    EXFLGS=\"${EXFLGS} -DSIZEOF_VOID_P=4\"\n    EXFLGS=\"${EXFLGS} -DSIZEOF_LONG=4\"\n    EXFLGS=\"${EXFLGS} -DLIN\"\nelse\n    EXFLGS=\"${EXFLGS} -DSIZEOF_VOID_P=8\"\n    EXFLGS=\"${EXFLGS} -DSIZEOF_LONG=8\"\n    EXFLGS=\"${EXFLGS} -DLIN64\"\nfi\n\n# musl doesn't like readline\nif [[ ${target} != *\"musl\"* ]]; then\n    EXFLGS=\"${EXFLGS} -DABC_READLINE\"\nfi\n\ncd ${WORKSPACE}/srcdir/abc\n\n# it appears necessary to have the file(s) for the FileProduct(s) live in the destdir\ncp abc.rc ${prefix}/.\n\nmake -j${nproc} ABC_USE_STDINT_H=1 CFLAGS+=\"${EXFLGS}\" libabc.so\n# the abc Makefile always makes a .so  Fix that here.\nmv libabc.so libabc.${dlext}\nmkdir -p \"${libdir}\"\ncp libabc.${dlext} ${libdir}\n\nmake -j${nproc} ABC_USE_STDINT_H=1 CFLAGS+=\"${EXFLGS}\"\nmkdir -p \"${bindir}\"\ncp abc${exeext} ${bindir}\nchmod +x ${bindir}/*\ninstall_license copyright.txt\nexit\n"""
        version = "v1.1.1"

            [["1.1.1+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Readline_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["1.1.1+0".artifact_metadata.metadata.products]]
            binnames = ["abc"]
            type = "exe"
            variable_name = "abc"
            [["1.1.1+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libabc"]
            type = "lib"
            variable_name = "libabc"
            [["1.1.1+0".artifact_metadata.metadata.products]]
            paths = ["abc.rc"]
            type = "file"
            variable_name = "abc_rc"

            [["1.1.1+0".artifact_metadata.metadata.sources]]
            hash = "08d25f39f2ee717b688529e61acb695cec0deeed"
            type = "git"
            unpack_target = ""
            url = "https://github.com/berkeley-abc/abc.git"
