["0.1.0"]
artifact_urls = []
registered = 2018-08-09T10:04:18.000Z

["0.1.1"]
artifact_urls = []
registered = 2018-08-11T10:43:40.000Z

["0.1.2"]
artifact_urls = []
registered = 2018-08-27T13:41:01.000Z

["0.2.0"]
artifact_urls = []
registered = 2019-06-23T19:51:54.000Z

["0.2.1"]
artifact_urls = []
registered = 2019-08-06T13:05:53.000Z

["0.2.2"]
artifact_urls = []
registered = 2020-06-19T15:20:52.000Z

["0.2.3"]
artifact_urls = []
registered = 2020-06-23T08:20:58.000Z

["0.2.4"]
artifact_urls = ["https://github.com/JuliaReinforcementLearning/ArcadeLearningEnvironment.jl/releases/download/v0.2.3/ROMS.tar.gz"]
registered = 2021-05-01T06:43:33.000Z
