["3.18.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.18.0+0/azurite.v3.18.0.any.tar.gz"]
registered = 2022-07-12T22:19:07.000Z

    [["3.18.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.18.0+0/azurite.v3.18.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d3c681b034a10c0561ce0dc515e8f45e8a74fbcf/A/azurite/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/a/azurite/build_tarballs.jl/d3c681b034a10c0561ce0dc515e8f45e8a74fbcf.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"
    sources = []

["3.24.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.24.0+0/azurite.v3.24.0.any.tar.gz"]
registered = 2023-07-25T13:22:15.000Z

    [["3.24.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.24.0+0/azurite.v3.24.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ce890a174d8ae76214422d7360ce83feb0f817e0/A/azurite/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/a/azurite/build_tarballs.jl/ce890a174d8ae76214422d7360ce83feb0f817e0.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"
    sources = []

["3.29.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.29.0+0/azurite.v3.29.0.any.tar.gz"]
registered = 2024-02-22T23:20:46.000Z

    [["3.29.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/azurite_jll.jl/releases/download/azurite-v3.29.0+0/azurite.v3.29.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/60fcca23065cc5c64b106ba152752e092d149f32/A/azurite/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/a/azurite/build_tarballs.jl/60fcca23065cc5c64b106ba152752e092d149f32.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.7"
    sources = []
