init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SHTOOLS"
platforms = ["i686-linux-gnu-libgfortran3", "i686-linux-gnu-libgfortran4", "i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran3", "aarch64-linux-gnu-libgfortran4", "aarch64-linux-gnu-libgfortran5", "armv6l-linux-gnueabihf-libgfortran3", "armv6l-linux-gnueabihf-libgfortran4", "armv6l-linux-gnueabihf-libgfortran5", "armv7l-linux-gnueabihf-libgfortran3", "armv7l-linux-gnueabihf-libgfortran4", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran3", "powerpc64le-linux-gnu-libgfortran4", "powerpc64le-linux-gnu-libgfortran5", "i686-linux-musl-libgfortran3", "i686-linux-musl-libgfortran4", "i686-linux-musl-libgfortran5", "x86_64-linux-musl-libgfortran3", "x86_64-linux-musl-libgfortran4", "x86_64-linux-musl-libgfortran5", "aarch64-linux-musl-libgfortran3", "aarch64-linux-musl-libgfortran4", "aarch64-linux-musl-libgfortran5", "armv6l-linux-musleabihf-libgfortran3", "armv6l-linux-musleabihf-libgfortran4", "armv6l-linux-musleabihf-libgfortran5", "armv7l-linux-musleabihf-libgfortran3", "armv7l-linux-musleabihf-libgfortran4", "armv7l-linux-musleabihf-libgfortran5", "x86_64-apple-darwin-libgfortran3", "x86_64-apple-darwin-libgfortran4", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5", "x86_64-unknown-freebsd-libgfortran3", "x86_64-unknown-freebsd-libgfortran4", "x86_64-unknown-freebsd-libgfortran5", "i686-w64-mingw32-libgfortran3", "i686-w64-mingw32-libgfortran4", "i686-w64-mingw32-libgfortran5", "x86_64-w64-mingw32-libgfortran3", "x86_64-w64-mingw32-libgfortran4", "x86_64-w64-mingw32-libgfortran5"]
script = """cd $WORKSPACE/srcdir/SHTOOLS-*\n\n# Patch source code\n# Don't use libtool\natomic_patch -p0 $WORKSPACE/srcdir/patches/no-libtool.patch\n# Correct C interface for MakeGradientDH (see <https://github.com/SHTOOLS/SHTOOLS/issues/328>)\natomic_patch -p1 $WORKSPACE/srcdir/patches/correct-cMakeGradientDH.patch\n\n# Build and install static libraries\nmake fortran -j${nproc} F95FLAGS=\"-fPIC -O3 -std=gnu\"\nmake fortran-mp -j${nproc} F95FLAGS=\"-fPIC -O3 -std=gnu\"\nmake install PREFIX=${prefix}\n\n# Create shared libraries\n# TODO: Do we need to add \" | cut -d' ' -f1\"?\nwhole_archive=$(flagon --whole-archive)\nif [ -n \"${whole_archive}\" ]; then\n    whole_archive=\"-Wl,${whole_archive}\"\nfi\nno_whole_archive=$(flagon --no-whole-archive)\nif [ -n \"${no_whole_archive}\" ]; then\n    no_whole_archive=\"-Wl,${no_whole_archive}\"\nfi\ngfortran -shared -o ${libdir}/libSHTOOLS.${dlext} ${whole_archive} ${prefix}/lib/libSHTOOLS.a ${no_whole_archive} -lfftw3 -lopenblas -lm\ngfortran -fopenmp -shared -o ${libdir}/libSHTOOLS-mp.${dlext} ${whole_archive} ${prefix}/lib/libSHTOOLS-mp.a ${no_whole_archive} -lfftw3 -lopenblas -lm\n"""
version = "v4.9.1"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "FFTW_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenBLAS32_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libSHTOOLS"]
type = "lib"
variable_name = "libSHTOOLS"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libSHTOOLS-mp"]
type = "lib"
variable_name = "libSHTOOLS_mp"

[[sources]]
hash = "5c22064f9daf6e9aa08cace182146993aa6b25a6ea593d92572c59f4013d53c2"
type = "archive"
unpack_target = ""
url = "https://github.com/SHTOOLS/SHTOOLS/releases/download/v4.9.1/SHTOOLS-4.9.1.tar.gz"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
