augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libxls"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libxls-*/\n# libxls 1.6.3 adds -D_spawnv=spawnv to CFLAGS on mingw, which conflicts with\n# the spawnv declaration in mingw-w64's process.h when compiling xls2csv.\nsed -i 's/-D_spawnv=spawnv//' configure\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    ac_cv_func_malloc_0_nonnull=yes \\\n    ac_cv_func_realloc_0_nonnull=yes \nmake -j${nproc}\nmake install\n"""
toplevel_block = ""
version = "v1.6.3"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libxlsreader"]
type = "lib"
variable_name = "libxlsreader"

[[sources]]
hash = "b2fb836ea0b5253a352fb5ca55742e29f06f94f9421c5b8eeccef2e5d43f622c"
type = "archive"
unpack_target = ""
url = "https://github.com/libxls/libxls/releases/download/v1.6.3/libxls-1.6.3.tar.gz"
