dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Icestorm"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-apple-darwin", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11"]
script = """cd icestorm\nmake PREFIX=${prefix} ICEPROG=0 -j${nproc}\nmake install PREFIX=${prefix} ICEPROG=0\n"""
version = "v0.1.0"

[[products]]
binnames = ["iceunpack"]
type = "exe"
variable_name = "iceunpack"
[[products]]
binnames = ["icebox_diff"]
type = "exe"
variable_name = "icebox_diff"
[[products]]
binnames = ["icebox_stat"]
type = "exe"
variable_name = "icebox_stat"
[[products]]
binnames = ["icebox_colbuf"]
type = "exe"
variable_name = "icebox_colbuf"
[[products]]
binnames = ["icebox_maps"]
type = "exe"
variable_name = "icebox_maps"
[[products]]
binnames = ["icebox_explain"]
type = "exe"
variable_name = "icebox_explain"
[[products]]
binnames = ["icebox_chipdb"]
type = "exe"
variable_name = "icebox_chipdb"
[[products]]
binnames = ["icepll"]
type = "exe"
variable_name = "icepll"
[[products]]
binnames = ["icebox_html"]
type = "exe"
variable_name = "icebox_html"
[[products]]
binnames = ["icemulti"]
type = "exe"
variable_name = "icemulti"
[[products]]
binnames = ["icebox_asc2hlc"]
type = "exe"
variable_name = "icebox_asc2hlc"
[[products]]
binnames = ["icebox_hlc2asc"]
type = "exe"
variable_name = "icebox_hlc2asc"
[[products]]
binnames = ["icebox_vlog"]
type = "exe"
variable_name = "icebox_vlog"
[[products]]
binnames = ["icebram"]
type = "exe"
variable_name = "icebram"
[[products]]
binnames = ["icepack"]
type = "exe"
variable_name = "icepack"
[[products]]
binnames = ["icetime"]
type = "exe"
variable_name = "icetime"

[[sources]]
hash = "c495861c19bd0976c88d4964f912abe76f3901c3"
type = "git"
unpack_target = ""
url = "https://github.com/YosysHQ/icestorm.git"
