augment_platform_block = """using Base.BinaryPlatforms\n\n# Can't use Preferences since we might be running this very early with a non-existing Manifest\nNEO_jll_uuid = Base.UUID(\"700fe977-ac61-5f37-bbc8-c6c4b2b6a9fd\")\nconst preferences = Base.get_preferences(NEO_jll_uuid)\nBase.record_compiletime_preference(NEO_jll_uuid, \"debug\")\nconst debug_preference = if haskey(preferences, \"debug\")\n    if isa(preferences[\"debug\"], Bool)\n        preferences[\"debug\"]\n    elseif isa(preferences[\"debug\"], String)\n        parsed = tryparse(Bool, preferences[\"debug\"])\n        if parsed === nothing\n            @error \"Debug preference is not valid; expected a boolean, but got '$(preferences[\"debug\"])'\"\n            nothing\n        else\n            parsed\n        end\n    else\n        @error \"Debug preference is not valid; expected a boolean, but got '$(preferences[\"debug\"])'\"\n        nothing\n    end\nelse\n    nothing\nend\n\nfunction augment_platform!(platform::Platform)\n    platform[\"debug\"] = string(something(debug_preference, false))\n    return platform\nend"""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = true
name = "NEO"
platforms = ["x86_64-linux-gnu-cxx11-debug+false", "x86_64-linux-gnu-cxx11-debug+true"]
script = ["""# ocloc segfaults after successful build and before exiting. So we wrap\n# a script around ocloc that detects when the build is reported\n# successful and ignores the segfault.\natomic_patch -p0 ./patches/ocloc.patch\n# Fix OpenCL ICD installation to use prefix instead of /etc\natomic_patch -p0 ./patches/install_to_prefix.patch\ncp ocloc_wrapper.sh compute-runtime/shared/source/built_ins/kernels/ocloc_wrapper.sh\nmkdir -p tmpdir\nexport TMPDIR=$(pwd)/tmpdir\nexport CCACHE_TEMPDIR=$(pwd)/tmpdir\ncd compute-runtime\ninstall_license LICENSE.md\n\n# revert a change that breaks the cxx03 build\n# https://github.com/intel/compute-runtime/issues/708\ngit revert 18c25e5aa3fc00c7d47469713adeace08a9aec07\n\n# work around compilation failures\n## already defined in gmmlib\nsed -i '/__stdcall/d' shared/source/gmm_helper/gmm_lib.h\n## extend LD_LIBRARY_PATH, don't overwrite it\nfind . \\( -name CMakeLists.txt -or -name '*.cmake' \\) -exec \\\n    sed -i 's/LD_LIBRARY_PATH=/LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH}:/g' '{}' \\;\n## NO\nsed -i '/-Werror/d' CMakeLists.txt\n\n# Fails because C header is used in C++ code\nsed -i 's/inttypes\\.h/cinttypes/g' level_zero/core/source/mutable_cmdlist/mutable_indirect_data.cpp\n\nCMAKE_FLAGS=()\n\n# Need C++20\nCMAKE_FLAGS+=(-DCMAKE_CXX_STANDARD=20)\n\n# Release build for best performance\nCMAKE_FLAGS+=(-DCMAKE_BUILD_TYPE=Release)\n\n        # Install things into $prefix\n        CMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n        # NOTE: NEO currently can't cross compile because of its IGC dependency\n        CMAKE_FLAGS+=(-DCMAKE_CROSSCOMPILING:BOOL=OFF)\n\n        # Explicitly use our cmake toolchain file\n        CMAKE_FLAGS+=(-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN})\n\n        # Don't run tests\n        CMAKE_FLAGS+=(-DSKIP_UNIT_TESTS:Bool=true)\n\n        # we don't care about cl_intel_va_api_media_sharing\n        CMAKE_FLAGS+=(-DDISABLE_LIBVA:Bool=true)\n\n        # additional hardware support\n        CMAKE_FLAGS+=(-DNEO_ENABLE_i915_PRELIM_DETECTION=TRUE)\n\n        # libigc installs libraries and pkgconfig rules in lib64, so look for them there.\n        # FIXME: shouldn't BinaryBuilder do this?\n        export PKG_CONFIG_PATH=${prefix}/lib64/pkgconfig:${prefix}/lib/pkgconfig\n\n        cmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\n        ninja -C build -j ${nproc} install\n        # Create unversioned symlinks\n        ln -s ocloc-25.44.1 ${bindir}/ocloc\n\n""", """# ocloc segfaults after successful build and before exiting. So we wrap\n# a script around ocloc that detects when the build is reported\n# successful and ignores the segfault.\natomic_patch -p0 ./patches/ocloc.patch\n# Fix OpenCL ICD installation to use prefix instead of /etc\natomic_patch -p0 ./patches/install_to_prefix.patch\ncp ocloc_wrapper.sh compute-runtime/shared/source/built_ins/kernels/ocloc_wrapper.sh\nmkdir -p tmpdir\nexport TMPDIR=$(pwd)/tmpdir\nexport CCACHE_TEMPDIR=$(pwd)/tmpdir\ncd compute-runtime\ninstall_license LICENSE.md\n\n# revert a change that breaks the cxx03 build\n# https://github.com/intel/compute-runtime/issues/708\ngit revert 18c25e5aa3fc00c7d47469713adeace08a9aec07\n\n# work around compilation failures\n## already defined in gmmlib\nsed -i '/__stdcall/d' shared/source/gmm_helper/gmm_lib.h\n## extend LD_LIBRARY_PATH, don't overwrite it\nfind . \\( -name CMakeLists.txt -or -name '*.cmake' \\) -exec \\\n    sed -i 's/LD_LIBRARY_PATH=/LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH}:/g' '{}' \\;\n## NO\nsed -i '/-Werror/d' CMakeLists.txt\n\n# Fails because C header is used in C++ code\nsed -i 's/inttypes\\.h/cinttypes/g' level_zero/core/source/mutable_cmdlist/mutable_indirect_data.cpp\n\nCMAKE_FLAGS=()\n\n# Need C++20\nCMAKE_FLAGS+=(-DCMAKE_CXX_STANDARD=20)\n\n# Release build for best performance\nCMAKE_FLAGS+=(-DCMAKE_BUILD_TYPE=Debug)\n\n        # Install things into $prefix\n        CMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n        # NOTE: NEO currently can't cross compile because of its IGC dependency\n        CMAKE_FLAGS+=(-DCMAKE_CROSSCOMPILING:BOOL=OFF)\n\n        # Explicitly use our cmake toolchain file\n        CMAKE_FLAGS+=(-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN})\n\n        # Don't run tests\n        CMAKE_FLAGS+=(-DSKIP_UNIT_TESTS:Bool=true)\n\n        # we don't care about cl_intel_va_api_media_sharing\n        CMAKE_FLAGS+=(-DDISABLE_LIBVA:Bool=true)\n\n        # additional hardware support\n        CMAKE_FLAGS+=(-DNEO_ENABLE_i915_PRELIM_DETECTION=TRUE)\n\n        # libigc installs libraries and pkgconfig rules in lib64, so look for them there.\n        # FIXME: shouldn't BinaryBuilder do this?\n        export PKG_CONFIG_PATH=${prefix}/lib64/pkgconfig:${prefix}/lib/pkgconfig\n\n        cmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\n        ninja -C build -j ${nproc} install\n        # Create unversioned symlinks\n        ln -s ocloc-25.44.1 ${bindir}/ocloc\n\n"""]
version = "v25.44.36015"

[[dependencies]]
compat = "=22.8.2"
name = "gmmlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "=2.22.2"
name = "libigc_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "=1.13"
name = "oneAPI_Level_Zero_Headers_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["ocloc"]
type = "exe"
variable_name = "ocloc"
[[products]]
dir_paths = ["lib/intel-opencl", "lib64/intel-opencl"]
dlopen_flags = []
dont_dlopen = false
libnames = ["libigdrcl"]
type = "lib"
variable_name = "libigdrcl"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libze_intel_gpu"]
type = "lib"
variable_name = "libze_intel_gpu"

[[sources]]
hash = "82bc8ddc7bc420f76eb975b4b58e48e4f78b1a24"
type = "git"
unpack_target = ""
url = "https://github.com/intel/compute-runtime.git"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
