augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Minuit2_Julia_Wrapper"
platforms = ["x86_64-linux-gnu-cxx03-julia_version+1.6.3", "x86_64-linux-gnu-cxx11-julia_version+1.6.3", "aarch64-linux-gnu-cxx03-julia_version+1.6.3", "aarch64-linux-gnu-cxx11-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx03-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx11-julia_version+1.6.3", "x86_64-apple-darwin-julia_version+1.6.3", "x86_64-w64-mingw32-cxx03-julia_version+1.6.3", "x86_64-w64-mingw32-cxx11-julia_version+1.6.3", "x86_64-linux-gnu-cxx03-julia_version+1.7.0", "x86_64-linux-gnu-cxx11-julia_version+1.7.0", "aarch64-linux-gnu-cxx03-julia_version+1.7.0", "aarch64-linux-gnu-cxx11-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.7.0", "x86_64-apple-darwin-julia_version+1.7.0", "aarch64-apple-darwin-julia_version+1.7.0", "x86_64-w64-mingw32-cxx03-julia_version+1.7.0", "x86_64-w64-mingw32-cxx11-julia_version+1.7.0", "x86_64-linux-gnu-cxx03-julia_version+1.8.2", "x86_64-linux-gnu-cxx11-julia_version+1.8.2", "aarch64-linux-gnu-cxx03-julia_version+1.8.2", "aarch64-linux-gnu-cxx11-julia_version+1.8.2", "powerpc64le-linux-gnu-cxx03-julia_version+1.8.2", "powerpc64le-linux-gnu-cxx11-julia_version+1.8.2", "x86_64-apple-darwin-julia_version+1.8.2", "aarch64-apple-darwin-julia_version+1.8.2", "x86_64-w64-mingw32-cxx03-julia_version+1.8.2", "x86_64-w64-mingw32-cxx11-julia_version+1.8.2", "x86_64-linux-gnu-cxx03-julia_version+1.9.0", "x86_64-linux-gnu-cxx11-julia_version+1.9.0", "aarch64-linux-gnu-cxx03-julia_version+1.9.0", "aarch64-linux-gnu-cxx11-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-apple-darwin-julia_version+1.9.0", "aarch64-apple-darwin-julia_version+1.9.0", "x86_64-w64-mingw32-cxx03-julia_version+1.9.0", "x86_64-w64-mingw32-cxx11-julia_version+1.9.0", "x86_64-linux-gnu-cxx03-julia_version+1.10.0", "x86_64-linux-gnu-cxx11-julia_version+1.10.0", "aarch64-linux-gnu-cxx03-julia_version+1.10.0", "aarch64-linux-gnu-cxx11-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-apple-darwin-julia_version+1.10.0", "aarch64-apple-darwin-julia_version+1.10.0", "x86_64-w64-mingw32-cxx03-julia_version+1.10.0", "x86_64-w64-mingw32-cxx11-julia_version+1.10.0", "x86_64-linux-gnu-cxx03-julia_version+1.11.1", "x86_64-linux-gnu-cxx11-julia_version+1.11.1", "aarch64-linux-gnu-cxx03-julia_version+1.11.1", "aarch64-linux-gnu-cxx11-julia_version+1.11.1", "powerpc64le-linux-gnu-cxx03-julia_version+1.11.1", "powerpc64le-linux-gnu-cxx11-julia_version+1.11.1", "x86_64-apple-darwin-julia_version+1.11.1", "aarch64-apple-darwin-julia_version+1.11.1", "x86_64-w64-mingw32-cxx03-julia_version+1.11.1", "x86_64-w64-mingw32-cxx11-julia_version+1.11.1", "x86_64-linux-gnu-cxx03-julia_version+1.12.0", "x86_64-linux-gnu-cxx11-julia_version+1.12.0", "aarch64-linux-gnu-cxx03-julia_version+1.12.0", "aarch64-linux-gnu-cxx11-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.12.0", "x86_64-apple-darwin-julia_version+1.12.0", "aarch64-apple-darwin-julia_version+1.12.0", "x86_64-w64-mingw32-cxx03-julia_version+1.12.0", "x86_64-w64-mingw32-cxx11-julia_version+1.12.0", "x86_64-linux-gnu-cxx03-julia_version+1.13.0", "x86_64-linux-gnu-cxx11-julia_version+1.13.0", "aarch64-linux-gnu-cxx03-julia_version+1.13.0", "aarch64-linux-gnu-cxx11-julia_version+1.13.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.13.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.13.0", "x86_64-apple-darwin-julia_version+1.13.0", "aarch64-apple-darwin-julia_version+1.13.0", "x86_64-w64-mingw32-cxx03-julia_version+1.13.0", "x86_64-w64-mingw32-cxx11-julia_version+1.13.0"]
script = """\ncmake ${WORKSPACE}/srcdir/Minuit2_Julia_Wrapper -B build \\\n    -DJulia_PREFIX=${prefix} \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DCMAKE_CXX_STANDARD=20\n\nVERBOSE=ON cmake --build build --config Release --target install -- -j${nproc}\n\ninstall_license Minuit2_Julia_Wrapper/LICENSE \n"""
version = "v0.4.0"

[[dependencies]]
compat = ""
name = "libjulia_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "0.14.4"
name = "libcxxwrap_julia_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "~6.34.2"
name = "Minuit2_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libMinuit2Wrap"]
type = "lib"
variable_name = "libMinuit2Wrap"
[[products]]
paths = ["Minuit2-export.jl"]
type = "file"
variable_name = "Minuit2_exports"

[[sources]]
hash = "0ecc01c10d1f8831d6b01753bc660a58d90756ae"
type = "git"
unpack_target = ""
url = "https://github.com/JuliaHEP/Minuit2_Julia_Wrapper.git"
