["0.0.20210320+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/FP16_jll.jl/releases/download/FP16-v0.0.20210320+0/FP16.v0.0.20210320.any.tar.gz"]
registered = 2022-09-03T17:21:55.000Z

    [["0.0.20210320+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/FP16_jll.jl/releases/download/FP16-v0.0.20210320+0/FP16.v0.0.20210320.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d6314eb2b0394d8533ed7febc50cda734c6e7e30/F/FP16/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/f/fp16/build_tarballs.jl/d6314eb2b0394d8533ed7febc50cda734c6e7e30.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

        [["0.0.20210320+0".artifact_metadata.sources]]
        hash = "0a92994d729ff76a58f692d3028ca1b64b145d91"
        type = "git"
        url = "https://github.com/Maratyszcza/FP16.git"

            ["0.0.20210320+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/fp16"
