augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "p7zip"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """macos_sdk_version=10.13\nmacosx_deployment_target=10.13\nif [[ \"${target}\" == x86_64-apple-darwin* ]]; then\n    echo \"Extracting MacOSX${macos_sdk_version}.sdk.tar.xz (this may take a while)\"\n    rm -rf /opt/${target}/${target}/sys-root/System\n    rm -rf /opt/${target}/${target}/sys-root/usr/include/libxml2/libxml\n    # extract the tarball into the sys-root so all compilers pick it up\n    # automatically, and use --warning=no-unknown-keyword to hide harmless\n    # warnings about unsupported pax header keywords like \"SCHILY.fflags\"\n    tar --extract \\\n        --file=${WORKSPACE}/srcdir/MacOSX${macos_sdk_version}.sdk.tar.xz \\\n        --directory=\"/opt/${target}/${target}/sys-root/.\" \\\n        --strip-components=1 \\\n        --warning=no-unknown-keyword \\\n        MacOSX${macos_sdk_version}.sdk/System \\\n        MacOSX${macos_sdk_version}.sdk/usr\n    export MACOSX_DEPLOYMENT_TARGET=${macosx_deployment_target}\nfi\ncd 7z/CPP/7zip/Bundles/Alone\n\n# RAR has a custom license\nexport DISABLE_RAR=1\n\nif [[ \"${target}\" == *-mingw* ]]; then\n    export IS_MINGW=1\n    export RC=windres\nfi\n\nif [[ \"${target}\" == x86_64-apple-darwin* ]]; then\n    # For some reason USE_ASM doesn't work on this platform\n    make -j${nproc} -f makefile.gcc\nelse\n    if [[ \"${target}\" == x86_64-* ]]; then\n        make -j${nproc} -f makefile.gcc IS_X64=1 USE_ASM=1 MY_ASM=\"uasm\"\n    elif [[ \"${target}\" == aarch64-* ]]; then\n        make -j${nproc} -f makefile.gcc IS_ARM64=1 USE_ASM=1\n    else\n        make -j${nproc} -f makefile.gcc\n    fi\nfi\n\ninstall -Dvm 755 _o/7za${exeext} \"${bindir}/7z${exeext}\"\ninstall_license ../../../../DOC/copying.txt\ninstall_license ../../../../DOC/License.txt\n"""
version = "v17.8.0"

[[dependencies]]
compat = ""
name = "UASM_jll"
platforms = ["any"]
top_level = false
type = "hostdependency"
uuid = "bbf38c07-751d-5a2b-a7fc-5c0acd9bd57e"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["7z"]
type = "exe"
variable_name = "p7zip"

[[sources]]
hash = "3e596155744af055a77fc433c703d54e3ea9212246287b5b1436a6beac060f16"
type = "archive"
unpack_target = "7z"
url = "https://downloads.sourceforge.net/project/sevenzip/7-Zip/26.00/7z2600-src.tar.xz"
[[sources]]
filename = "MacOSX10.13.sdk.tar.xz"
hash = "a3a077385205039a7c6f9e2c98ecdf2a720b2a819da715e03e0630c75782c1e4"
type = "file"
url = "https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.13.sdk.tar.xz"
