buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/29a31fcee125e8a0f37e5825945ee35e630d7ea1/J/juliaup/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "juliaup"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/juliaup\ncargo build --release\ninstall -Dm 755 \"target/${rust_target}/release/juliaup${exeext}\" \"${bindir}/juliaup${exeext}\"\ninstall -Dm 755 \"target/${rust_target}/release/julia${exeext}\" \"${bindir}/julia${exeext}\"\n"""
version = "v1.18.9"

    [[metadata.dependencies]]
    compat = ""
    name = "Libiconv_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["juliaup"]
    type = "exe"
    variable_name = "juliaup"
    [[metadata.products]]
    binnames = ["julia"]
    type = "exe"
    variable_name = "julia"

    [[metadata.sources]]
    hash = "a0841737fd01b13a06b56883bb852ecb6ca056d9"
    type = "git"
    unpack_target = ""
    url = "https://github.com/JuliaLang/juliaup.git"
