buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f771e039cbe82c42b3b800ce2ecdc185df5ee200/O/oneAPI_Level_Zero/oneAPI_Level_Zero_Headers/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.3.7"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "oneAPI_Level_Zero_Headers"
script = """cd level-zero\ninstall_license LICENSE\n\nmkdir -p ${includedir}/level_zero\nrsync --archive --exclude=\"*.py\" include/ ${includedir}/level_zero\n"""
version = "v1.1.2"

    [[metadata.products]]
    paths = ["include/level_zero/ze_api.h"]
    type = "file"
    variable_name = "ze_api"

    [[metadata.sources]]
    hash = "bb89202bfd8c5e05b54d16fc8d9ad9e6c7142a09"
    type = "git"
    unpack_target = ""
    url = "https://github.com/oneapi-src/level-zero.git"
