init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "msolve"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "x86_64-apple-darwin"]
script = """cd $WORKSPACE/srcdir\ncd msolve/\n./autogen.sh\nac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ./configure --with-gnu-ld --prefix=${prefix} --build=${MACHTYPE} --host=${target} --disable-openmp\nmake -j${nprocs}\nmake install\n"""
version = "v0.1.3"

[[dependencies]]
compat = "6.1.2"
name = "GMP_jll"
type = "dependency"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "~200.700"
name = "FLINT_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MPFR_jll"
type = "dependency"
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmsolve"]
type = "lib"
variable_name = "libmsolve"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libneogb"]
type = "lib"
variable_name = "libneogb"

[[sources]]
hash = "0e6de1bab447381b7fdf42c3c414caa6ed2a8f88"
type = "git"
unpack_target = ""
url = "https://gitlab.lip6.fr/safey/msolve.git"
