augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "CoverM"
platforms = ["x86_64-linux-gnu", "x86_64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin"]
script = """cd $WORKSPACE/srcdir/CoverM/\ncargo build --release\ninstall -Dvm 0755 \"target/${rust_target}/release/coverm${exeext}\" \"${bindir}/coverm${exeext}\"\ninstall_license LICENCE.txt\n"""
version = "v0.6.1"

[[products]]
binnames = ["coverm"]
type = "exe"
variable_name = "coverm"

[[sources]]
hash = "0056336d4b245064a23e5b40197b29607fb1fe56"
type = "git"
unpack_target = ""
url = "https://github.com/wwood/CoverM"
