buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2c320e93b306272fbeb19d5d7c57700ce62bf191/L/LSODA/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.6"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LSODA"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/liblsoda*\nfor f in ${WORKSPACE}/srcdir/patches/*.patch; do\n    atomic_patch -p1 ${f}\ndone\nmake -j${nproc} CC=cc\ninstall -Dvm 755 \"src/liblsoda.${dlext}\" \"${libdir}/liblsoda.${dlext}\"\n"""
version = "v0.1.2"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["liblsoda"]
    type = "lib"
    variable_name = "liblsoda"

    [[metadata.sources]]
    hash = "014a16bfa199eaffcf641eafdce8dcc487bfe9d9"
    type = "git"
    unpack_target = ""
    url = "https://github.com/sdwfrost/liblsoda.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
