augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "MozillaCACerts"
script = """install -Dvm 0644 \"${WORKSPACE}/srcdir/cacert.pem\" \"${prefix}/share/cacert.pem\"\ninstall_license /usr/share/licenses/MPL2\n"""
version = "v2024.12.31"

[[products]]
paths = ["share/cacert.pem"]
type = "file"
variable_name = "cacert"

[[sources]]
filename = "cacert.pem"
hash = "a3f328c21e39ddd1f2be1cea43ac0dec819eaa20a90425d7da901a11531b3aa5"
type = "file"
url = "https://curl.haxx.se/ca/cacert-2024-12-31.pem"
