augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "MozillaCACerts"
script = """install -Dvm 0644 \"${WORKSPACE}/srcdir/cacert.pem\" \"${prefix}/share/cacert.pem\"\ninstall_license /usr/share/licenses/MPL2\n"""
version = "v2025.9.9"

[[products]]
paths = ["share/cacert.pem"]
type = "file"
variable_name = "cacert"

[[sources]]
filename = "cacert.pem"
hash = "f290e6acaf904a4121424ca3ebdd70652780707e28e8af999221786b86bb1975"
type = "file"
url = "https://curl.haxx.se/ca/cacert-2025-09-09.pem"
