buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2d07bff8b2e601306f34d274954ef5193ccd4b0e/C/CUDA/CUDSS/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.5"

[metadata]
augment_platform_block = """using Base.BinaryPlatforms\n\ntry\n    using CUDA_Runtime_jll\ncatch\n    # during initial package installation, CUDA_Runtime_jll may not be available.\n    # in that case, we just won't select an artifact.\nend\n\n# can't use Preferences for the same reason\nconst CUDA_Runtime_jll_uuid = Base.UUID(\"76a88914-d11a-5bdc-97e0-2f5a05c973a2\")\nconst preferences = Base.get_preferences(CUDA_Runtime_jll_uuid)\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"version\")\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"local\")\nconst local_toolkit = something(tryparse(Bool, get(preferences, \"local\", \"false\")), false)\n\nfunction cuda_comparison_strategy(_a::String, _b::String, a_requested::Bool, b_requested::Bool)\n    # if we're using a local toolkit, we can't use artifacts\n    if local_toolkit\n        return false\n    end\n\n    # if either isn't a version number (e.g. \"none\"), perform a simple equality check\n    a = tryparse(VersionNumber, _a)\n    b = tryparse(VersionNumber, _b)\n    if a === nothing || b === nothing\n        return _a == _b\n    end\n\n    # if both b and a requested, then we fall back to equality\n    if a_requested && b_requested\n        return Base.thisminor(a) == Base.thisminor(b)\n    end\n\n    # otherwise, do the comparison between the the single version cap and the single version:\n    function is_compatible(artifact::VersionNumber, host::VersionNumber)\n        if host >= v\"11.0\"\n            # enhanced compatibility, semver-style\n            artifact.major == host.major &&\n            Base.thisminor(artifact) <= Base.thisminor(host)\n        else\n            Base.thisminor(artifact) == Base.thisminor(host)\n        end\n    end\n    if a_requested\n        is_compatible(b, a)\n    else\n        is_compatible(a, b)\n    end\nend\n\nfunction augment_platform!(platform::Platform)\n    if !@isdefined(CUDA_Runtime_jll)\n        # don't set to nothing or Pkg will download any artifact\n        platform[\"cuda\"] = \"none\"\n    end\n\n    if !haskey(platform, \"cuda\")\n        CUDA_Runtime_jll.augment_platform!(platform)\n    end\n    BinaryPlatforms.set_compare_strategy!(platform, \"cuda\", cuda_comparison_strategy)\n\n    return platform\nend"""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = true
name = "CUDSS"
platforms = ["x86_64-linux-gnu-cuda+12.0", "aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0", "aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0", "x86_64-w64-mingw32-cuda+12.0", "x86_64-linux-gnu-cuda+13.0", "aarch64-linux-gnu-cuda+13.0", "x86_64-w64-mingw32-cuda+13.0"]
script = """mkdir -p ${libdir} ${prefix}/include\n\ncd ${WORKSPACE}/srcdir\nif [[ ${target} == *-linux-gnu ]]; then\n\n    cd libcudss-*\n    install_license LICENSE\n    mv lib/libcudss*.so* ${libdir}\n    mv include/* ${prefix}/include\n\nelif [[ ${target} == x86_64-w64-mingw32 ]]; then\n\n    cd libcudss-*\n    install_license LICENSE\n    mv lib/cudss*.lib ${prefix}/lib\n    mv bin/cudss*.dll ${libdir}\n    mv include/* ${prefix}/include\n\n    # fixup\n    chmod +x ${libdir}/*.dll\nfi\n"""
version = "v0.7.1"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_Runtime_jll"
    platforms = ["any"]
    top_level = false
    type = "runtimedependency"
    uuid = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libcudss", "cudss64_0"]
    type = "lib"
    variable_name = "libcudss"

    [[metadata.sources]]
    hash = "946571d9ea164f948e402dd97a14541cb90fbec800336cfa7ae644af5937632f"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-x86_64/libcudss-linux-x86_64-0.7.1.4_cuda12-archive.tar.xz"
    [[metadata.sources]]
    hash = "f283c31b6badf4a5277014295705eac8e6e28f27de30d746719ea1cef7a750b8"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-aarch64/libcudss-linux-aarch64-0.7.1.4_cuda12-archive.tar.xz"
    [[metadata.sources]]
    hash = "a4ddd47ad711243bbea0da2d6520799595cc8d79aa740927e0855c0b8cb69cf8"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-sbsa/libcudss-linux-sbsa-0.7.1.4_cuda12-archive.tar.xz"
    [[metadata.sources]]
    hash = "b27a8af56a66ea4a15dadb6f3d4c3f8ce3acdc987d911f99b56801643b99528a"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/windows-x86_64/libcudss-windows-x86_64-0.7.1.4_cuda12-archive.zip"
    [[metadata.sources]]
    hash = "84b34ebe7fad40ec10f2aab2957a63b6070bd8ce16e3ada3e6bcac7317256347"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-x86_64/libcudss-linux-x86_64-0.7.1.4_cuda13-archive.tar.xz"
    [[metadata.sources]]
    hash = "de8295cb6773992bd1ca7e2ad93caae1fd18eba39175f0101b85d53abd3e0179"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-sbsa/libcudss-linux-sbsa-0.7.1.4_cuda13-archive.tar.xz"
    [[metadata.sources]]
    hash = "545cd15505d7c3b6e3f2af5209ea5be33e764a92194dc9d05fa8d50a1320a86a"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/windows-x86_64/libcudss-windows-x86_64-0.7.1.4_cuda13-archive.zip"
