buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3d606377c53491f5ddad517de6bc273326ec8f4c/C/CUDA/CUDSS/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.8"

[metadata]
augment_platform_block = """using Base.BinaryPlatforms\n\ntry\n    using CUDA_Runtime_jll\ncatch\n    # during initial package installation, CUDA_Runtime_jll may not be available.\n    # in that case, we just won't select an artifact.\nend\n\n# can't use Preferences for the same reason\nconst CUDA_Runtime_jll_uuid = Base.UUID(\"76a88914-d11a-5bdc-97e0-2f5a05c973a2\")\nconst preferences = Base.get_preferences(CUDA_Runtime_jll_uuid)\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"version\")\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"local\")\nconst local_toolkit = something(tryparse(Bool, get(preferences, \"local\", \"false\")), false)\n\nfunction cuda_comparison_strategy(_a::String, _b::String, a_requested::Bool, b_requested::Bool)\n    # if we're using a local toolkit, we can't use artifacts\n    if local_toolkit\n        return false\n    end\n\n    # if either isn't a version number (e.g. \"none\"), perform a simple equality check\n    a = tryparse(VersionNumber, _a)\n    b = tryparse(VersionNumber, _b)\n    if a === nothing || b === nothing\n        return _a == _b\n    end\n\n    # if both b and a requested, then we fall back to equality\n    if a_requested && b_requested\n        return Base.thisminor(a) == Base.thisminor(b)\n    end\n\n    # otherwise, do the comparison between the the single version cap and the single version:\n    function is_compatible(artifact::VersionNumber, host::VersionNumber)\n        if host >= v\"11.0\"\n            # enhanced compatibility, semver-style\n            artifact.major == host.major &&\n            Base.thisminor(artifact) <= Base.thisminor(host)\n        else\n            Base.thisminor(artifact) == Base.thisminor(host)\n        end\n    end\n    if a_requested\n        is_compatible(b, a)\n    else\n        is_compatible(a, b)\n    end\nend\n\nfunction augment_platform!(platform::Platform)\n    if !@isdefined(CUDA_Runtime_jll)\n        # don't set to nothing or Pkg will download any artifact\n        platform[\"cuda\"] = \"none\"\n    end\n\n    if !haskey(platform, \"cuda\")\n        CUDA_Runtime_jll.augment_platform!(platform)\n    end\n    BinaryPlatforms.set_compare_strategy!(platform, \"cuda\", cuda_comparison_strategy)\n\n    # store the fact that we're using a local CUDA toolkit, for debugging purposes\n    platform[\"cuda_local\"] = string(local_toolkit)\n\n    return platform\nend"""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = true
name = "CUDSS"
platforms = ["x86_64-linux-gnu-cuda+12.0", "aarch64-linux-gnu-cuda+12.0", "x86_64-w64-mingw32-cuda+12.0"]
script = """mkdir -p ${libdir} ${prefix}/include\n\ncd ${WORKSPACE}/srcdir\nif [[ ${target} == *-linux-gnu ]]; then\n\n    cd libcudss-*\n    install_license LICENSE\n    mv lib/libcudss*.so* ${libdir}\n    mv include/* ${prefix}/include\n\nelif [[ ${target} == x86_64-w64-mingw32 ]]; then\n\n    cd libcudss-*\n    install_license LICENSE\n    mv lib/cudss.lib ${prefix}/lib\n    mv bin/cudss*64_*.dll ${libdir}\n    mv include/* ${prefix}/include\n\n    # fixup\n    chmod +x ${libdir}/*.dll\nfi\n"""
version = "v0.2.1"

    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_Runtime_jll"
    platforms = ["any"]
    top_level = false
    type = "runtimedependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libcudss", "cudss64_0"]
    type = "lib"
    variable_name = "libcudss"

    [[metadata.sources]]
    hash = "7b57df176b79d9566f2e1cd92aa30924650bacde96b25cb95392d503ba5e1634"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-x86_64/libcudss-linux-x86_64-0.2.1.3_cuda12-archive.tar.xz"
    [[metadata.sources]]
    hash = "12503d270fe969b521bbe615a9ef00805d56487e3b2a4143899c27329c22b4e7"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-sbsa/libcudss-linux-sbsa-0.2.1.3_cuda12-archive.tar.xz"
    [[metadata.sources]]
    hash = "0353c12dde22283a3672bf28aeedbc663f76066ac1b22a33930ceb9dcb658983"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/windows-x86_64/libcudss-windows-x86_64-0.2.1.3_cuda12-archive.zip"
