dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Giflib"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/giflib-*/\n# Apply patch to make it possible to build for non Linux-like platforms.\n# Adapted from also https://sourceforge.net/p/giflib/bugs/133/\natomic_patch -p1 ../patches/makefile.patch\nmake -j${nproc}\nmake install\nrm \"${libdir}/libgif.a\"\ninstall_license COPYING\n"""
version = "v5.2.1"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libgif"]
type = "lib"
variable_name = "libgif"

[[sources]]
hash = "31da5562f44c5f15d63340a09a4fd62b48c45620cd302f77a6d9acf0077879bd"
type = "archive"
unpack_target = ""
url = "https://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
