augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "abseil_cpp"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/abseil-cpp\n\n# ABSL_RANDOM_HWAES_*_FLAGS are used to set ABSL_RANDOM_RANDEN_COPTS,\n# which is used when compiling absl/random/internal/randen_hwaes.cc\n\n# Output ABSL_RANDOM_RANDEN_COPTS during configure\natomic_patch -p1 ../patches/cmake-copts.patch\n\n# Allow setting \"-march=armv8-a+crypto\"\nfind $(dirname $(which $CC)) -type f \\\n    | xargs grep --files-with-matches 'BinaryBuilder: Cannot force an architecture via -march' \\\n    | xargs -n1 sed -i -E 's/^if \\[\\[ (\" \\$\\{ARGS\\[@\\]\\} \" == \\*\"-march=\"\\*) \\]\\]; then/if [[\\n    \\1\\n    \\&\\& ! \" \\${ARGS[@]} \" == *\"-march=armv8-a+crypto\"*\\n]]; then/'\n\n# Do not attempt to set ABSL_RANDOM_HWAES_ARM32_FLAGS (Neon) for armv6l\nif [[ \"$bb_full_target\" == armv6l-* ]]; then\n    atomic_patch -p1 ../patches/arm-neon-cmake.patch\nfi\n\n# For some reason, the ABSL_RANDOM_HWAES_X64_FLAGS are applied for aarch64-apple-darwin,\n# and the ABSL_RANDOM_HWAES_ARM64_FLAGS are applied for x86_64-apple-darwin\nif [[ \"$target\" == aarch64-apple-darwin* ]]; then\n    atomic_patch -p1 ../patches/x86_64-aes-cmake.patch\nelif [[ \"$target\" == x86_64-apple-darwin* ]]; then\n    atomic_patch -p1 ../patches/aarch64-crypto-cmake.patch\nfi\n\ncmake -B build -G Ninja \\\n    -DABSL_PROPAGATE_CXX_STD=OFF \\\n    -DBUILD_SHARED_LIBS=ON \\\n    -DBUILD_TESTING=OFF \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DCMAKE_CXX_STANDARD=14 \\\n    -DCMAKE_FIND_ROOT_PATH=${prefix} \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN}\ncmake --build build --parallel ${nproc}\ncmake --install build\ninstall_license LICENSE\n"""
version = "v20230125.0.0"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_bad_any_cast_impl"]
type = "lib"
variable_name = "libabsl_bad_any_cast_impl"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_bad_optional_access"]
type = "lib"
variable_name = "libabsl_bad_optional_access"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_bad_variant_access"]
type = "lib"
variable_name = "libabsl_bad_variant_access"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_base"]
type = "lib"
variable_name = "libabsl_base"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_city"]
type = "lib"
variable_name = "libabsl_city"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_civil_time"]
type = "lib"
variable_name = "libabsl_civil_time"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cord"]
type = "lib"
variable_name = "libabsl_cord"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cord_internal"]
type = "lib"
variable_name = "libabsl_cord_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cordz_functions"]
type = "lib"
variable_name = "libabsl_cordz_functions"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cordz_handle"]
type = "lib"
variable_name = "libabsl_cordz_handle"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cordz_info"]
type = "lib"
variable_name = "libabsl_cordz_info"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_cordz_sample_token"]
type = "lib"
variable_name = "libabsl_cordz_sample_token"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_crc32c"]
type = "lib"
variable_name = "libabsl_crc32c"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_crc_cord_state"]
type = "lib"
variable_name = "libabsl_crc_cord_state"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_crc_cpu_detect"]
type = "lib"
variable_name = "libabsl_crc_cpu_detect"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_crc_internal"]
type = "lib"
variable_name = "libabsl_crc_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_debugging_internal"]
type = "lib"
variable_name = "libabsl_debugging_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_demangle_internal"]
type = "lib"
variable_name = "libabsl_demangle_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_die_if_null"]
type = "lib"
variable_name = "libabsl_die_if_null"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_examine_stack"]
type = "lib"
variable_name = "libabsl_examine_stack"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_exponential_biased"]
type = "lib"
variable_name = "libabsl_exponential_biased"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_failure_signal_handler"]
type = "lib"
variable_name = "libabsl_failure_signal_handler"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags"]
type = "lib"
variable_name = "libabsl_flags"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_commandlineflag"]
type = "lib"
variable_name = "libabsl_flags_commandlineflag"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_commandlineflag_internal"]
type = "lib"
variable_name = "libabsl_flags_commandlineflag_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_config"]
type = "lib"
variable_name = "libabsl_flags_config"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_internal"]
type = "lib"
variable_name = "libabsl_flags_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_marshalling"]
type = "lib"
variable_name = "libabsl_flags_marshalling"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_parse"]
type = "lib"
variable_name = "libabsl_flags_parse"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_private_handle_accessor"]
type = "lib"
variable_name = "libabsl_flags_private_handle_accessor"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_program_name"]
type = "lib"
variable_name = "libabsl_flags_program_name"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_reflection"]
type = "lib"
variable_name = "libabsl_flags_reflection"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_usage"]
type = "lib"
variable_name = "libabsl_flags_usage"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_flags_usage_internal"]
type = "lib"
variable_name = "libabsl_flags_usage_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_graphcycles_internal"]
type = "lib"
variable_name = "libabsl_graphcycles_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_hash"]
type = "lib"
variable_name = "libabsl_hash"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_hashtablez_sampler"]
type = "lib"
variable_name = "libabsl_hashtablez_sampler"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_int128"]
type = "lib"
variable_name = "libabsl_int128"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_leak_check"]
type = "lib"
variable_name = "libabsl_leak_check"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_entry"]
type = "lib"
variable_name = "libabsl_log_entry"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_flags"]
type = "lib"
variable_name = "libabsl_log_flags"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_globals"]
type = "lib"
variable_name = "libabsl_log_globals"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_initialize"]
type = "lib"
variable_name = "libabsl_log_initialize"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_check_op"]
type = "lib"
variable_name = "libabsl_log_internal_check_op"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_conditions"]
type = "lib"
variable_name = "libabsl_log_internal_conditions"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_format"]
type = "lib"
variable_name = "libabsl_log_internal_format"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_globals"]
type = "lib"
variable_name = "libabsl_log_internal_globals"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_log_sink_set"]
type = "lib"
variable_name = "libabsl_log_internal_log_sink_set"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_message"]
type = "lib"
variable_name = "libabsl_log_internal_message"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_nullguard"]
type = "lib"
variable_name = "libabsl_log_internal_nullguard"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_internal_proto"]
type = "lib"
variable_name = "libabsl_log_internal_proto"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_severity"]
type = "lib"
variable_name = "libabsl_log_severity"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_log_sink"]
type = "lib"
variable_name = "libabsl_log_sink"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_low_level_hash"]
type = "lib"
variable_name = "libabsl_low_level_hash"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_malloc_internal"]
type = "lib"
variable_name = "libabsl_malloc_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_periodic_sampler"]
type = "lib"
variable_name = "libabsl_periodic_sampler"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_distributions"]
type = "lib"
variable_name = "libabsl_random_distributions"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_distribution_test_util"]
type = "lib"
variable_name = "libabsl_random_internal_distribution_test_util"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_platform"]
type = "lib"
variable_name = "libabsl_random_internal_platform"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_pool_urbg"]
type = "lib"
variable_name = "libabsl_random_internal_pool_urbg"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_randen"]
type = "lib"
variable_name = "libabsl_random_internal_randen"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_randen_hwaes"]
type = "lib"
variable_name = "libabsl_random_internal_randen_hwaes"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_randen_hwaes_impl"]
type = "lib"
variable_name = "libabsl_random_internal_randen_hwaes_impl"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_randen_slow"]
type = "lib"
variable_name = "libabsl_random_internal_randen_slow"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_internal_seed_material"]
type = "lib"
variable_name = "libabsl_random_internal_seed_material"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_seed_gen_exception"]
type = "lib"
variable_name = "libabsl_random_seed_gen_exception"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_random_seed_sequences"]
type = "lib"
variable_name = "libabsl_random_seed_sequences"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_raw_hash_set"]
type = "lib"
variable_name = "libabsl_raw_hash_set"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_raw_logging_internal"]
type = "lib"
variable_name = "libabsl_raw_logging_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_scoped_set_env"]
type = "lib"
variable_name = "libabsl_scoped_set_env"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_spinlock_wait"]
type = "lib"
variable_name = "libabsl_spinlock_wait"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_stacktrace"]
type = "lib"
variable_name = "libabsl_stacktrace"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_status"]
type = "lib"
variable_name = "libabsl_status"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_statusor"]
type = "lib"
variable_name = "libabsl_statusor"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_str_format_internal"]
type = "lib"
variable_name = "libabsl_str_format_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_strerror"]
type = "lib"
variable_name = "libabsl_strerror"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_strings"]
type = "lib"
variable_name = "libabsl_strings"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_strings_internal"]
type = "lib"
variable_name = "libabsl_strings_internal"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_symbolize"]
type = "lib"
variable_name = "libabsl_symbolize"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_synchronization"]
type = "lib"
variable_name = "libabsl_synchronization"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_throw_delegate"]
type = "lib"
variable_name = "libabsl_throw_delegate"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_time"]
type = "lib"
variable_name = "libabsl_time"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libabsl_time_zone"]
type = "lib"
variable_name = "libabsl_time_zone"

[[sources]]
hash = "78be63686ba732b25052be15f8d6dee891c05749"
type = "git"
unpack_target = ""
url = "https://github.com/abseil/abseil-cpp"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
