augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Libmount"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/util-linux-*\n\nconfigure_flags=()\nif [[ ${nbits} == 32 ]]; then\n   # We disable the year 2038 check because we don't have an alternative on the affected systems\n   configure_flags+=(--disable-year2038)\nfi\n\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --disable-all-programs --enable-libblkid --enable-libmount ${configure_flags[@]}\nmake -j${nproc}\nmake install\n"""
version = "v2.40.2"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmount"]
type = "lib"
variable_name = "libmount"

[[sources]]
hash = "d78b37a66f5922d70edf3bdfb01a6b33d34ed3c3cafd6628203b2a2b67c8e8b3"
type = "archive"
unpack_target = ""
url = "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.2.tar.xz"
