["0.1.0"]
artifact_urls = []
registered = 2021-02-07T10:28:40.000Z

["0.2.0"]
artifact_urls = ["https://github.com/IFL-CAMP/iiwa_stack/archive/a4f132ad093d276e63040ddbbac6b2cd1facbdcc.tar.gz", "https://github.com/Kinovarobotics/kinova-ros/archive/93f66822ec073827eac5de59ebc2a3c5f06bf17f.tar.gz", "https://github.com/Kinovarobotics/ros_kortex/archive/7ba75b3e6293fe4af9fe64f35e877d1ff2613360.tar.gz"]
registered = 2022-06-03T10:29:37.000Z
