["0.1.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.0+0/TropicalGemmC.v0.1.0.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.0+0/TropicalGemmC.v0.1.0.x86_64-linux-gnu-cuda+12.1.tar.gz"]
registered = 2023-10-03T22:01:47.000Z

    [["0.1.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.0+0/TropicalGemmC.v0.1.0.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.0+0/TropicalGemmC.v0.1.0.x86_64-linux-gnu-cuda+12.1.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2df21ede9decc9b0645fba4459eed3e8a2e624fb/T/TropicalGemmC/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/t/tropicalgemmc/build_tarballs.jl/2df21ede9decc9b0645fba4459eed3e8a2e624fb.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["0.1.0+0".artifact_metadata.sources]]
        hash = "5510f1394e8b5dc4fc98df7ea640a54a417188a2"
        type = "git"
        url = "https://github.com/ArrogantGao/TropicalGemm_Cuda.git"
        [["0.1.0+0".artifact_metadata.sources]]
        package = "CUDA_full_jll"
        type = "builddependency"
        [["0.1.0+0".artifact_metadata.sources]]
        package = "CUDA_full_jll"
        type = "builddependency"

["0.1.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.2.tar.gz"]
registered = 2023-10-18T09:04:49.000Z

    [["0.1.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.1+0/TropicalGemmC.v0.1.1.x86_64-linux-gnu-cuda+12.2.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/5574e64a483f4f0c18cbfe36ae19b0a0f8474ad8/T/TropicalGemmC/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/t/tropicalgemmc/build_tarballs.jl/5574e64a483f4f0c18cbfe36ae19b0a0f8474ad8.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["0.1.1+0".artifact_metadata.sources]]
        hash = "5510f1394e8b5dc4fc98df7ea640a54a417188a2"
        type = "git"
        url = "https://github.com/ArrogantGao/TropicalGemm_Cuda.git"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.1+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"

["0.1.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.2.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.3.tar.gz"]
registered = 2023-12-07T14:01:03.000Z

    [["0.1.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.2.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.2+0/TropicalGemmC.v0.1.2.x86_64-linux-gnu-cuda+12.3.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/9de7628cda0696f6302839d6ec423bd6dfadd7fc/T/TropicalGemmC/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/t/tropicalgemmc/build_tarballs.jl/9de7628cda0696f6302839d6ec423bd6dfadd7fc.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["0.1.2+0".artifact_metadata.sources]]
        hash = "d80efc066bca8ac7fc4ce0ca2c40ec025793ccbd"
        type = "git"
        url = "https://github.com/ArrogantGao/TropicalGemm_Cuda.git"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.2+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"

["0.1.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.2.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.3.tar.gz"]
registered = 2023-12-17T19:19:04.000Z

    [["0.1.3+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.4.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.5.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.6.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.7.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+11.8.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.0.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.1.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.2.tar.gz", "https://github.com/JuliaBinaryWrappers/TropicalGemmC_jll.jl/releases/download/TropicalGemmC-v0.1.3+0/TropicalGemmC.v0.1.3.x86_64-linux-gnu-cuda+12.3.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/1281b9eae614421fd8c6e877154b59911416b097/T/TropicalGemmC/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/t/tropicalgemmc/build_tarballs.jl/1281b9eae614421fd8c6e877154b59911416b097.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        [["0.1.3+0".artifact_metadata.sources]]
        hash = "3a7dd44a5927f148c5c58c77dc4e0b027887fa58"
        type = "git"
        url = "https://github.com/ArrogantGao/TropicalGemm_Cuda.git"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["0.1.3+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
