dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "libCEED"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/libCEED\nmake -j${nproc} MEMCHK=0 CC_VENDOR=gcc\nmake install MEMCHK=0 CC_VENDOR=gcc\n"""
version = "v0.8.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libceed"]
type = "lib"
variable_name = "libceed"

[[sources]]
hash = "e8f234590eddcce2220edb1d6e979af7a3c35f82"
type = "git"
unpack_target = ""
url = "https://github.com/CEED/libCEED.git"
