buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/b0cb2ab72c912e5cbdf82847eaee40c8a9ab67a5/P/PCRE/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
system = "Yggdrasil"
version = "0.2.4"

[metadata]
dependencies = []
lazy_artifacts = false
name = "PCRE"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/pcre-*/\n./configure --prefix=$prefix --host=$target --enable-utf8 --enable-unicode-properties\nmake -j${nproc} VERBOSE=1\nmake install VERBOSE=1\n"""
version = "v8.42.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libpcre"]
    type = "lib"
    variable_name = "libpcre"

    [[metadata.sources]]
    hash = "2cd04b7c887808be030254e8d77de11d3fe9d4505c39d4b15d2664ffe8bf9301"
    type = "archive"
    unpack_target = ""
    url = "https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.bz2"
