buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ce8e5259b4f4168f82eb35296ea38b3e8cf96e96/L/libsingular_julia/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.8"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libsingular_julia"
platforms = ["i686-linux-gnu-cxx03-julia_version+1.6.3", "i686-linux-gnu-cxx11-julia_version+1.6.3", "x86_64-linux-gnu-cxx03-julia_version+1.6.3", "x86_64-linux-gnu-cxx11-julia_version+1.6.3", "aarch64-linux-gnu-cxx03-julia_version+1.6.3", "aarch64-linux-gnu-cxx11-julia_version+1.6.3", "armv7l-linux-gnueabihf-cxx03-julia_version+1.6.3", "armv7l-linux-gnueabihf-cxx11-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx03-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx11-julia_version+1.6.3", "x86_64-linux-musl-cxx03-julia_version+1.6.3", "x86_64-linux-musl-cxx11-julia_version+1.6.3", "aarch64-linux-musl-cxx03-julia_version+1.6.3", "aarch64-linux-musl-cxx11-julia_version+1.6.3", "armv7l-linux-musleabihf-cxx03-julia_version+1.6.3", "armv7l-linux-musleabihf-cxx11-julia_version+1.6.3", "x86_64-apple-darwin-julia_version+1.6.3", "x86_64-unknown-freebsd-julia_version+1.6.3", "i686-linux-gnu-cxx03-julia_version+1.7.0", "i686-linux-gnu-cxx11-julia_version+1.7.0", "x86_64-linux-gnu-cxx03-julia_version+1.7.0", "x86_64-linux-gnu-cxx11-julia_version+1.7.0", "aarch64-linux-gnu-cxx03-julia_version+1.7.0", "aarch64-linux-gnu-cxx11-julia_version+1.7.0", "armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0", "armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0", "armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0", "armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.7.0", "x86_64-linux-musl-cxx03-julia_version+1.7.0", "x86_64-linux-musl-cxx11-julia_version+1.7.0", "aarch64-linux-musl-cxx03-julia_version+1.7.0", "aarch64-linux-musl-cxx11-julia_version+1.7.0", "armv6l-linux-musleabihf-cxx03-julia_version+1.7.0", "armv6l-linux-musleabihf-cxx11-julia_version+1.7.0", "armv7l-linux-musleabihf-cxx03-julia_version+1.7.0", "armv7l-linux-musleabihf-cxx11-julia_version+1.7.0", "x86_64-apple-darwin-julia_version+1.7.0", "aarch64-apple-darwin-julia_version+1.7.0", "x86_64-unknown-freebsd-julia_version+1.7.0", "i686-linux-gnu-cxx03-julia_version+1.8.2", "i686-linux-gnu-cxx11-julia_version+1.8.2", "x86_64-linux-gnu-cxx03-julia_version+1.8.2", "x86_64-linux-gnu-cxx11-julia_version+1.8.2", "aarch64-linux-gnu-cxx03-julia_version+1.8.2", "aarch64-linux-gnu-cxx11-julia_version+1.8.2", "armv6l-linux-gnueabihf-cxx03-julia_version+1.8.2", "armv6l-linux-gnueabihf-cxx11-julia_version+1.8.2", "armv7l-linux-gnueabihf-cxx03-julia_version+1.8.2", "armv7l-linux-gnueabihf-cxx11-julia_version+1.8.2", "powerpc64le-linux-gnu-cxx03-julia_version+1.8.2", "powerpc64le-linux-gnu-cxx11-julia_version+1.8.2", "x86_64-linux-musl-cxx03-julia_version+1.8.2", "x86_64-linux-musl-cxx11-julia_version+1.8.2", "aarch64-linux-musl-cxx03-julia_version+1.8.2", "aarch64-linux-musl-cxx11-julia_version+1.8.2", "armv6l-linux-musleabihf-cxx03-julia_version+1.8.2", "armv6l-linux-musleabihf-cxx11-julia_version+1.8.2", "armv7l-linux-musleabihf-cxx03-julia_version+1.8.2", "armv7l-linux-musleabihf-cxx11-julia_version+1.8.2", "x86_64-apple-darwin-julia_version+1.8.2", "aarch64-apple-darwin-julia_version+1.8.2", "x86_64-unknown-freebsd-julia_version+1.8.2", "i686-linux-gnu-cxx03-julia_version+1.9.0", "i686-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-gnu-cxx03-julia_version+1.9.0", "x86_64-linux-gnu-cxx11-julia_version+1.9.0", "aarch64-linux-gnu-cxx03-julia_version+1.9.0", "aarch64-linux-gnu-cxx11-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-musl-cxx03-julia_version+1.9.0", "x86_64-linux-musl-cxx11-julia_version+1.9.0", "aarch64-linux-musl-cxx03-julia_version+1.9.0", "aarch64-linux-musl-cxx11-julia_version+1.9.0", "x86_64-apple-darwin-julia_version+1.9.0", "aarch64-apple-darwin-julia_version+1.9.0", "x86_64-unknown-freebsd-julia_version+1.9.0", "i686-linux-gnu-cxx03-julia_version+1.10.0", "i686-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-gnu-cxx03-julia_version+1.10.0", "x86_64-linux-gnu-cxx11-julia_version+1.10.0", "aarch64-linux-gnu-cxx03-julia_version+1.10.0", "aarch64-linux-gnu-cxx11-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-musl-cxx03-julia_version+1.10.0", "x86_64-linux-musl-cxx11-julia_version+1.10.0", "aarch64-linux-musl-cxx03-julia_version+1.10.0", "aarch64-linux-musl-cxx11-julia_version+1.10.0", "x86_64-apple-darwin-julia_version+1.10.0", "aarch64-apple-darwin-julia_version+1.10.0", "x86_64-unknown-freebsd-julia_version+1.10.0", "i686-linux-gnu-cxx03-julia_version+1.11.0", "i686-linux-gnu-cxx11-julia_version+1.11.0", "x86_64-linux-gnu-cxx03-julia_version+1.11.0", "x86_64-linux-gnu-cxx11-julia_version+1.11.0", "aarch64-linux-gnu-cxx03-julia_version+1.11.0", "aarch64-linux-gnu-cxx11-julia_version+1.11.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.11.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.11.0", "x86_64-linux-musl-cxx03-julia_version+1.11.0", "x86_64-linux-musl-cxx11-julia_version+1.11.0", "aarch64-linux-musl-cxx03-julia_version+1.11.0", "aarch64-linux-musl-cxx11-julia_version+1.11.0", "x86_64-apple-darwin-julia_version+1.11.0", "aarch64-apple-darwin-julia_version+1.11.0", "x86_64-unknown-freebsd-julia_version+1.11.0", "i686-linux-gnu-cxx03-julia_version+1.12.0", "i686-linux-gnu-cxx11-julia_version+1.12.0", "x86_64-linux-gnu-cxx03-julia_version+1.12.0", "x86_64-linux-gnu-cxx11-julia_version+1.12.0", "aarch64-linux-gnu-cxx03-julia_version+1.12.0", "aarch64-linux-gnu-cxx11-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.12.0", "x86_64-linux-musl-cxx03-julia_version+1.12.0", "x86_64-linux-musl-cxx11-julia_version+1.12.0", "aarch64-linux-musl-cxx03-julia_version+1.12.0", "aarch64-linux-musl-cxx11-julia_version+1.12.0", "x86_64-apple-darwin-julia_version+1.12.0", "aarch64-apple-darwin-julia_version+1.12.0", "x86_64-unknown-freebsd-julia_version+1.12.0"]
script = """cd Singular.jl/deps/src\ncmake . -B build \\\n   -DJulia_PREFIX=\"$prefix\" \\\n   -DSingular_PREFIX=\"$prefix\" \\\n   -DCMAKE_INSTALL_PREFIX=\"$prefix\" \\\n   -DCMAKE_FIND_ROOT_PATH=\"$prefix\" \\\n   -DCMAKE_TOOLCHAIN_FILE=\"${CMAKE_TARGET_TOOLCHAIN}\" \\\n   -DCMAKE_CXX_STANDARD=14 \\\n   -DCMAKE_BUILD_TYPE=Release\n\nVERBOSE=ON cmake --build build --config Release --target install -- -j${nproc}\n\n# store tree hash of the source directory\ngit ls-tree HEAD .. | cut -c13-52 > ${libdir}/libsingular_julia.treehash\n\ninstall_license ../../LICENSE.md\n"""
version = "v0.44.1"

    [[metadata.dependencies]]
    compat = ""
    name = "libjulia_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 1
    version-minor = 10
    version-patch = 9
    [[metadata.dependencies]]
    compat = ""
    name = "GMP_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "MPFR_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "~0.11.2"
    name = "libcxxwrap_julia_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Singular_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsingular_julia"]
    type = "lib"
    variable_name = "libsingular_julia"

    [[metadata.sources]]
    hash = "dead8eb25ed537c98e544779f7736f0a6e6558f1"
    type = "git"
    unpack_target = ""
    url = "https://github.com/oscar-system/Singular.jl.git"
