lazy_artifacts = false
name = "MariaDB_Connector_ODBC"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "x86_64-apple-darwin14", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """install_license $WORKSPACE/srcdir/mariadb-connector*/COPYING\n\nif [[ \"${target}\" == *-mingw* ]]; then\n    # For Windows just use the prebuilt library\n    mkdir -p \"${libdir}\"\n    cd $WORKSPACE/srcdir\n    apk add p7zip\n    7z x \"${target}.msi\"\n    cp mariadb_odbc_dll \"${libdir}/mariadb_odbc.dll\"\n    exit\nfi\n\ncd $WORKSPACE/srcdir/mariadb-connector*/\n\n# Skip building of macOS package\nsed -i 's/ADD_SUBDIRECTORY(osxinstall)/# ADD_SUBDIRECTORY(osxinstall)/' CMakeLists.txt\n\n## Keep this for reference in case we decide to build for Windows from source\n# if [[ \"${target}\" == *-mingw* ]]; then\n#     # Disable dialog plugin\n#     sed -i 's/-DPLUGINS_LIB_DIR.*:dialog.*//' CMakeLists.txt\n#     atomic_patch -p1 \"${WORKSPACE}/srcdir/patches/0001-fix-case-headers-windows.patch\"\n#     # The following is not really a patch: Microsoft Visual C++ thinks that it's\n#     # a good idea to put some stray characters in the first bits of the file,\n#     # making it hard to digest for MinGW.  We can't diff the file as the\n#     # original one appears to be binary, because of the stray character.\n#     cp \"${WORKSPACE}/srcdir/patches/resource.h\" dsn/\n# fi\n\nmkdir build && cd build\n\nexport CFLAGS=\"-I${includedir}/mariadb\"\n# Find the MariaDB lib and link to the right OpenSSL and Zlib libraries\nexport LDFLAGS=\"-L${libdir}/mariadb ${libdir}/libssl.${dlext} ${libdir}/libcrypto.${dlext} -lz\"\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DWITH_OPENSSL=ON \\\n    -DWITH_SSL=OPENSSL \\\n    -DOPENSSL_FOUND=ON \\\n    -DOPENSSL_CRYPTO_LIBRARY=${libdir}/libcrypto.${dlext} \\\n    -DOPENSSL_SSL_LIBRARY=${libdir}/libssl.${dlext} \\\n    -DICONV_LIBRARIES=${libdir}/libiconv.${dlext} \\\n    -DICONV_INCLUDE_DIR=${includedir} \\\n    ..\nmake -j${nproc}\nmake install\n"""
version = "v3.1.7"

[[dependencies]]
name = "MariaDB_Connector_C_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "iODBC_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Libiconv_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "unixODBC_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "OpenSSL_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Zlib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmaodbc", "mariadb_odbc"]
type = "lib"
variable_name = "libmaodbc"

[[sources]]
hash = "699c575e169d770ccfae1c1e776aa7725d849046476bf6579d292c89e8c8593e"
type = "archive"
unpack_target = ""
url = "https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-ga-src.tar.gz"
[[sources]]
filename = "x86_64-w64-mingw32.msi"
hash = "ef1ad796cc4aba67aa6606b35239302c579b7894604239d1caaa1f2d10623bd2"
type = "file"
url = "https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-win64.msi"
[[sources]]
filename = "i686-w64-mingw32.msi"
hash = "a60b74dc3af0b450d892731c2973037beef6fc972e0813f3db9f28f083a63402"
type = "file"
url = "https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-win32.msi"
