augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LibTeXPrintf"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libtexprintf/\n./autogen.sh\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-static=no --enable-shared=yes --enable-fast-install=yes\nmake -j${nproc}\nmake install\ninstall_license COPYING\n"""
version = "v1.21.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtexprintf"]
type = "lib"
variable_name = "libtexprintf"

[[sources]]
hash = "8bdbf8afdcbf305a5f1a1cef8fcaedab6c26d6fa"
type = "git"
unpack_target = ""
url = "https://github.com/bartp5/libtexprintf.git"
