buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/88cb7da1d87126c27e5b7e5acf64d8bf67d9cb6a/O/OpenFHE_int128/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "OpenFHE_int128"
platforms = ["x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/openfhe-development/\n\n# Set proper install directories for libraries on Windows\nif [[ \"${target}\" == *-mingw* ]]; then\n  atomic_patch -p1 \"${WORKSPACE}/srcdir/patches/windows-fix-cmake-libdir.patch\"\nfi\n\nmkdir build && cd build\n\n# Install newer SDK which supports `std::filesystem`\nif [[ \"${target}\" == x86_64-apple-darwin* ]]; then\n    export MACOSX_DEPLOYMENT_TARGET=10.15\n    rm -rf /opt/${target}/${target}/sys-root/System\n    tar --extract --file=${WORKSPACE}/srcdir/MacOSX10.15.sdk.tar.xz --directory=\"/opt/${target}/${target}/sys-root/.\" --strip-components=1 MacOSX10.15.sdk/System MacOSX10.15.sdk/usr\nfi\n\ncmake .. \\\n  -DCMAKE_INSTALL_PREFIX=$prefix \\\n  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n  -DCMAKE_BUILD_TYPE=Release \\\n  -DWITH_BE2=ON \\\n  -DWITH_BE4=ON \\\n  -DBUILD_UNITTESTS=OFF \\\n  -DBUILD_BENCHMARKS=OFF \\\n  -DNATIVE_SIZE=128\nmake -j${nproc}\nmake install\n"""
version = "v1.4.2"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "x86_64-w64-mingw32-cxx11"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "LLVMOpenMP_jll"
    platforms = ["x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
    top_level = false
    type = "dependency"
    uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libOPENFHEbinfhe"]
    type = "lib"
    variable_name = "libOPENFHEbinfhe"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libOPENFHEpke"]
    type = "lib"
    variable_name = "libOPENFHEpke"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libOPENFHEcore"]
    type = "lib"
    variable_name = "libOPENFHEcore"

    [[metadata.sources]]
    hash = "aa391988d354d4360f390f223a90e0d1b98839d7"
    type = "git"
    unpack_target = ""
    url = "https://github.com/openfheorg/openfhe-development.git"
    [[metadata.sources]]
    filename = "MacOSX10.15.sdk.tar.xz"
    hash = "2408d07df7f324d3beea818585a6d990ba99587c218a3969f924dfcc4de93b62"
    type = "file"
    url = "https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.15.sdk.tar.xz"
    [[metadata.sources]]
    follow_symlinks = false
    path = "../OpenFHE/bundled"
    target = ""
    type = "directory"
