["0.96.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx11.tar.gz"]
registered = 2020-10-01T20:46:52.000Z

["0.96.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-w64-mingw32-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-w64-mingw32-cxx11.tar.gz"]
registered = 2022-07-28T07:40:35.000Z

    [["0.96.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.i686-w64-mingw32-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.1+0/SARSOP.v0.96.1.x86_64-w64-mingw32-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a1b3930059b5ef818154fc7553c220829ff31066/S/SARSOP/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

        ["0.96.1+0".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.6"
        lazy_artifacts = false
        name = "SARSOP"
        platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
        script = """cd $WORKSPACE/srcdir\ncd sarsop/src\nmake -j${nprocs} CC=${CC} CXX=${CXX} LINKER=${CXX} DESTDIR=${prefix}\nmake install DESTDIR=${prefix}\nif [[ \"${target}\" == *mingw* ]]; then\n    for file in ${prefix}/bin/*;\n    do\n        mv $file $file.exe\n    done\nfi\ninstall_license ${WORKSPACE}/srcdir/sarsop/license/*\nexit\n"""
        version = "v0.96.1"

            [["0.96.1+0".artifact_metadata.metadata.products]]
            binnames = ["pomdpsim"]
            type = "exe"
            variable_name = "pomdpsim"
            [["0.96.1+0".artifact_metadata.metadata.products]]
            binnames = ["pomdpconvert"]
            type = "exe"
            variable_name = "pomdpconvert"
            [["0.96.1+0".artifact_metadata.metadata.products]]
            binnames = ["pomdpeval"]
            type = "exe"
            variable_name = "pomdpeval"
            [["0.96.1+0".artifact_metadata.metadata.products]]
            binnames = ["pomdpsol"]
            type = "exe"
            variable_name = "pomdpsol"
            [["0.96.1+0".artifact_metadata.metadata.products]]
            binnames = ["polgraph"]
            type = "exe"
            variable_name = "polgraph"

            [["0.96.1+0".artifact_metadata.metadata.sources]]
            hash = "4c0fd7022b227a58c07558d487f717374884dc32"
            type = "git"
            unpack_target = ""
            url = "https://github.com/JuliaPOMDP/sarsop.git"
