["4.6.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.aarch64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.i686-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.powerpc64le-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2024-08-17T20:40:19.000Z

    [["4.6.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.aarch64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.i686-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.powerpc64le-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/systemtap_jll.jl/releases/download/systemtap-v4.6.0+0/systemtap.v4.6.0.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/05e797213572a1ac3897acdfdbf9c3cf71f68bd9/S/systemtap/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.9"

        ["4.6.0+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.6"
        lazy_artifacts = false
        name = "systemtap"
        platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11"]
        script = """apk add gettext\n\ncd ${WORKSPACE}/srcdir/systemtap\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j all\nmake install\n\n"""
        version = "v4.6.0"

            [["4.6.0+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Elfutils_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["stap"]
            type = "exe"
            variable_name = "stap"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["stap-merge"]
            type = "exe"
            variable_name = "stapmerge"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["stap-report"]
            type = "exe"
            variable_name = "stapreport"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["stapbpf"]
            type = "exe"
            variable_name = "stapbpf"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["staprun"]
            type = "exe"
            variable_name = "staprun"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["stapsh"]
            type = "exe"
            variable_name = "stapsh"
            [["4.6.0+0".artifact_metadata.metadata.products]]
            binnames = ["dtrace"]
            type = "exe"
            variable_name = "dtrace"

            [["4.6.0+0".artifact_metadata.metadata.sources]]
            hash = "cbb34b7244ba60cb0904d61dc9167290855106aa"
            type = "git"
            unpack_target = ""
            url = "https://github.com/cdkey/systemtap.git"
