["0.1.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/py_v0.2.0.tar.gz"]
registered = 2022-10-28T07:58:52.000Z

["0.2.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.4.0.tar.gz"]
registered = 2022-11-02T09:48:52.000Z

["0.3.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.4.0.tar.gz"]
registered = 2022-11-06T21:23:02.000Z

["0.3.1"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.4.0.tar.gz"]
registered = 2022-11-07T22:19:14.000Z

["0.3.2"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.4.0.tar.gz"]
registered = 2023-01-31T21:23:46.000Z

["0.4.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.4.0.tar.gz"]
registered = 2023-02-26T22:12:05.000Z

["0.5.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.5.0.tar.gz"]
registered = 2023-10-16T18:37:57.000Z

["0.5.1"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.5.0.tar.gz"]
registered = 2024-02-15T00:25:52.000Z

["0.5.2"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.5.0.tar.gz"]
registered = 2024-12-15T19:40:37.000Z

["0.5.3"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/0.5.0.tar.gz"]
registered = 2024-12-15T22:43:52.000Z

["0.6.0"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/1.0.0.tar.gz"]
registered = 2025-07-25T13:08:40.000Z

["0.6.1"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/1.0.0.tar.gz"]
registered = 2026-07-07T14:42:32.000Z

["0.6.2"]
artifact_urls = ["https://github.com/stan-dev/posteriordb/archive/refs/tags/1.0.0.tar.gz"]
registered = 2026-07-08T15:54:37.000Z
