augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "libbposit"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/libbposit\nmake -j TARGET=\"libbposit.${dlext}\"\ninstall -Dvm 755 \"libbposit.${dlext}\" -t \"${libdir}\"\ninstall_license LICENSE\n"""
version = "v0.1.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libbposit"]
type = "lib"
variable_name = "libbposit"

[[sources]]
hash = "af67e6064b93e3feafb4ce176cbb14b1a84a32ed"
type = "git"
unpack_target = ""
url = "https://github.com/jamesquinlan/libbposit.git"
