["0.1.0"]
artifact_urls = ["https://github.com/newren/git-filter-repo/archive/refs/tags/v2.29.0.tar.gz"]
registered = 2021-05-06T12:48:42.000Z

["0.1.2"]
artifact_urls = ["https://github.com/newren/git-filter-repo/archive/refs/tags/v2.34.0.tar.gz"]
registered = 2023-01-24T19:53:58.000Z
