["2.11.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/GoogleSparseHash_jll.jl/releases/download/GoogleSparseHash-v2.11.1+0/GoogleSparseHash.v2.11.1.any.tar.gz"]
registered = 2022-01-24T22:34:00.000Z
