["1.5.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.x86_64-linux-gnu.tar.gz"]
registered = 2022-05-18T16:41:57.000Z

    [["1.5.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/GPI2_jll.jl/releases/download/GPI2-v1.5.1+0/GPI2.v1.5.1.x86_64-linux-gnu.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/92ef99f64ac1268d44f463386b0a50bf0d70c9d1/G/GPI2/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/g/gpi2/build_tarballs.jl/92ef99f64ac1268d44f463386b0a50bf0d70c9d1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.3"

        [["1.5.1+0".artifact_metadata.sources]]
        hash = "4dac7e9152694d2ec4aefd982a52ecc064a8cb8f2c9eab0425428127c3719e2e"
        type = "archive"
        url = "https://github.com/cc-hpc-itwm/GPI-2/archive/refs/tags/v1.5.1.tar.gz"

            ["1.5.1+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/gpi-2"
            version = "1.5.1"
