["20.3.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2026-05-08T23:27:09.000Z

    [["20.3.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.2+0/grok.v20.3.2.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d415e8a37d766e592f7bf668b80367f9c15aa6ff/G/grok/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/g/grok/build_tarballs.jl/d415e8a37d766e592f7bf668b80367f9c15aa6ff.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["20.3.2+0".artifact_metadata.sources]]
        hash = "e51302338564648bcd966429bb5bea9d48e3a3958820df77bf691f7d678aa810"
        type = "archive"
        url = "https://github.com/GrokImageCompression/grok/releases/download/v20.3.2/source-full.tar.gz"

            ["20.3.2+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/grokj2k"
            version = "20.3.2"
        [["20.3.2+0".artifact_metadata.sources]]
        type = "directory"
        url = "https://github.com/JuliaPackaging/Yggdrasil/tree/d415e8a37d766e592f7bf668b80367f9c15aa6ff/G/grok/bundled"

["20.3.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2026-06-05T16:06:33.000Z

    [["20.3.3+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/97bba24dd0255171d36a3b23abb00add7def17c7/G/grok/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/g/grok/build_tarballs.jl/97bba24dd0255171d36a3b23abb00add7def17c7.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["20.3.3+0".artifact_metadata.sources]]
        hash = "2b588f23202e306e0242dd5b2c8b99648bded44f118a31e57ed5dcee75cbc549"
        type = "archive"
        url = "https://github.com/GrokImageCompression/grok/releases/download/v20.3.3/source-full.tar.gz"

            ["20.3.3+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/grokj2k"
            version = "20.3.3"

["20.3.7+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.x86_64-linux-gnu-cxx11.tar.gz"]
registered = 2026-07-22T19:24:25.000Z

    [["20.3.7+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.aarch64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.i686-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.powerpc64le-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.x86_64-linux-gnu-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/1884df737083707d2a618e4de9bbab4d8f809f7f/G/grok/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/g/grok/build_tarballs.jl/1884df737083707d2a618e4de9bbab4d8f809f7f.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["20.3.7+0".artifact_metadata.sources]]
        hash = "f2a94f903175296104996dd0fc42504761174d6f2ec8cfdac89fed1aa5f5c337"
        type = "archive"
        url = "https://github.com/GrokImageCompression/grok/releases/download/v20.3.7/source-full.tar.gz"

            ["20.3.7+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/grokj2k"
            version = "20.3.7"
