buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/415ead0b551a6b8e2ce92693c3747203a2f1968f/G/GMP/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.2.4"

[metadata]
dependencies = []
lazy_artifacts = false
name = "GMP"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin14-cxx03", "x86_64-apple-darwin14-cxx11", "x86_64-unknown-freebsd11.1-cxx03", "x86_64-unknown-freebsd11.1-cxx11", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/gmp-*\n\n# Include Julia-carried patches\natomic_patch -p1 ${WORKSPACE}/srcdir/patches/gmp_alloc_overflow_func.patch\n\nflags=(--enable-cxx --enable-shared --disable-static)\n\n# On x86_64 architectures, build fat binary\nif [[ ${proc_family} == intel ]]; then\n    flags+=(--enable-fat)\nfi\n\n./configure --prefix=$prefix --build=${MACHTYPE} --host=${target} ${flags[@]}\n\nmake -j${nproc}\nmake install\n\n# On Windows, we need to make sure that the non-versioned dll names exist too\nif [[ ${target} == *mingw* ]]; then\n    cp -v ${libdir}/libgmp-*.dll \"${libdir}/libgmp.dll\"\n    cp -v ${libdir}/libgmpxx-*.dll \"${libdir}/libgmpxx.dll\"\nfi\n\n# GMP is dual-licensed, install all license files\ninstall_license COPYING*\n"""
version = "v6.2.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgmp"]
    type = "lib"
    variable_name = "libgmp"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgmpxx"]
    type = "lib"
    variable_name = "libgmpxx"

    [[metadata.sources]]
    hash = "f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea"
    type = "archive"
    unpack_target = ""
    url = "https://gmplib.org/download/gmp/gmp-6.2.0.tar.bz2"
    [[metadata.sources]]
    path = "./bundled"
    target = ""
    type = "directory"
