buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f7eb91e8d9bafb8d00b0c3e30b9dd60e291bfead/D/Dex/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.1"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Dex"
platforms = ["x86_64-linux-musl", "x86_64-linux-gnu"]
script = """cd $WORKSPACE/srcdir\nmkdir -p \"${bindir}\" \"${prefix}/share\"\ncd dex/\nfor f in ${WORKSPACE}/srcdir/patches/*.patch; do\n    atomic_patch -p1 ${f}\ndone\ninstall_license LICENSE \nmake\nmkdir -p $bindir\nmv bin/dex \"$bindir/dex${exeext}\"\ntar -czvf $prefix/share/webtemplates.tar.gz -C ./web static templates themes\n"""
version = "v2.28.1"

    [[metadata.products]]
    binnames = ["dex"]
    type = "exe"
    variable_name = "dex"
    [[metadata.products]]
    paths = ["share/webtemplates.tar.gz"]
    type = "file"
    variable_name = "webtemplates"

    [[metadata.sources]]
    hash = "510ee05334923aab2bb598f97c7a6d8eb53d53c6"
    type = "git"
    unpack_target = ""
    url = "https://github.com/dexidp/dex.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "bundled"
    target = ""
    type = "directory"
