buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/11d76c84c42b5c905b7d6e0bece2a89a9d63911e/S/SDL12_compat/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.6"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SDL12_compat"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\ncd sdl12-compat/\nmkdir build\ncd build/\ncmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DSDL12TESTS=OFF -DSDL12DEVEL=ON ..\nmake -j${nproc}\nmake install\n"""
version = "v1.2.60"

    [[metadata.dependencies]]
    compat = ""
    name = "SDL2_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "ab825dc5-c88e-5901-9575-1e5e20358fcf"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_xorgproto_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    top_level = false
    type = "builddependency"
    uuid = "c4d99508-4286-5418-9131-c86396af500b"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["SDL", "libSDL"]
    type = "lib"
    variable_name = "libSDL"

    [[metadata.sources]]
    hash = "43887001c05c64eb23eb5312c0f62e9841618700"
    type = "git"
    unpack_target = ""
    url = "https://github.com/libsdl-org/sdl12-compat.git"
