augment_platform_block = ""
init_block = ""
julia_compat = "1.9"
lazy_artifacts = false
name = "CImGuiPack"
platforms = ["i686-linux-gnu-cxx03-julia_version+1.9.0", "i686-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-gnu-cxx03-julia_version+1.9.0", "x86_64-linux-gnu-cxx11-julia_version+1.9.0", "aarch64-linux-gnu-cxx03-julia_version+1.9.0", "aarch64-linux-gnu-cxx11-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-musl-cxx03-julia_version+1.9.0", "x86_64-linux-musl-cxx11-julia_version+1.9.0", "aarch64-linux-musl-cxx03-julia_version+1.9.0", "aarch64-linux-musl-cxx11-julia_version+1.9.0", "x86_64-apple-darwin-julia_version+1.9.0", "aarch64-apple-darwin-julia_version+1.9.0", "x86_64-unknown-freebsd-julia_version+1.9.0", "i686-w64-mingw32-cxx03-julia_version+1.9.0", "i686-w64-mingw32-cxx11-julia_version+1.9.0", "x86_64-w64-mingw32-cxx03-julia_version+1.9.0", "x86_64-w64-mingw32-cxx11-julia_version+1.9.0", "i686-linux-gnu-cxx03-julia_version+1.10.0", "i686-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-gnu-cxx03-julia_version+1.10.0", "x86_64-linux-gnu-cxx11-julia_version+1.10.0", "aarch64-linux-gnu-cxx03-julia_version+1.10.0", "aarch64-linux-gnu-cxx11-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-musl-cxx03-julia_version+1.10.0", "x86_64-linux-musl-cxx11-julia_version+1.10.0", "aarch64-linux-musl-cxx03-julia_version+1.10.0", "aarch64-linux-musl-cxx11-julia_version+1.10.0", "x86_64-apple-darwin-julia_version+1.10.0", "aarch64-apple-darwin-julia_version+1.10.0", "x86_64-unknown-freebsd-julia_version+1.10.0", "i686-w64-mingw32-cxx03-julia_version+1.10.0", "i686-w64-mingw32-cxx11-julia_version+1.10.0", "x86_64-w64-mingw32-cxx03-julia_version+1.10.0", "x86_64-w64-mingw32-cxx11-julia_version+1.10.0", "i686-linux-gnu-cxx03-julia_version+1.11.1", "i686-linux-gnu-cxx11-julia_version+1.11.1", "x86_64-linux-gnu-cxx03-julia_version+1.11.1", "x86_64-linux-gnu-cxx11-julia_version+1.11.1", "aarch64-linux-gnu-cxx03-julia_version+1.11.1", "aarch64-linux-gnu-cxx11-julia_version+1.11.1", "powerpc64le-linux-gnu-cxx03-julia_version+1.11.1", "powerpc64le-linux-gnu-cxx11-julia_version+1.11.1", "x86_64-linux-musl-cxx03-julia_version+1.11.1", "x86_64-linux-musl-cxx11-julia_version+1.11.1", "aarch64-linux-musl-cxx03-julia_version+1.11.1", "aarch64-linux-musl-cxx11-julia_version+1.11.1", "x86_64-apple-darwin-julia_version+1.11.1", "aarch64-apple-darwin-julia_version+1.11.1", "x86_64-unknown-freebsd-julia_version+1.11.1", "i686-w64-mingw32-cxx03-julia_version+1.11.1", "i686-w64-mingw32-cxx11-julia_version+1.11.1", "x86_64-w64-mingw32-cxx03-julia_version+1.11.1", "x86_64-w64-mingw32-cxx11-julia_version+1.11.1", "i686-linux-gnu-cxx03-julia_version+1.12.0", "i686-linux-gnu-cxx11-julia_version+1.12.0", "x86_64-linux-gnu-cxx03-julia_version+1.12.0", "x86_64-linux-gnu-cxx11-julia_version+1.12.0", "aarch64-linux-gnu-cxx03-julia_version+1.12.0", "aarch64-linux-gnu-cxx11-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.12.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.12.0", "x86_64-linux-musl-cxx03-julia_version+1.12.0", "x86_64-linux-musl-cxx11-julia_version+1.12.0", "aarch64-linux-musl-cxx03-julia_version+1.12.0", "aarch64-linux-musl-cxx11-julia_version+1.12.0", "x86_64-apple-darwin-julia_version+1.12.0", "aarch64-apple-darwin-julia_version+1.12.0", "x86_64-unknown-freebsd-julia_version+1.12.0", "i686-w64-mingw32-cxx03-julia_version+1.12.0", "i686-w64-mingw32-cxx11-julia_version+1.12.0", "x86_64-w64-mingw32-cxx03-julia_version+1.12.0", "x86_64-w64-mingw32-cxx11-julia_version+1.12.0", "i686-linux-gnu-cxx03-julia_version+1.13.0", "i686-linux-gnu-cxx11-julia_version+1.13.0", "x86_64-linux-gnu-cxx03-julia_version+1.13.0", "x86_64-linux-gnu-cxx11-julia_version+1.13.0", "aarch64-linux-gnu-cxx03-julia_version+1.13.0", "aarch64-linux-gnu-cxx11-julia_version+1.13.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.13.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.13.0", "x86_64-linux-musl-cxx03-julia_version+1.13.0", "x86_64-linux-musl-cxx11-julia_version+1.13.0", "aarch64-linux-musl-cxx03-julia_version+1.13.0", "aarch64-linux-musl-cxx11-julia_version+1.13.0", "x86_64-apple-darwin-julia_version+1.13.0", "aarch64-apple-darwin-julia_version+1.13.0", "x86_64-unknown-freebsd-julia_version+1.13.0", "i686-w64-mingw32-cxx03-julia_version+1.13.0", "i686-w64-mingw32-cxx11-julia_version+1.13.0", "x86_64-w64-mingw32-cxx03-julia_version+1.13.0", "x86_64-w64-mingw32-cxx11-julia_version+1.13.0"]
script = """cd $WORKSPACE/srcdir/cimgui-pack\ngit submodule update --init --recursive --depth 1\ncp test_engine/overrides.h test_engine/src/overrides.h\n\nmkdir build && cd build\nexport VERBOSE=1\ncmake .. -DCMAKE_INSTALL_PREFIX=${prefix} \\\n         -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n         -DJulia_PREFIX=${prefix} \\\n         -DCMAKE_BUILD_TYPE=Release\nmake -j${nproc}\nmake install\ninstall_license ../cimgui/LICENSE ../cimgui/imgui/LICENSE.txt ../cimplot/LICENSE ../cimplot/implot/LICENSE ../cimnodes/imnodes/LICENSE.md\n\n# Copy generator files for cimgui\ninstall -Dvm 644 ../cimgui_comments_output/*.json -t ${prefix}/share/cimgui\n\n# And cimplot\ninstall -Dvm 644 ../cimplot/generator/output/*.json -t ${prefix}/share/cimplot\n\n# And cimnodes\ninstall -Dvm 644 ../cimnodes/generator/output/*.json -t ${prefix}/share/cimnodes\n"""
version = "v0.8.0"

[[dependencies]]
compat = ""
name = "libjulia_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 1
version-minor = 10
version-patch = 15
[[dependencies]]
compat = ""
name = "GLFW_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "0.13.4"
name = "libcxxwrap_julia_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcimgui"]
type = "lib"
variable_name = "libcimgui"
[[products]]
paths = ["share/compile_commands.json"]
type = "file"
variable_name = "compile_commands"
[[products]]
paths = ["share/cimgui/definitions.json"]
type = "file"
variable_name = "cimgui_definitions"
[[products]]
paths = ["share/cimgui/impl_definitions.json"]
type = "file"
variable_name = "cimgui_impl_definitions"
[[products]]
paths = ["share/cimgui/structs_and_enums.json"]
type = "file"
variable_name = "cimgui_structs_and_enums"
[[products]]
paths = ["share/cimgui/typedefs_dict.json"]
type = "file"
variable_name = "cimgui_typedefs_dict"
[[products]]
paths = ["share/cimplot/definitions.json"]
type = "file"
variable_name = "cimplot_definitions"
[[products]]
paths = ["share/cimplot/structs_and_enums.json"]
type = "file"
variable_name = "cimplot_structs_and_enums"
[[products]]
paths = ["share/cimplot/typedefs_dict.json"]
type = "file"
variable_name = "cimplot_typedefs_dict"
[[products]]
paths = ["share/cimnodes/definitions.json"]
type = "file"
variable_name = "cimnodes_definitions"
[[products]]
paths = ["share/cimnodes/structs_and_enums.json"]
type = "file"
variable_name = "cimnodes_structs_and_enums"
[[products]]
paths = ["share/cimnodes/typedefs_dict.json"]
type = "file"
variable_name = "cimnodes_typedefs_dict"

[[sources]]
hash = "c715ad63e3aa8d642743750d905ab9cfef747790"
type = "git"
unpack_target = ""
url = "https://github.com/JuliaImGui/cimgui-pack.git"
