augment_platform_block = """    using Base.BinaryPlatforms\n    # Can't use Preferences since we might be running this very early with a non-existing Manifest\nMPIPreferences_UUID = Base.UUID(\"3da0fdf6-3ccc-4f1b-acd9-58baa6c99267\")\nconst preferences = Base.get_preferences(MPIPreferences_UUID)\n\n# Keep logic in sync with MPIPreferences.jl\nfunction augment_mpi!(platform)\n    # Doesn't need to be `const` since we depend on MPIPreferences so we\n    # invalidate the cache when it changes.\n    binary = get(preferences, \"binary\", Sys.iswindows() ? \"MicrosoftMPI_jll\" : \"MPICH_jll\")\n\n    abi = if binary == \"system\"\n        let abi = get(preferences, \"abi\", nothing)\n            if abi === nothing\n                error(\"MPIPreferences: Inconsistent state detected, binary set to system, but no ABI set.\")\n            else\n                abi\n            end\n        end\n    elseif binary == \"MicrosoftMPI_jll\"\n        \"MicrosoftMPI\"\n    elseif binary == \"MPICH_jll\"\n        \"MPICH\"\n    elseif binary == \"OpenMPI_jll\"\n        \"OpenMPI\"\n    elseif binary == \"MPItrampoline_jll\"\n        \"MPItrampoline\"\n    else\n        error(\"Unknown binary: $binary\")\n    end\n\n    if !haskey(platform, \"mpi\")\n        platform[\"mpi\"] = abi\n    end\n    return platform\nend\n\n    augment_platform!(platform::Platform) = augment_mpi!(platform)\n"""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = true
name = "SuperLU_DIST"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich", "i686-linux-gnu-mpi+openmpi", "x86_64-linux-gnu-mpi+openmpi", "aarch64-linux-gnu-mpi+openmpi", "armv7l-linux-gnueabihf-mpi+openmpi", "powerpc64le-linux-gnu-mpi+openmpi", "i686-linux-musl-mpi+openmpi", "x86_64-linux-musl-mpi+openmpi", "aarch64-linux-musl-mpi+openmpi", "armv6l-linux-musleabihf-mpi+openmpi", "armv7l-linux-musleabihf-mpi+openmpi", "x86_64-apple-darwin-mpi+openmpi", "aarch64-apple-darwin-mpi+openmpi", "x86_64-unknown-freebsd-mpi+openmpi", "i686-w64-mingw32-mpi+microsoftmpi", "x86_64-w64-mingw32-mpi+microsoftmpi", "i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline"]
script = """cd $WORKSPACE/srcdir/superlu_dist*\n# allow us to set the name of the shared lib.\nsed -i -e 's!OUTPUT_NAME superlu_dist!OUTPUT_NAME \"${SUPERLU_OUTPUT_NAME}\"!g' SRC/CMakeLists.txt\n\nif [[ \"${target}\" == *-mingw* ]]; then\n    # This is required to ensure that MSMPI can be found by cmake\n    export LDFLAGS=\"-L${libdir} -lmsmpi\"\n    PLATFLAGS=\"-DTPL_ENABLE_PARMETISLIB:BOOL=FALSE -DMPI_C_ADDITIONAL_INCLUDE_DIRS=${includedir}\"\nfi\n\nBLAS=\"libopenblas\"\n\nbuild_superlu_dist()\n{\n    if [[ \"${1}\" == \"Int64\" ]]; then\n        INT=64\n        METIS_PATH=\"${libdir}/metis/metis_Int64_Real32/lib/libmetis_Int64_Real32.${dlext}\"\n        PARMETIS_PATH=\"${libdir}/libparmetis_Int64_Real32.${dlext}\"\n    else\n        INT=32\n        METIS_PATH=\"${libdir}/libmetis.${dlext}\"\n        PARMETIS_PATH=\"${libdir}/libparmetis.${dlext}\"\n    fi\n    if [[ \"${target}\" != *-mingw* ]]; then\n        PLATFLAGS=\"-DTPL_ENABLE_PARMETISLIB:BOOL=TRUE -DTPL_PARMETIS_INCLUDE_DIRS=${includedir} -DTPL_PARMETIS_LIBRARIES=${PARMETIS_PATH};${METIS_PATH}\"\n    fi\n\n    mkdir build-${INT}\n    pushd build-${INT}\n    cmake \\\n        -DCMAKE_INSTALL_PREFIX=${prefix} \\\n        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n        -DCMAKE_BUILD_TYPE=Release \\\n        -DBUILD_SHARED_LIBS=ON \\\n        -DBUILD_STATIC_LIBS=OFF \\\n        -DTPL_ENABLE_INTERNAL_BLASLIB=OFF \\\n        -Denable_tests=OFF \\\n        -Denable_doc=OFF \\\n        -Denable_single=ON \\\n        -Denable_double=ON \\\n        -Denable_complex16=ON \\\n        -DTPL_BLAS_LIBRARIES=\"${libdir}/${BLAS}.${dlext}\" \\\n        ${PLATFLAGS} \\\n        -DCMAKE_C_FLAGS=\"-std=c99\" \\\n        -DXSDK_INDEX_SIZE=${INT} \\\n        -DXSDK_ENABLE_Fortran=OFF \\\n        -DSUPERLU_OUTPUT_NAME=\"superlu_dist_Int${INT}\" \\\n        -Denable_examples=OFF \\\n        ..\n    make -j${nproc}\n    make install\n    popd\n}\nbuild_superlu_dist Int32\nbuild_superlu_dist Int64\n"""
version = "v8.1.2"

[[dependencies]]
compat = ""
name = "OpenBLAS32_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "656ef2d0-ae68-5445-9ca0-591084a874a2"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "4.0.6"
name = "PARMETIS_jll"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich", "i686-linux-gnu-mpi+openmpi", "x86_64-linux-gnu-mpi+openmpi", "aarch64-linux-gnu-mpi+openmpi", "armv7l-linux-gnueabihf-mpi+openmpi", "powerpc64le-linux-gnu-mpi+openmpi", "i686-linux-musl-mpi+openmpi", "x86_64-linux-musl-mpi+openmpi", "aarch64-linux-musl-mpi+openmpi", "armv6l-linux-musleabihf-mpi+openmpi", "armv7l-linux-musleabihf-mpi+openmpi", "x86_64-apple-darwin-mpi+openmpi", "aarch64-apple-darwin-mpi+openmpi", "x86_64-unknown-freebsd-mpi+openmpi", "i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline"]
top_level = false
type = "dependency"
uuid = "b247a4be-ddc1-5759-8008-7e02fe3dbdaa"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "METIS_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "i686-linux-gnu-mpi+openmpi", "x86_64-linux-gnu-mpi+openmpi", "aarch64-linux-gnu-mpi+openmpi", "armv7l-linux-gnueabihf-mpi+openmpi", "powerpc64le-linux-gnu-mpi+openmpi", "i686-linux-musl-mpi+openmpi", "x86_64-linux-musl-mpi+openmpi", "aarch64-linux-musl-mpi+openmpi", "armv6l-linux-musleabihf-mpi+openmpi", "armv7l-linux-musleabihf-mpi+openmpi", "i686-w64-mingw32-mpi+microsoftmpi", "x86_64-w64-mingw32-mpi+microsoftmpi", "i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LLVMOpenMP_jll"
platforms = ["x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich", "x86_64-apple-darwin-mpi+openmpi", "aarch64-apple-darwin-mpi+openmpi", "x86_64-unknown-freebsd-mpi+openmpi", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline"]
top_level = false
type = "dependency"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MPICH_jll"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenMPI_jll"
platforms = ["i686-linux-gnu-mpi+openmpi", "x86_64-linux-gnu-mpi+openmpi", "aarch64-linux-gnu-mpi+openmpi", "armv6l-linux-gnueabihf-mpi+openmpi", "armv7l-linux-gnueabihf-mpi+openmpi", "powerpc64le-linux-gnu-mpi+openmpi", "i686-linux-musl-mpi+openmpi", "x86_64-linux-musl-mpi+openmpi", "aarch64-linux-musl-mpi+openmpi", "armv6l-linux-musleabihf-mpi+openmpi", "armv7l-linux-musleabihf-mpi+openmpi", "x86_64-apple-darwin-mpi+openmpi", "aarch64-apple-darwin-mpi+openmpi", "x86_64-unknown-freebsd-mpi+openmpi"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MicrosoftMPI_jll"
platforms = ["i686-w64-mingw32-mpi+microsoftmpi", "x86_64-w64-mingw32-mpi+microsoftmpi"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "5.2.1"
name = "MPItrampoline_jll"
platforms = ["i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline", "i686-linux-musl-mpi+mpitrampoline", "x86_64-linux-musl-mpi+mpitrampoline", "aarch64-linux-musl-mpi+mpitrampoline", "armv6l-linux-musleabihf-mpi+mpitrampoline", "armv7l-linux-musleabihf-mpi+mpitrampoline", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline", "x86_64-unknown-freebsd-mpi+mpitrampoline"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "0.1"
name = "MPIPreferences"
platforms = ["any"]
top_level = true
type = "dependency"
uuid = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = ["$libdir/superlu_dist/Int32/lib", "$libdir/superlu_dist/Int32/bin"]
dlopen_flags = []
dont_dlopen = false
libnames = ["libsuperlu_dist_Int32"]
type = "lib"
variable_name = "libsuperlu_dist_Int32"
[[products]]
dir_paths = ["$libdir/superlu_dist/Int64/lib", "$libdir/superlu_dist/Int64/bin"]
dlopen_flags = []
dont_dlopen = false
libnames = ["libsuperlu_dist_Int64"]
type = "lib"
variable_name = "libsuperlu_dist_Int64"

[[sources]]
hash = "58e4171dda309255b3b66b0923cd04124f4c0c01"
type = "git"
unpack_target = ""
url = "https://github.com/xiaoyeli/superlu_dist.git"
