augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LinearPartition"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/LinearPartition-*/\n\nmake -j${nproc} CC=${CXX}\nmkdir -p ${bindir}\nfor prg in linearpartition_{c,v}; do\n    install -Dvm 755 \"bin/${prg}\" \"${bindir}/${prg}${exeext}\"\ndone\n\ninstall_license LICENSE\n"""
version = "v1.0.0"

[[products]]
binnames = ["linearpartition_c"]
type = "exe"
variable_name = "linearpartition_c"
[[products]]
binnames = ["linearpartition_v"]
type = "exe"
variable_name = "linearpartition_v"

[[sources]]
hash = "4fdea96f7ffbd4804d9308ddb46db5f96d1abc4b7bd737725f9bedcae3c88178"
type = "archive"
unpack_target = ""
url = "https://github.com/LinearFold/LinearPartition/archive/refs/tags/v1.0.tar.gz"
