augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "Singular"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd [Ss]ingular*\n\n#for f in ${WORKSPACE}/srcdir/patches/*.patch; do\n#    atomic_patch -p1 ${f}\n#done\n\n./autogen.sh\nexport CPPFLAGS=\"-I${prefix}/include\"\n\n# lld doesn't support -r and -keep_private_externs which the Singular build uses\n# switch back to ld on macos to avoid errors:\nif [[ \"${target}\" == *apple* ]]; then\n  export LDFLAGS=\"-fuse-ld=ld\"\nfi\n\n./configure --prefix=$prefix --host=$target --build=${MACHTYPE} \\\n    --with-libparse \\\n    --enable-shared \\\n    --disable-static \\\n    --enable-p-procs-static \\\n    --disable-p-procs-dynamic \\\n    --enable-gfanlib \\\n    --with-readline=no \\\n    --with-gmp=$prefix \\\n    --with-flint=$prefix \\\n    --without-python \\\n    --with-builtinmodules=gfanlib,syzextra,customstd,interval,subsets,loctriv,gitfan,freealgebra \\\n    --disable-partialgb-module \\\n    --disable-polymake-module \\\n    --disable-pyobject-module \\\n    --disable-singmathic-module \\\n    --disable-systhreads-module \\\n    --disable-cohomo-module \\\n    --disable-machinelearning-module \\\n    --disable-sispasm-module\n\nmake -j${nproc}\nmake install\n"""
version = "v404.101.500"

[[dependencies]]
compat = ""
name = "cddlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "~301.300.101"
name = "FLINT_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "GMP_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MPFR_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpolys"]
type = "lib"
variable_name = "libpolys"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libSingular"]
type = "lib"
variable_name = "libsingular"
[[products]]
binnames = ["Singular"]
type = "exe"
variable_name = "Singular"
[[products]]
binnames = ["libparse"]
type = "exe"
variable_name = "libparse"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libfactory"]
type = "lib"
variable_name = "libfactory"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libsingular_resources"]
type = "lib"
variable_name = "libsingular_resources"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libomalloc"]
type = "lib"
variable_name = "libomalloc"

[[sources]]
hash = "7ab5247be80f25ae5ab5a4f4dae59fdd4d4e4782"
type = "git"
unpack_target = ""
url = "https://github.com/Singular/Singular.git"
