buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/81ed428a51522314d1297f61698373a40d11e13e/W/WaveFD/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.6"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "WaveFD"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/WaveFD.jl/src\n\nCXXFLAGS=\"-funroll-loops\"\nif [[ \"${target}\" == i686-linux-gnu || \"${target}\" == x86_64-linux-gnu || \"${target}\" == powerpc6rle-linux-gnu ]]; then\n    CXXFLAGS+=\" -D__FUNCTION_CLONES__\"\nfi\n\necho \"target=$target, CXXFLAGS=$CXXFLAGS\"\n\ncmake . -DCMAKE_CXX_FLAGS=\"${CXXFLAGS}\" -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release\nmake -j${nproc} VERBOSE=1\nmake install\n"""
version = "v0.6.1"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "i686-w64-mingw32", "x86_64-w64-mingw32"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "LLVMOpenMP_jll"
    platforms = ["x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
    top_level = false
    type = "dependency"
    uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "FFTW_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop2DAcoIsoDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop2DAcoIsoDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop2DAcoVTIDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop2DAcoVTIDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop2DAcoTTIDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop2DAcoTTIDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop3DAcoIsoDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop3DAcoIsoDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop3DAcoVTIDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop3DAcoVTIDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libprop3DAcoTTIDenQ_DEO2_FDTD"]
    type = "lib"
    variable_name = "libprop3DAcoTTIDenQ_DEO2_FDTD"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libillumination"]
    type = "lib"
    variable_name = "libillumination"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libspacetime"]
    type = "lib"
    variable_name = "libspacetime"

    [[metadata.sources]]
    hash = "b74720842f1f2fb7e836a8f2762aa78fd2ed1ce8"
    type = "git"
    unpack_target = ""
    url = "https://github.com/ChevronETC/WaveFD.jl.git"
