dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "UBPF"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
script = """cd ${WORKSPACE}/srcdir/ubpf/vm\nif [[ \"${target}\" == *mingw* ]]; then\nsed -i 's/-fPIC//g' Makefile\nelif [[ \"${target}\" == *bsd* ]]; then\nsed -i 's#endian.h#sys/endian.h#g' *.c *.h\nfi\nmake -j $(nproc)\nmake PREFIX=${prefix} install\ncd ..\ninstall_license LICENSE-APACHE\n"""
version = "v0.0.1"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libubpf"]
type = "lib"
variable_name = "libubpf"

[[sources]]
hash = "173a58790af1fdefc67aea6e22aaec0d6d8b4d67"
type = "git"
unpack_target = ""
url = "https://github.com/jpsamaroo/ubpf.git"
