dependencies = []
init_block = ""
lazy_artifacts = false
name = "tree_sitter_cpp"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin14-cxx03", "x86_64-apple-darwin14-cxx11", "x86_64-unknown-freebsd11.1-cxx03", "x86_64-unknown-freebsd11.1-cxx11", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir\nmv tree-sitter-* tree-sitter\n\nBUILD_FLAGS=(-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN})\nmkdir build && cd build\ncmake .. \"${BUILD_FLAGS[@]}\"\nmake -j${nproc}\nmake install\n\ncd ..\nif [ -d tree-sitter/queries ]; then\n   cp -r tree-sitter/queries $WORKSPACE/destdir/\nfi\nif [ -f tree-sitter/LICENSE ]; then\n    install_license tree-sitter/LICENSE\nfi\n"""
version = "v0.16.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtreesitter_cpp"]
type = "lib"
variable_name = "libtreesitter_cpp"

[[sources]]
hash = "1a744ee94e9c3bcfa9c639d49ab1d4b60ebea9474d88aafa5955cbab0afe4ca6"
type = "archive"
unpack_target = ""
url = "https://github.com/tree-sitter/tree-sitter-cpp/archive/v0.16.0.tar.gz"
[[sources]]
path = "./bundled"
target = ""
type = "directory"
