init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "MPSolve"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/MPSolve/\nexport CPPFLAGS=\"-I${prefix}/include\"\n./autogen.sh \n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\ncd src/libmps/\nmake\nmake install\nexit\n"""
version = "v3.2.1"

[[dependencies]]
name = "GMP_jll"
type = "dependency"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmps"]
type = "lib"
variable_name = "libmps"

[[sources]]
hash = "65be6767119a3df911943d7aaacdad4646fa6173"
type = "git"
unpack_target = ""
url = "https://github.com/robol/MPSolve.git"
