augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FreeType2"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/freetype-*\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-shared --disable-static\nmake -j${nproc}\nmake install\ninstall_license docs/{FTL,GPLv2}.TXT\n"""
version = "v2.14.3"

[[dependencies]]
compat = "1.0.9"
name = "Bzip2_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "1.2.12"
name = "Zlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libfreetype"]
type = "lib"
variable_name = "libfreetype"

[[sources]]
hash = "36bc4f1cc413335368ee656c42afca65c5a3987e8768cc28cf11ba775e785a5f"
type = "archive"
unpack_target = ""
url = "https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.xz"
