dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "bottom"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/bottom*/\ncargo build --release\ninstall -Dvm 755 \"target/${rust_target}/release/btm${exeext}\" \"${bindir}/btm${exeext}\"\n"""
version = "v0.6.8"

[[products]]
binnames = ["btm"]
type = "exe"
variable_name = "btm"

[[sources]]
hash = "4e4eb251972a7af8c46dd36bcf1335fea334fb670569434fbfd594208905b2d9"
type = "archive"
unpack_target = ""
url = "https://github.com/ClementTsang/bottom/archive/refs/tags/0.6.8.tar.gz"
