init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "SCS"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/scs*\nflags=\"DLONG=1 USE_OPENMP=0\"\nblasldflags=\"-L${prefix}/lib\"\n# see https://github.com/JuliaPackaging/Yggdrasil/blob/0bc1abd56fa176e3d2cc2e48e7bf85a26c948c40/OpenBLAS/build_tarballs.jl#L23\nif [[ ${nbits} == 64 ]] && [[ ${target} != aarch64* ]]; then\n    flags=\"${flags} BLAS64=1 BLASSUFFIX=_64_\"\n    blasldflags+=\" -lopenblas64_\"\nelse\n    blasldflags+=\" -lopenblas\"\nfi\n\nmake BLASLDFLAGS=\"${blasldflags}\" ${flags} out/libscsdir.${dlext}\nmake BLASLDFLAGS=\"${blasldflags}\" ${flags} out/libscsindir.${dlext}\n\nmkdir -p ${libdir}\ncp out/libscs*.${dlext} ${libdir}\n"""
version = "v2.1.4"

[[dependencies]]
compat = "<0.3.13"
name = "OpenBLAS_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libscsindir"]
type = "lib"
variable_name = "libscsindir"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libscsdir"]
type = "lib"
variable_name = "libscsdir"

[[sources]]
hash = "a70a42c8c740ee756f787760ed59a8a41531e891"
type = "git"
unpack_target = ""
url = "https://github.com/cvxgrp/scs.git"
