["1.0.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Madagascar_jll.jl/releases/download/Madagascar-v1.0.0+0/Madagascar.v1.0.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Madagascar_jll.jl/releases/download/Madagascar-v1.0.0+0/Madagascar.v1.0.0.x86_64-linux-gnu.tar.gz"]
registered = 2023-04-25T13:52:29.000Z
