["2.4.4+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-w64-mingw32-cxx11.tar.gz"]
registered = 2021-01-06T22:53:07.000Z

    [["2.4.4+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+0/MathGL.v2.4.4.x86_64-w64-mingw32-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/95108f1b7b23c371138a98f9e198f167b3542467/M/MathGL/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mathgl/build_tarballs.jl/95108f1b7b23c371138a98f9e198f167b3542467.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.0"

        [["2.4.4+0".artifact_metadata.sources]]
        hash = "0e5977196635962903eaff9b2f759e5b89108339b6e71427036c92bfaf3149e9"
        type = "archive"
        url = "https://sourceforge.net/projects/mathgl/files/mathgl/mathgl%202.4.4/mathgl-2.4.4.tar.gz"
        [["2.4.4+0".artifact_metadata.sources]]
        type = "directory"
        url = "https://github.com/JuliaPackaging/Yggdrasil/tree/95108f1b7b23c371138a98f9e198f167b3542467/M/MathGL/bundled"

["2.4.4+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx11.tar.gz"]
registered = 2021-02-23T17:11:14.000Z

    [["2.4.4+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx11.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx03.tar.gz", "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx11.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e58e861ae100e7546aff7963a14ff1eb91275afa/M/MathGL/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mathgl/build_tarballs.jl/e58e861ae100e7546aff7963a14ff1eb91275afa.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.0"

        [["2.4.4+1".artifact_metadata.sources]]
        hash = "0e5977196635962903eaff9b2f759e5b89108339b6e71427036c92bfaf3149e9"
        type = "archive"
        url = "https://sourceforge.net/projects/mathgl/files/mathgl/mathgl%202.4.4/mathgl-2.4.4.tar.gz"
        [["2.4.4+1".artifact_metadata.sources]]
        type = "directory"
        url = "https://github.com/JuliaPackaging/Yggdrasil/tree/e58e861ae100e7546aff7963a14ff1eb91275afa/M/MathGL/bundled"
