["2020.0.0-01-01+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.0.0-01-01+0/MozillaCACerts.v2020.0.0-01-01.any.tar.gz"]
registered = 2020-05-07T17:09:12.000Z

    [["2020.0.0-01-01+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.0.0-01-01+0/MozillaCACerts.v2020.0.0-01-01.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/88f9fef888ddd440dc51c4bfc51ae75c10a02174/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/88f9fef888ddd440dc51c4bfc51ae75c10a02174.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.4"

["2020.0.0-07-22+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.0.0-07-22+1/MozillaCACerts.v2020.0.0-07-22.any.tar.gz"]
registered = 2020-08-06T20:19:42.000Z

    [["2020.0.0-07-22+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.0.0-07-22+1/MozillaCACerts.v2020.0.0-07-22.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/01458ebf6615a229416ec9d01a4f5fc33b90c5b9/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/01458ebf6615a229416ec9d01a4f5fc33b90c5b9.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["2020.7.22+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.7.22+0/MozillaCACerts.v2020.7.22.any.tar.gz"]
registered = 2020-08-06T21:17:21.000Z

    [["2020.7.22+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.7.22+0/MozillaCACerts.v2020.7.22.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/469aaacb3997170b4fa2dbdedbe60da0539ed1be/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/469aaacb3997170b4fa2dbdedbe60da0539ed1be.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["2020.10.14+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.10.14+0/MozillaCACerts.v2020.10.14.any.tar.gz"]
registered = 2020-10-30T00:45:48.000Z

    [["2020.10.14+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.10.14+0/MozillaCACerts.v2020.10.14.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e2a232e65666882debfca3859396fe7acb3f0635/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/e2a232e65666882debfca3859396fe7acb3f0635.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.0"

["2021.1.19+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2021.1.19+0/MozillaCACerts.v2021.1.19.any.tar.gz"]
registered = 2021-04-09T00:10:37.000Z

    [["2021.1.19+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2021.1.19+0/MozillaCACerts.v2021.1.19.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/6ba7c7b7bafab06699a6dde8346c19c03865afbf/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/6ba7c7b7bafab06699a6dde8346c19c03865afbf.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.1"

["2022.2.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.2.1+0/MozillaCACerts.v2022.2.1.any.tar.gz"]
registered = 2022-02-06T22:47:59.000Z

    [["2022.2.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.2.1+0/MozillaCACerts.v2022.2.1.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a72e830c54aec6d79dda68dfdfdb199758e3d42a/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/a72e830c54aec6d79dda68dfdfdb199758e3d42a.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.1"

["2022.3.29+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.3.29+0/MozillaCACerts.v2022.3.29.any.tar.gz"]
registered = 2022-04-01T22:20:07.000Z

    [["2022.3.29+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.3.29+0/MozillaCACerts.v2022.3.29.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/eb299d2562c1f4eb1c57e23b1358a135d160e26c/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/eb299d2562c1f4eb1c57e23b1358a135d160e26c.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.2"

["2022.10.11+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.10.11+0/MozillaCACerts.v2022.10.11.any.tar.gz"]
registered = 2022-10-15T12:59:16.000Z

    [["2022.10.11+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.10.11+0/MozillaCACerts.v2022.10.11.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/7906ede8c96cbf582e558ad92970e8d653b98444/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/7906ede8c96cbf582e558ad92970e8d653b98444.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.5"

["2023.1.10+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.1.10+0/MozillaCACerts.v2023.1.10.any.tar.gz"]
registered = 2023-02-25T14:31:32.000Z

    [["2023.1.10+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.1.10+0/MozillaCACerts.v2023.1.10.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/8d12ba7c6823660dfd90117bdbe124fdb3b5bb8d/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/8d12ba7c6823660dfd90117bdbe124fdb3b5bb8d.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

["2023.8.22+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.8.22+0/MozillaCACerts.v2023.8.22.any.tar.gz"]
registered = 2023-09-17T19:46:17.000Z

    [["2023.8.22+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.8.22+0/MozillaCACerts.v2023.8.22.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ba1bd9d3db58fb0f30b656c3a716a617431fd051/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/ba1bd9d3db58fb0f30b656c3a716a617431fd051.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

["2023.12.12+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.12.12+0/MozillaCACerts.v2023.12.12.any.tar.gz"]
registered = 2024-02-23T12:36:13.000Z

    [["2023.12.12+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.12.12+0/MozillaCACerts.v2023.12.12.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/448967c3ecd35a6b24f88d73b5b5628136a01345/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/448967c3ecd35a6b24f88d73b5b5628136a01345.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.7"

["2024.3.11+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.3.11+0/MozillaCACerts.v2024.3.11.any.tar.gz"]
registered = 2024-03-16T20:54:32.000Z

    [["2024.3.11+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.3.11+0/MozillaCACerts.v2024.3.11.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/9fc32d0b9d9d54dd9ff9b5c03623d62869133828/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/9fc32d0b9d9d54dd9ff9b5c03623d62869133828.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.8"

["2024.7.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.7.2+0/MozillaCACerts.v2024.7.2.any.tar.gz"]
registered = 2024-07-24T17:39:13.000Z

    [["2024.7.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.7.2+0/MozillaCACerts.v2024.7.2.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/beebef2b610a9da961b5aa30cf4342910460fd6c/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/beebef2b610a9da961b5aa30cf4342910460fd6c.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.8"

["2024.11.26+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.11.26+0/MozillaCACerts.v2024.11.26.any.tar.gz"]
registered = 2024-11-27T18:34:36.000Z

    [["2024.11.26+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.11.26+0/MozillaCACerts.v2024.11.26.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/89323317c9bdd6a4c0f5eeb929b4f88ea82acb88/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/89323317c9bdd6a4c0f5eeb929b4f88ea82acb88.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.0"

["2024.12.31+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.12.31+0/MozillaCACerts.v2024.12.31.any.tar.gz"]
registered = 2025-01-13T22:19:27.000Z

    [["2024.12.31+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.12.31+0/MozillaCACerts.v2024.12.31.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a8c201605e09c1b0ab9a051c5bf7ffa3b389a35f/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/a8c201605e09c1b0ab9a051c5bf7ffa3b389a35f.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.3"

["2025.2.25+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.2.25+0/MozillaCACerts.v2025.2.25.any.tar.gz"]
registered = 2025-03-01T17:06:45.000Z

    [["2025.2.25+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.2.25+0/MozillaCACerts.v2025.2.25.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d3c0b805a0874c2f2fea8b1d77deeaf7ce0da97c/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/d3c0b805a0874c2f2fea8b1d77deeaf7ce0da97c.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

["2025.5.20+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.5.20+0/MozillaCACerts.v2025.5.20.any.tar.gz"]
registered = 2025-05-22T03:45:17.000Z

    [["2025.5.20+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.5.20+0/MozillaCACerts.v2025.5.20.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/6a5a38489703bfe1770ad8dac962d141c7e70cdc/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/6a5a38489703bfe1770ad8dac962d141c7e70cdc.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

["2025.7.15+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.7.15+0/MozillaCACerts.v2025.7.15.any.tar.gz"]
registered = 2025-07-15T17:07:13.000Z

    [["2025.7.15+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.7.15+0/MozillaCACerts.v2025.7.15.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/99a2a8c8136b31e679cf37d4c2f40319498ffd6d/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/99a2a8c8136b31e679cf37d4c2f40319498ffd6d.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

["2025.8.12+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.8.12+0/MozillaCACerts.v2025.8.12.any.tar.gz"]
registered = 2025-08-14T14:36:00.000Z

    [["2025.8.12+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.8.12+0/MozillaCACerts.v2025.8.12.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/bf296e7efd741e02a25214ec7cef6446b2dd6e17/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/bf296e7efd741e02a25214ec7cef6446b2dd6e17.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"

["2025.9.9+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.9.9+0/MozillaCACerts.v2025.9.9.any.tar.gz"]
registered = 2025-09-10T15:08:51.000Z

    [["2025.9.9+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.9.9+0/MozillaCACerts.v2025.9.9.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f59f9ab5c33eba36d095d6e7dc72c8037ba48dd7/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/f59f9ab5c33eba36d095d6e7dc72c8037ba48dd7.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"

["2025.11.4+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.11.4+0/MozillaCACerts.v2025.11.4.any.tar.gz"]
registered = 2025-11-04T19:03:28.000Z

    [["2025.11.4+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.11.4+0/MozillaCACerts.v2025.11.4.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/10813b1f0084af3bc58c25e5f59aa6f4933d06c1/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/10813b1f0084af3bc58c25e5f59aa6f4933d06c1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"

["2025.12.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.12.2+0/MozillaCACerts.v2025.12.2.any.tar.gz"]
registered = 2025-12-02T17:15:07.000Z

    [["2025.12.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.12.2+0/MozillaCACerts.v2025.12.2.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/54ed3e77009f825fd519cce8bd630731280bbc00/M/MozillaCACerts/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/m/mozillacacerts/build_tarballs.jl/54ed3e77009f825fd519cce8bd630731280bbc00.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"
