buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e6153c730e77b8d3d595f68ea41382295b5e1a94/E/ECOS/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.0"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "ECOS"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/ecos*\nmake shared\n\nmkdir -p ${libdir}\ncp libecos.${dlext} ${libdir}\ncp -r include ${prefix}\n"""
version = "v2.0.8"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libecos"]
    type = "lib"
    variable_name = "libecos"

    [[metadata.sources]]
    hash = "3b98fe0376ceeeb8310a06694b0a84ac59920f3f"
    type = "git"
    unpack_target = ""
    url = "https://github.com/embotech/ecos.git"
