augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libsvm"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libsvm*/\nfor f in ${WORKSPACE}/srcdir/patches/*.patch; do\n    atomic_patch -p1 ${f}\ndone\nmake \nmake lib\ninstall -Dvm 0755 \"libsvm.${dlext}\" \"${libdir}/libsvm.${dlext}\"\ninstall -Dvm 0755 \"svm-train${exeext}\" \"${bindir}/svm-train${exeext}\"\ninstall -Dvm 0755 \"svm-predict${exeext}\" \"${bindir}/svm-predict${exeext}\"\ninstall -Dvm 0755 \"svm-scale${exeext}\" \"${bindir}/svm-scale${exeext}\"\n"""
version = "v3.25.0"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "i686-w64-mingw32", "x86_64-w64-mingw32"]
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LLVMOpenMP_jll"
platforms = ["x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
type = "dependency"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libsvm"]
type = "lib"
variable_name = "libsvm"
[[products]]
binnames = ["svm-scale"]
type = "exe"
variable_name = "svm_scale"
[[products]]
binnames = ["svm-train"]
type = "exe"
variable_name = "svm_train"
[[products]]
binnames = ["svm-predict"]
type = "exe"
variable_name = "svm_predict"

[[sources]]
hash = "1f587ec0df6fd422dfe50f942f8836ac179b0723b768fe9d2fabdfd1601a0963"
type = "archive"
unpack_target = ""
url = "https://github.com/cjlin1/libsvm/archive/v325.tar.gz"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
