augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "gitoxide"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-unknown-freebsd", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/gitoxide*/\ncargo build --release\ninstall -Dvm 755 \"target/${rust_target}/release/ein${exeext}\" \"${bindir}/ein${exeext}\"\ninstall -Dvm 755 \"target/${rust_target}/release/gix${exeext}\" \"${bindir}/gix${exeext}\"\ninstall_license LICENSE-*\n"""
version = "v0.11.0"

[[products]]
binnames = ["ein"]
type = "exe"
variable_name = "ein"
[[products]]
binnames = ["gix"]
type = "exe"
variable_name = "gix"

[[sources]]
hash = "7e76796d5c2956961bd998286bec05fca1ba8fc4"
type = "git"
unpack_target = ""
url = "https://github.com/Byron/gitoxide"
