buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/95a27aefca1a1e3ba8504c1a5caa3aaf89788bf4/F/FGlT/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.7"

[metadata]
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FGlT"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/fglt/\nmeson --cross-file=${MESON_TARGET_TOOLCHAIN} build\ncd build/\nninja -j${nproc}\nninja install\n"""
version = "v1.0.0"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "cilkrts_jll"
    type = "dependency"
    uuid = "71772805-00bc-5a29-9044-a26d819b7806"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libfglt"]
    type = "lib"
    variable_name = "libfglt"

    [[metadata.sources]]
    hash = "c3c0c683a76fef56473314527760b74ffd271455"
    type = "git"
    unpack_target = ""
    url = "https://github.com/fcdimitr/fglt.git"
