buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/167020f7cdeb87123804ff76d81d4cae4efa312e/S/SoapyRemote/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.4"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SoapyRemote"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx03", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd SoapyRemote\ninstall_license LICENSE_1_0.txt\n\nmkdir build\ncd build\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n      -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n      -DCMAKE_BUILD_TYPE=Release \\\n      ..\nmake -j${nproc}\nmake install\nif [[ \"${target}\" == *-apple-* ]]; then\n    mv ${libdir}/SoapySDR/modules0.8/libremoteSupport.so  ${libdir}/SoapySDR/modules0.8/libremoteSupport.dylib\nfi\n"""
version = "v0.5.2"

    [[metadata.dependencies]]
    compat = "0.8"
    name = "soapysdr_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = ["lib/SoapySDR/modules0.8/"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libremoteSupport"]
    type = "lib"
    variable_name = "libremoteSupport"

    [[metadata.sources]]
    hash = "f920d9bf10f62f67c8e31b7dc25090bc784e5210"
    type = "git"
    unpack_target = ""
    url = "https://github.com/pothosware/SoapyRemote.git"
