buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2d5d72eb6cbdfb99d96496de6573aafc2927fab9/L/libfabric/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.4"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libfabric"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd ${WORKSPACE}/srcdir/libfabric\n\nargs=(--with-dlopen)\nif [[ ${target} == *freebsd* ]]; then\n    # verbs on FreeBSD requires the Linux kernel header files\n    # (Maybe a cross-compiling bug?)\n    args+=(--enable-verbs=no)\nfi\n\n./autogen.sh\n# export CPPFLAGS=-I${prefix}/usr/include\n./configure --build=${MACHTYPE} --host=${target} --prefix=${prefix} ${args[@]}\nmake -j${nproc}\nmake install\n"""
version = "v1.22.0"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libfabric"]
    type = "lib"
    variable_name = "libfabric"

    [[metadata.sources]]
    hash = "159219639b7fd69d140892120121bbb4d694e295"
    type = "git"
    unpack_target = ""
    url = "https://github.com/ofiwg/libfabric"
