["6.8.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+0/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz", "https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+0/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"]
registered = 2025-10-09T22:12:18.000Z

    [["6.8.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+0/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz", "https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+0/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/4fbeefdf53ac0d2e0e78217c5830d2ab55aa44d0/Q/Qt6Tools/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/q/qt6tools/build_tarballs.jl/4fbeefdf53ac0d2e0e78217c5830d2ab55aa44d0.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"

        [["6.8.2+0".artifact_metadata.sources]]
        hash = "326381b7d43f07913612f291abc298ae79bd95382e2233abce982cff2b53d2c0"
        type = "archive"
        url = "https://download.qt.io/official_releases/qt/6.8/6.8.2/submodules/qttools-everywhere-src-6.8.2.tar.xz"
        [["6.8.2+0".artifact_metadata.sources]]
        hash = "3f66bce069ee8bed7439a1a13da7cb91a5e67ea6170f21317ac7f5794625ee10"
        type = "archive"
        url = "https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v11.0.1.tar.bz2"

            ["6.8.2+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/mingw-w64-headers"
            version = "11.0.1"
        [["6.8.2+0".artifact_metadata.sources]]
        hash = "4a31565fd2644d1aec23da3829977f83632a20985561a2038e198681e7e7bf49"
        type = "archive"
        url = "https://github.com/roblabla/MacOSX-SDKs/releases/download/macosx14.0/MacOSX14.0.sdk.tar.xz"
        [["6.8.2+0".artifact_metadata.sources]]
        package = "Vulkan_Headers_jll"
        type = "builddependency"
        [["6.8.2+0".artifact_metadata.sources]]
        package = "LLVM_full_jll"
        type = "builddependency"
        [["6.8.2+0".artifact_metadata.sources]]
        package = "LLVM_full_assert_jll"
        type = "builddependency"
