dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libtree"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/libtree-*/\nmake CFLAGS=\"-Os -fwhole-program\" LDFLAGS=\"-Wl,-s\" \"PREFIX=$prefix\" install\n"""
version = "v3.0.3"

[[products]]
binnames = ["libtree"]
type = "exe"
variable_name = "libtree"

[[sources]]
hash = "7e4589b617775cb3a2b4b8fe03f80b81e43ef16046d680f1517ce52d7be9893f"
type = "archive"
unpack_target = ""
url = "https://github.com/haampie/libtree/archive/refs/tags/v3.0.3.tar.gz"
