augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SCS_MKL"
platforms = ["x86_64-linux-gnu"]
script = """cd $WORKSPACE/srcdir/scs*\nscsflags=\"DLONG=1 USE_OPENMP=1 BLAS32=1 NOBLASSUFFIX=1 USE_SPECTRAL_CONES=1\"\nmklflags=\"-L${prefix}/lib -Wl,--no-as-needed -lmkl_rt -lmkl_core -lpthread -lm -ldl\"\n\nmake ${scsflags} MKLFLAGS=\"${mklflags}\" out/libscsmkl.${dlext}\n\nmkdir -p ${libdir}\ncp out/libscs*.${dlext} ${libdir}\n"""
version = "v300.200.1100"

[[dependencies]]
compat = "=2025.2.0"
name = "MKL_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["x86_64-linux-gnu"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = true
libnames = ["libscsmkl"]
type = "lib"
variable_name = "libscsmkl"

[[sources]]
hash = "e2f2148b6db2055fbdea58ceae28a29b07cc681d"
type = "git"
unpack_target = ""
url = "https://github.com/cvxgrp/scs.git"
