augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Xorg_libXinerama"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/libXinerama-*/\nCPPFLAGS=\"-I${prefix}/include\"\n# When compiling for things like ppc64le, we need newer `config.sub` files\nupdate_configure_scripts\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-malloc0returnsnull=no\nmake -j${nproc}\nmake install\n"""
version = "v1.1.5"

[[dependencies]]
compat = ""
name = "Xorg_xorgproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_util_macros_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libXext_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libXinerama"]
type = "lib"
variable_name = "libXinerama"

[[sources]]
hash = "2efa855cb42dc620eff3b77700d8655695e09aaa318f791f201fa60afa72b95c"
type = "archive"
unpack_target = ""
url = "https://www.x.org/archive/individual/lib/libXinerama-1.1.5.tar.gz"
