buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/5b19263a35a0086295bb391fbd2e312bca9d1891/F/FlexExtract/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.3"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FlexExtract"
platforms = ["i686-linux-gnu-libgfortran3", "i686-linux-gnu-libgfortran4", "i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran3", "aarch64-linux-gnu-libgfortran4", "aarch64-linux-gnu-libgfortran5", "armv6l-linux-gnueabihf-libgfortran3", "armv6l-linux-gnueabihf-libgfortran4", "armv6l-linux-gnueabihf-libgfortran5", "armv7l-linux-gnueabihf-libgfortran3", "armv7l-linux-gnueabihf-libgfortran4", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran3", "powerpc64le-linux-gnu-libgfortran4", "powerpc64le-linux-gnu-libgfortran5"]
script = """cd flex_extract\natomic_patch -p1 /workspace/srcdir/patches/flexextract-makefile.patch\ncd Source/Fortran/\nmake -f makefile_local_gfortran\ncp calc_etadot_fast.out $bindir/calc_etadot\ninstall_license ../../LICENSE.md\n"""
version = "v7.1.2"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "eccodes_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Emoslib_jll"
    platforms = ["any"]
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["calc_etadot"]
    type = "exe"
    variable_name = "calc_etadot"

    [[metadata.sources]]
    hash = "e0005c99ac81d12faa45a8ff799debbd592b0dc0"
    type = "git"
    unpack_target = ""
    url = "https://www.flexpart.eu/gitmob/flex_extract"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
