augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "CLFFT"
platforms = ["x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "aarch64-apple-darwin", "x86_64-apple-darwin"]
script = """cd $WORKSPACE/srcdir\n\ninstall_license ./clFFT/LICENSE\n\npatch ./clFFT/src/CMakeLists.txt 245.patch\n\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -S ./clFFT/src -B ./clFFT/build\ncmake --build ./clFFT/build --target install -j${nproc}\n"""
version = "v2.12.2"

[[dependencies]]
compat = ""
name = "OpenCL_Headers_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 2022
version-minor = 9
version-patch = 23
[[dependencies]]
compat = "2022.09.23"
name = "OpenCL_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "3.3.10"
name = "FFTW_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "=1.76.0"
name = "boost_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libclFFT"]
type = "lib"
variable_name = "libclfft"

[[sources]]
hash = "1e4833f060976971c4df4b54b1b9ad1620aaf1fb"
type = "git"
unpack_target = ""
url = "https://github.com/clMathLibraries/clFFT.git"
[[sources]]
filename = "245.patch"
hash = "b78e80258bd5dd41572dfad8f4c8fe3b0192d7d4f3bdaa85aae2d59f61184a88"
type = "file"
url = "https://patch-diff.githubusercontent.com/raw/clMathLibraries/clFFT/pull/245.patch"
