dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LZO"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/lzo-*/\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-shared --disable-static\nmake -j${nproc}\nmake install\n"""
version = "v2.10.1"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["liblzo2"]
type = "lib"
variable_name = "liblzo2"

[[sources]]
hash = "c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072"
type = "archive"
unpack_target = ""
url = "https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz"
