buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e134d43c80afd1c60268c97ac2e1912944a856c1/L/libsigcpp/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.4.1"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libsigcpp"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "aarch64-apple-darwin", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11"]
script = """cd $WORKSPACE/srcdir/libsigc++*/\nmkdir meson\ncd meson\nmeson --cross-file=${MESON_TARGET_TOOLCHAIN}\nninja -j${nproc}\nninja install\n"""
version = "v3.0.7"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsigc-3.0", "libsigc-3"]
    type = "lib"
    variable_name = "libsigc"

    [[metadata.sources]]
    hash = "bfbe91c0d094ea6bbc6cbd3909b7d98c6561eea8b6d9c0c25add906a6e83d733"
    type = "archive"
    unpack_target = ""
    url = "https://download.gnome.org/sources/libsigc++/3.0/libsigc%2B%2B-3.0.7.tar.xz"
