buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d41c112c7e950bd6f0a45ee0e85a295a984a5376/G/GAP_pkg/GAP_pkg_ace/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "GAP_pkg_ace"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "riscv64-linux-gnu"]
script = """cd ace*\n\n# HACK to workaround need to pass --with-gaproot\nmkdir -p $prefix/lib/gap/ # HACK\necho \"GAParch=dummy\" > $prefix/lib/gap/sysinfo.gap # HACK\necho \"GAP_CPPFLAGS=dummy\" >> $prefix/lib/gap/sysinfo.gap # HACK\n\n./configure ${prefix}/lib/gap\nmake -j${nproc}\n\n# copy just the executable\nmkdir -p ${prefix}/bin/\ncp bin/*/* ${prefix}/bin/\n\ninstall_license LICENSE\n\nrm $prefix/lib/gap/sysinfo.gap\n"""
version = "v501.70000.0"

    [[metadata.products]]
    binnames = ["ace"]
    type = "exe"
    variable_name = "ace"

    [[metadata.sources]]
    hash = "7123e4100f1340a791d20bca1a8d9e6d9f09fe74a1c5fb15f1723899a1bb4553"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/gap-packages/ace/releases/download/v5.7.0/ace-5.7.0.tar.gz"
