buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/1dd1b77d36156fdbc91d42e0ab09cc4ef5cadfce/O/OpenCL_Headers/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.2.4"

[metadata]
dependencies = []
lazy_artifacts = false
name = "OpenCL_Headers"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd OpenCL-Headers-*\ninstall_license LICENSE\n\nmkdir ${prefix}/include\nmv CL ${prefix}/include/\n"""
version = "v2020.3.13"

    [[metadata.products]]
    paths = ["include/CL/cl.h"]
    type = "file"
    variable_name = "cl_h"

    [[metadata.sources]]
    hash = "664bbe587e5a0a00aac267f645b7c413586e7bc56dca9ff3b00037050d06f476"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/KhronosGroup/OpenCL-Headers/archive/v2020.03.13.tar.gz"
