augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "OpenEXR"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
script = """macos_sdk_version=11.0\nmacosx_deployment_target=11.0\nif [[ \"${target}\" == x86_64-apple-darwin* ]]; then\n    echo \"Extracting MacOSX${macos_sdk_version}.sdk.tar.xz (this may take a while)\"\n    rm -rf /opt/${target}/${target}/sys-root/System\n    rm -rf /opt/${target}/${target}/sys-root/usr/include/libxml2/libxml\n    # extract the tarball into the sys-root so all compilers pick it up\n    # automatically, and use --warning=no-unknown-keyword to hide harmless\n    # warnings about unsupported pax header keywords like \"SCHILY.fflags\"\n    tar --extract \\\n        --file=${WORKSPACE}/srcdir/MacOSX${macos_sdk_version}.sdk.tar.xz \\\n        --directory=\"/opt/${target}/${target}/sys-root/.\" \\\n        --strip-components=1 \\\n        --warning=no-unknown-keyword \\\n        MacOSX${macos_sdk_version}.sdk/System \\\n        MacOSX${macos_sdk_version}.sdk/usr\n    export MACOSX_DEPLOYMENT_TARGET=${macosx_deployment_target}\nfi\ncd $WORKSPACE/srcdir/openexr*\n\n# We are building with old kernel headers that do not define `HWCAP_SVE2`\natomic_patch -p1 $WORKSPACE/srcdir/patches/sve2.patch\n\ncmake -B build -G Ninja \\\n    -DBUILD_TESTING=OFF \\\n    -DOPENEXR_BUILD_TOOLS=OFF \\\n    -DOPENEXR_BUILD_EXAMPLES=OFF \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release\ncmake --build build --parallel ${nproc}\ncmake --install build\ninstall_license LICENSE.md\ninstall_license PATENTS\n"""
version = "v3.4.8"

[[dependencies]]
compat = "~3.2.2"
name = "Imath_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libOpenEXRUtil-3_4"]
type = "lib"
variable_name = "libOpenEXRUtil"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libOpenEXRCore-3_4"]
type = "lib"
variable_name = "libOpenEXRCore"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libOpenEXR-3_4"]
type = "lib"
variable_name = "libOpenEXR"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libIlmThread-3_4"]
type = "lib"
variable_name = "libIlmThread"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libIex-3_4"]
type = "lib"
variable_name = "libIex"

[[sources]]
hash = "adbd2a588b47b1f6d02557571d8e36a91084da8a"
type = "git"
unpack_target = ""
url = "https://github.com/AcademySoftwareFoundation/openexr.git"
[[sources]]
follow_symlinks = false
path = "bundled"
target = ""
type = "directory"
[[sources]]
filename = "MacOSX11.0.sdk.tar.xz"
hash = "c8a9ff16196be43c35b699dd293f0c0563f1239c99caa6b3d53882e556a209bd"
type = "file"
url = "https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX11.0.sdk.tar.xz"
