augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "VIC5"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/VIC5.c/vic/drivers/classic\n\nmkdir -p ${bindir} ${libdir}\nmake CC=${CC} -j${nproc}\nmake install\ninstall_license ${WORKSPACE}/srcdir/VIC5.c/LICENSE.txt\n"""
version = "v0.1.2"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libvic5_classic"]
type = "lib"
variable_name = "libvic5_classic"
[[products]]
binnames = ["vic_classic"]
type = "exe"
variable_name = "vic5_classic"

[[sources]]
hash = "a999edf4624101a647ba8b9a6f8981aa353fd4ac"
type = "git"
unpack_target = ""
url = "https://github.com/CUG-hydro/VIC5.c.git"
