augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SCIP"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """# needed for now\n# clock_gettime requires linking to librt -lrt with old glibc\n# remove when CMake accounts for this\nif [[ \"${target}\" == *86*-linux-gnu ]]; then\n   export LDFLAGS=\"-lrt\"\nelif [[ \"${target}\" == *-mingw* ]]; then\n   # this is required to link to bliss on mingw\n   export LDFLAGS=-L${libdir}\nfi\n\ncd scipoptsuite*\n\natomic_patch -p1 ${WORKSPACE}/srcdir/patches/findbliss.patch\n\nmkdir build\ncd build/\ncmake -DCMAKE_INSTALL_PREFIX=$prefix\\\n  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN}\\\n  -DCMAKE_BUILD_TYPE=Release\\\n  -DPAPILO=0\\\n  -DZIMPL=OFF\\\n  -DGCG=0\\\n  -DUG=0\\\n  -DAMPL=0\\\n  -DBOOST=ON\\\n  -DSYM=bliss\\\n  -DTPI=tny\\\n  -DIPOPT_DIR=${prefix} \\\n  -DIPOPT_LIBRARIES=${libdir} \\\n  -DBLISS_INCLUDE_DIR=${includedir} \\\n  -DBLISS_LIBRARY=bliss \\\n  ..\nmake -j${nproc}\nmake install\n\nmkdir -p ${prefix}/share/licenses/SCIP\nfor dir in scip soplex; do\n    cp $WORKSPACE/srcdir/scipoptsuite*/${dir}/LICENSE ${prefix}/share/licenses/SCIP/LICENSE_${dir}\ndone\ncp $WORKSPACE/srcdir/scipoptsuite*/papilo/COPYING ${prefix}/share/licenses/SCIP/LICENSE_papilo\n"""
version = "v800.0.301"

[[dependencies]]
compat = ""
name = "bliss_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "508c9074-7a14-5c94-9582-3d4bc1871065"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "=1.76.0"
name = "boost_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "28df3c45-c428-5900-9ff8-a3135698ca75"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "1.0.8"
name = "Bzip2_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "GMP_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "300.1400.400"
name = "Ipopt_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Readline_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libscip"]
type = "lib"
variable_name = "libscip"
[[products]]
binnames = ["scip"]
type = "exe"
variable_name = "scipexe"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libsoplexshared"]
type = "lib"
variable_name = "libsoplex"

[[sources]]
hash = "5ad50eb42254c825d96f5747d8f3568dcbff0284dfbd1a727910c5a7c2899091"
type = "archive"
unpack_target = ""
url = "https://scipopt.org/download/release/scipoptsuite-8.0.3.tgz"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
