lazy_artifacts = false
name = "libsndfile"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libsndfile-*/\nCFLAGS=\"-I${prefix}/include\" ./configure --prefix=$prefix --host=$target --disable-static\nmake -j${nproc}\nmake install\n"""
version = "v1.0.28"

[[dependencies]]
name = "FLAC_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Ogg_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "libvorbis_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libsndfile"]
type = "lib"
variable_name = "libsndfile"
[[products]]
binnames = ["sndfile-cmp"]
type = "exe"
variable_name = "sndfile_cmp"
[[products]]
binnames = ["sndfile-concat"]
type = "exe"
variable_name = "sndfile_concat"
[[products]]
binnames = ["sndfile-convert"]
type = "exe"
variable_name = "sndfile_convert"
[[products]]
binnames = ["sndfile-deinterleave"]
type = "exe"
variable_name = "sndfile_deinterleave"
[[products]]
binnames = ["sndfile-info"]
type = "exe"
variable_name = "sndfile_info"
[[products]]
binnames = ["sndfile-interleave"]
type = "exe"
variable_name = "sndfile_interleave"
[[products]]
binnames = ["sndfile-metadata-get"]
type = "exe"
variable_name = "sndfile_metadata_get"
[[products]]
binnames = ["sndfile-metadata-set"]
type = "exe"
variable_name = "sndfile_metadata_set"
[[products]]
binnames = ["sndfile-play"]
type = "exe"
variable_name = "sndfile_play"
[[products]]
binnames = ["sndfile-salvage"]
type = "exe"
variable_name = "sndfile_salvage"

[[sources]]
hash = "1ff33929f042fa333aed1e8923aa628c3ee9e1eb85512686c55092d1e5a9dfa9"
type = "archive"
unpack_target = ""
url = "http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz"
