init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LAMMPS"
platforms = ["i686-linux-gnu-libgfortran4-cxx03", "i686-linux-gnu-libgfortran4-cxx11", "i686-linux-gnu-libgfortran5-cxx03", "i686-linux-gnu-libgfortran5-cxx11", "x86_64-linux-gnu-libgfortran4-cxx03", "x86_64-linux-gnu-libgfortran4-cxx11", "x86_64-linux-gnu-libgfortran5-cxx03", "x86_64-linux-gnu-libgfortran5-cxx11", "aarch64-linux-gnu-libgfortran5-cxx03", "aarch64-linux-gnu-libgfortran5-cxx11", "armv6l-linux-gnueabihf-libgfortran4-cxx03", "armv6l-linux-gnueabihf-libgfortran4-cxx11", "armv6l-linux-gnueabihf-libgfortran5-cxx03", "armv6l-linux-gnueabihf-libgfortran5-cxx11", "armv7l-linux-gnueabihf-libgfortran4-cxx03", "armv7l-linux-gnueabihf-libgfortran4-cxx11", "armv7l-linux-gnueabihf-libgfortran5-cxx03", "armv7l-linux-gnueabihf-libgfortran5-cxx11", "powerpc64le-linux-gnu-libgfortran4-cxx03", "powerpc64le-linux-gnu-libgfortran4-cxx11", "powerpc64le-linux-gnu-libgfortran5-cxx03", "powerpc64le-linux-gnu-libgfortran5-cxx11", "x86_64-apple-darwin-libgfortran4", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5", "i686-w64-mingw32-libgfortran4-cxx03", "i686-w64-mingw32-libgfortran4-cxx11", "i686-w64-mingw32-libgfortran5-cxx03", "i686-w64-mingw32-libgfortran5-cxx11", "x86_64-w64-mingw32-libgfortran4-cxx03", "x86_64-w64-mingw32-libgfortran4-cxx11", "x86_64-w64-mingw32-libgfortran5-cxx03", "x86_64-w64-mingw32-libgfortran5-cxx11"]
script = """cd $WORKSPACE/srcdir/lammps/\nmkdir build && cd build/\ncmake -C ../cmake/presets/most.cmake -C ../cmake/presets/nolib.cmake ../cmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DBUILD_SHARED_LIBS=ON \\\n    -DLAMMPS_EXCEPTIONS=ON \\\n    -DPKG_MPI=ON \\\n    -DPKG_SNAP=ON \\\n    -DPKG_ML-PACE=ON \\\n    -DPKG_DPD-BASIC=OFF \\\n    -DPKG_DPD-MESO=OFF \\\n    -DPKG_DPD-REACT=OFF \\\n    -DPKG_USER-MESODPD=OFF \\\n    -DPKG_USER-DPD=OFF \\\n    -DPKG_USER-SDPD=OFF \\\n    -DPKG_DPD-SMOOTH=OFF\n\t\nmake -j${nproc}\nmake install\n\nif [[ \"${target}\" == *mingw* ]]; then\n    cp *.dll ${prefix}/bin/\nfi\n"""
version = "v1.0.1"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "2"
name = "MPItrampoline_jll"
platforms = ["i686-linux-gnu-libgfortran4-cxx03", "i686-linux-gnu-libgfortran4-cxx11", "i686-linux-gnu-libgfortran5-cxx03", "i686-linux-gnu-libgfortran5-cxx11", "x86_64-linux-gnu-libgfortran4-cxx03", "x86_64-linux-gnu-libgfortran4-cxx11", "x86_64-linux-gnu-libgfortran5-cxx03", "x86_64-linux-gnu-libgfortran5-cxx11", "aarch64-linux-gnu-libgfortran5-cxx03", "aarch64-linux-gnu-libgfortran5-cxx11", "armv6l-linux-gnueabihf-libgfortran4-cxx03", "armv6l-linux-gnueabihf-libgfortran4-cxx11", "armv6l-linux-gnueabihf-libgfortran5-cxx03", "armv6l-linux-gnueabihf-libgfortran5-cxx11", "armv7l-linux-gnueabihf-libgfortran4-cxx03", "armv7l-linux-gnueabihf-libgfortran4-cxx11", "armv7l-linux-gnueabihf-libgfortran5-cxx03", "armv7l-linux-gnueabihf-libgfortran5-cxx11", "powerpc64le-linux-gnu-libgfortran4-cxx03", "powerpc64le-linux-gnu-libgfortran4-cxx11", "powerpc64le-linux-gnu-libgfortran5-cxx03", "powerpc64le-linux-gnu-libgfortran5-cxx11", "x86_64-apple-darwin-libgfortran4", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MicrosoftMPI_jll"
platforms = ["i686-w64-mingw32-libgfortran4-cxx03", "i686-w64-mingw32-libgfortran4-cxx11", "i686-w64-mingw32-libgfortran5-cxx03", "i686-w64-mingw32-libgfortran5-cxx11", "x86_64-w64-mingw32-libgfortran4-cxx03", "x86_64-w64-mingw32-libgfortran4-cxx11", "x86_64-w64-mingw32-libgfortran5-cxx03", "x86_64-w64-mingw32-libgfortran5-cxx11"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["liblammps"]
type = "lib"
variable_name = "liblammps"
[[products]]
binnames = ["lmp"]
type = "exe"
variable_name = "lmp"

[[sources]]
hash = "88fd96ec52f86dba4b222623f3a06632a32e42f1"
type = "git"
unpack_target = ""
url = "https://github.com/lammps/lammps.git"
