buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/02b8d788a4c7bd24afbc15bb60f4f7649182bae9/P/pandoc/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.8"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "pandoc"
platforms = ["x86_64-linux-gnu", "x86_64-apple-darwin", "x86_64-w64-mingw32", "aarch64-linux-gnu", "aarch64-apple-darwin"]
script = """cd ${WORKSPACE}/srcdir/\nmkdir -p \"${bindir}\"\nif [[ \"${target}\" != *-mingw* ]]; then\n    subdir=\"bin/\"\nfi\ncp ${target}/pandoc-*/${subdir}pandoc${exeext} ${bindir}\nchmod +x ${bindir}/*\ninstall_license COPYRIGHT\ninstall_license COPYING.md\n"""
version = "v3.2.0"

    [[metadata.products]]
    binnames = ["pandoc"]
    type = "exe"
    variable_name = "pandoc"

    [[metadata.sources]]
    hash = "ea3f96dde56ae1577c81184694b8576d8efec52e168ce49a6e7df1441f428289"
    type = "archive"
    unpack_target = "x86_64-linux-gnu"
    url = "https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-linux-amd64.tar.gz"
    [[metadata.sources]]
    hash = "0e11ca032fa452d69f8a06a0a4a1c26031ffd95d6f231a780b78bdbc8dd3488a"
    type = "archive"
    unpack_target = "x86_64-apple-darwin14"
    url = "https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-x86_64-macOS.zip"
    [[metadata.sources]]
    hash = "97b71204dd9b1a08f407d763695f54e71f96942c747a04bc16102c9eab5de3a0"
    type = "archive"
    unpack_target = "aarch64-apple-darwin20"
    url = "https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-arm64-macOS.zip"
    [[metadata.sources]]
    hash = "84395462eb08d74df3dbe9bb129ce3508e3eec3f29ac1f55559c2c5a1f34a8bf"
    type = "archive"
    unpack_target = "x86_64-w64-mingw32"
    url = "https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-windows-x86_64.zip"
    [[metadata.sources]]
    hash = "93d6c414e5994e254aec840be8428016a70167c835ca3227378217937bd9a01a"
    type = "archive"
    unpack_target = "aarch64-linux-gnu"
    url = "https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-linux-arm64.tar.gz"
    [[metadata.sources]]
    filename = "COPYRIGHT"
    hash = "f8379c9c714577397f2bdf1a06d0f500844ec924dcb268d85bc047772c35b3d7"
    type = "file"
    url = "https://raw.githubusercontent.com/jgm/pandoc/3.2/COPYRIGHT"
    [[metadata.sources]]
    filename = "COPYING.md"
    hash = "e7ea3adeab955103a837b692ca0017cb3abbed0d3dccbfa499d6b2b825d698c3"
    type = "file"
    url = "https://raw.githubusercontent.com/jgm/pandoc/3.2/COPYING.md"
