augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "object_store_ffi"
platforms = ["aarch64-apple-darwin", "x86_64-linux-gnu", "x86_64-apple-darwin", "aarch64-linux-gnu"]
script = """cd ${WORKSPACE}/srcdir/object_store_ffi/\ncargo rustc --release --lib --crate-type=cdylib\ninstall -Dvm 755 \"target/${rust_target}/release/libobject_store_ffi.${dlext}\" \"${libdir}/libobject_store_ffi.${dlext}\"\n"""
version = "v0.2.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libobject_store_ffi"]
type = "lib"
variable_name = "libobject_store_ffi"

[[sources]]
hash = "f3690b231245591f8d5b8caa05d85540a5f540c7"
type = "git"
unpack_target = ""
url = "https://github.com/RelationalAI/object_store_ffi.git"
