["1.10.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.aarch64-linux-gnu-cxx03-cuda_platform+jetson-cuda+10.2.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.aarch64-linux-gnu-cxx11-cuda_platform+jetson-cuda+10.2.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-linux-gnu-cxx03-cuda+11.3.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-linux-gnu-cxx11-cuda+11.3.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"]
registered = 2025-02-10T18:05:03.000Z

    [["1.10.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.aarch64-linux-gnu-cxx03-cuda_platform+jetson-cuda+10.2.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.aarch64-linux-gnu-cxx11-cuda_platform+jetson-cuda+10.2.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-linux-gnu-cxx03-cuda+11.3.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-linux-gnu-cxx11-cuda+11.3.tar.gz", "https://github.com/JuliaBinaryWrappers/ONNXRuntime_CUDA_jll.jl/releases/download/ONNXRuntime_CUDA-v1.10.0+0/ONNXRuntime_CUDA.v1.10.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/081828fac9f8abe89a4816628ce647b34fbbfa55/O/ONNXRuntime/ONNXRuntime_CUDA/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/o/onnxruntime/onnxruntime_cuda/build_tarballs.jl/081828fac9f8abe89a4816628ce647b34fbbfa55.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        [["1.10.0+0".artifact_metadata.sources]]
        hash = "0d9030e79888d1d5828730b254fedc53c7b640c1"
        type = "git"
        url = "https://github.com/microsoft/onnxruntime.git"
        [["1.10.0+0".artifact_metadata.sources]]
        hash = "0da11b8d953fad4ec75f87bb894f72dea511a3940cff2f4dad37451586d1ebbc"
        type = "archive"
        url = "https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-win-x64-gpu-1.10.0.zip"
        [["1.10.0+0".artifact_metadata.sources]]
        hash = "a608b7a4a4fc6ad5c90d6005edbfe0851847b991b08aafff4549bbbbdb938bf6"
        type = "file"
        url = "https://nvidia.box.com/shared/static/jy7nqva7l88mq9i8bw3g3sklzf4kccn2.whl"
        [["1.10.0+0".artifact_metadata.sources]]
        package = "CUDA_SDK_jll"
        type = "builddependency"
        [["1.10.0+0".artifact_metadata.sources]]
        package = "CUDA_SDK_static_jll"
        type = "builddependency"
        [["1.10.0+0".artifact_metadata.sources]]
        package = "CUDA_full_jll"
        type = "builddependency"
