["2.3.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/opam_jll.jl/releases/download/opam-v2.3.0+0/opam.v2.3.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/opam_jll.jl/releases/download/opam-v2.3.0+0/opam.v2.3.0.x86_64-linux-musl.tar.gz"]
registered = 2025-01-31T14:50:18.000Z

    [["2.3.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/opam_jll.jl/releases/download/opam-v2.3.0+0/opam.v2.3.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/opam_jll.jl/releases/download/opam-v2.3.0+0/opam.v2.3.0.x86_64-linux-musl.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/91a4df87388c9c3aadce29bf5e93b3556a832446/O/opam/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/o/opam/build_tarballs.jl/91a4df87388c9c3aadce29bf5e93b3556a832446.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.3"

        [["2.3.0+0".artifact_metadata.sources]]
        hash = "506ba76865dc315b67df9aa89e7abd5c1a897a7f0a92d7b2694974fdc532b346"
        type = "archive"
        url = "https://github.com/ocaml/opam/releases/download/2.3.0/opam-full-2.3.0.tar.gz"

            ["2.3.0+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/opam"
            version = "2.3.0"
        [["2.3.0+0".artifact_metadata.sources]]
        package = "OCaml_jll"
        type = "builddependency"
