buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f4afdd8e979ec1b5ba43aaf1872d3e33f0622940/S/SCS_GPU/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.2"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SCS_GPU"
platforms = ["x86_64-linux-gnu"]
script = """cd $WORKSPACE/srcdir/scs*\nflags=\"DLONG=0 USE_OPENMP=0\"\nblasldflags=\"-L${libdir} -lopenblas\"\n\nCUDA_PATH=$prefix/cuda make BLASLDFLAGS=\"${blasldflags}\" ${flags} out/libscsgpuindir.${dlext}\n\nmkdir -p ${libdir}\ncp out/libscs*.${dlext} ${libdir}\n"""
version = "v3.2.0"

    [[metadata.dependencies]]
    compat = ""
    name = "OpenBLAS32_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_full_jll"
    platforms = ["any"]
    type = "builddependency"
    version-major = 10
    version-minor = 1
    version-patch = 243

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = true
    libnames = ["libscsgpuindir"]
    type = "lib"
    variable_name = "libscsgpuindir"

    [[metadata.sources]]
    hash = "ac6840a3b3264950e6c300264cbf3937e0bcc6c5"
    type = "git"
    unpack_target = ""
    url = "https://github.com/cvxgrp/scs.git"
