augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GTPSA"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\ncd gtpsa/\nif [[ $target == *\"-apple-\"* ]]\nthen\nCC=gcc\nCXX=g++\nln /workspace/destdir/lib/liblapack32.dylib /workspace/destdir/lib/liblapack.dylib\nelif [[ $target == *\"linux\"* ]]\nthen\nln /workspace/destdir/lib/liblapack32.so /workspace/destdir/lib/liblapack.so\nfi\ncmake . -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN%.*}_gcc.cmake -DCMAKE_BUILD_TYPE=Release\nmake\nmake install\n"""
version = "v1.1.0"

[[dependencies]]
compat = ""
name = "ReferenceBLAS_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "ee697234-451c-51c9-b102-303d89a9c3a0"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LAPACK32_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "17f450c3-bd24-55df-bb84-8c51b4b939e3"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libgtpsa"]
type = "lib"
variable_name = "GTPSA"

[[sources]]
hash = "7916354009343356f5c44b017fded044b4aaaa53"
type = "git"
unpack_target = ""
url = "https://github.com/mattsignorelli/gtpsa.git"
