buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/fb31c78169fe3d77a5312d2348146bfa932be90d/S/SassC/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.1"

[metadata]
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SassC"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/sassc*\nexport CPPFLAGS=\"-I${includedir}\"\nautoreconf --force --install\n./configure --prefix=${prefix} --host=${target} --build=${MACHTYPE}\nmake -j${nproc}\nmake install\n"""
version = "v3.6.2"

    [[metadata.dependencies]]
    compat = "3.6.4"
    name = "libsass_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["sassc"]
    type = "exe"
    variable_name = "sassc"

    [[metadata.sources]]
    hash = "66f0ef37e7f0ad3a65d2f481eff09d09408f42d0"
    type = "git"
    unpack_target = ""
    url = "https://github.com/sass/sassc.git"
