dependencies = []
lazy_artifacts = false
name = "ThriftJuliaCompiler"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\ncd thrift/\n./bootstrap.sh \nif [ $target != \"x86_64-apple-darwin14\" ] && [ $target != \"x86_64-unknown-freebsd11.1\" ]; then     LDFLAGS=\"-static-libgcc -static-libstdc++\";     export LDFLAGS; fi\n./configure --prefix=$prefix --build=${MACHTYPE} --host=$target --enable-tutorial=no --enable-tests=no --enable-libs=no --disable-werror\nmake -j${nproc}\nmake install\n"""
version = "v0.11.0"

[[products]]
binnames = ["thrift"]
type = "exe"
variable_name = "thrift"

[[sources]]
hash = "ef6de66707eb6135402a73520deec3478d9e1ec7"
type = "git"
unpack_target = ""
url = "https://github.com/tanmaykm/thrift.git"
