dependencies = ["Attr_jll"]
name = "Tar"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "arm-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "arm-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1"]
script = """cd $WORKSPACE/srcdir/tar-*/\nexport FORCE_UNSAFE_CONFIGURE=1\n./configure --prefix=${prefix} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v1.32.0"

[[products]]
binnames = ["tar"]
type = "exe"
variable_name = "tar"

[[sources]]
"https://ftp.gnu.org/gnu/tar/tar-1.32.tar.xz" = "d0d3ae07f103323be809bc3eac0dcc386d52c5262499fe05511ac4788af1fdd8"
