buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/adaceafca770ddf8566002b7f72587cf9f888e89/T/tree_sitter_modelica/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "tree_sitter_modelica"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\nmv tree-sitter-* tree-sitter\n\nBUILD_FLAGS=(-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN})\nmkdir build && cd build\ncmake .. \"${BUILD_FLAGS[@]}\"\nmake -j${nproc}\nmake install LANGUAGE_NAME=libtreesitter_modelica\n\ncd ..\ninstall_license tree-sitter/LICENSE\n"""
version = "v0.1.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libtreesitter_modelica"]
    type = "lib"
    variable_name = "libtreesitter_modelica"

    [[metadata.sources]]
    hash = "cf20fb1e68401d1c18825b82802101b3ad1d3f3b"
    type = "git"
    unpack_target = ""
    url = "https://github.com/modelicahub/tree-sitter-modelica.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
