buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/be205597f9793b11705c654bde7a4343bbbc8a1e/T/TetGen/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.0"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "TetGen"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """# This will be used for 1.6\n# zipname=tetgen1.6.0\n# cd $WORKSPACE/srcdir/$zipname\n\nmkdir -p ${libdir}\n\ncd $WORKSPACE/srcdir/tetgen\n\n#\n# Patch tetgen.h  with operators delegating new/delete to malloc/free for C/Julia compatibility\n# Made corresponding feature request to upstream, probably available for 1.6.1\n#\nmv tetgen.h tmp.h\nsed -e \"s/class tetgenio {/class tetgenio { void * operator new(size_t n) {  return malloc(n);} void operator delete(void* p) noexcept {free(p);} /g\" tmp.h > tetgen.h\n\n# Compile and link together with C wrapper\n${CXX} -c -fPIC -std=c++11 -O3 -c -DTETLIBRARY -I. ${WORKSPACE}/srcdir/cwrapper/cwrapper.cxx -o cwrapper.o\n${CXX} -c -fPIC -std=c++11 -O3 -c -DTETLIBRARY tetgen.cxx -o tetgen.o\n${CXX} -c -fPIC -std=c++11 -O3 -c -DTETLIBRARY predicates.cxx -o predicates.o\n${CXX} $LDFLAGS -shared -fPIC tetgen.o predicates.o  cwrapper.o -o ${libdir}/libtet.${dlext}\n\ninstall_license LICENSE\n"""
version = "v1.5.1"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libtet"]
    type = "lib"
    variable_name = "libtet"

    [[metadata.sources]]
    hash = "150223d9416b5b75f5c1e50fda1ff7ba6f96871d"
    type = "git"
    unpack_target = ""
    url = "https://github.com/ufz/tetgen.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "cwrapper"
    target = "cwrapper"
    type = "directory"
