augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Ogg"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libogg-*/\n\n# Don't let `configure` use `-ffast-math` ANYWHERE\nsed -i.bak -e 's/-ffast-math//g' ./configure\n./configure --prefix=$prefix --host=${target} --build=${MACHTYPE}\nmake -j${nproc}\nmake install\n"""
version = "v1.3.6"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libogg"]
type = "lib"
variable_name = "libogg"

[[sources]]
hash = "5c8253428e181840cd20d41f3ca16557a9cc04bad4a3d04cce84808677fa1061"
type = "archive"
unpack_target = ""
url = "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.6.tar.xz"
