buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3dab4fd5c1ea3d46820915bfbd9ec315223a4fe4/G/GAP_pkg/GAP_pkg_datastructures/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.2"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GAP_pkg_datastructures"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
script = """# HACK WORKAROUND GAP_jll deficiencies\n# TODO: tweak for mac build\nif [[ \"${target}\" == *darwin* ]]; then\n  cp gac-darwin ${prefix}/share/gap/gac\nelse\n  cp gac ${prefix}/share/gap/gac\nfi\nchmod a+x ${prefix}/share/gap/gac\ncp sysinfo.gap ${prefix}/share/gap/\n\n# ensure #including src/compiled.h or src/profile.h from GAP_jll works\nln -s . ${prefix}/include/gap/src\ncd datastructures*\n./configure ${prefix}/share/gap\nmake -j${nproc}\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license LICENSE\nrm -rf ${prefix}/include\nrm -rf ${prefix}/share/gap\n"""
version = "v0.200.601"

    [[metadata.dependencies]]
    compat = "~400.1192.0"
    name = "GAP_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "~400.1192.0"
    name = "GAP_lib_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    paths = ["lib/gap/datastructures.so"]
    type = "file"
    variable_name = "datastructures"

    [[metadata.sources]]
    follow_symlinks = false
    path = "../bundled"
    target = ""
    type = "directory"
    [[metadata.sources]]
    hash = "fa05bd5ece4392c78927c7069e8db6fbd0712f73f1b1a00b2d2a2eae712b6fbe"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/gap-packages/datastructures/releases/download/v0.2.6/datastructures-0.2.6.tar.gz"
