buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/cd4cd4d497a87bcb489a60eb3dcd321f995b3a3b/G/GAP_pkg/GAP_pkg_datastructures/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "GAP_pkg_datastructures"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "riscv64-linux-gnu"]
script = """cd datastructures*\n./configure ${prefix}/lib/gap\nmake -j${nproc}\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license LICENSE\n"""
version = "v1.30300.0"

    [[metadata.dependencies]]
    compat = "~400.1500.0"
    name = "GAP_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    paths = ["lib/gap/datastructures.so"]
    type = "file"
    variable_name = "datastructures"

    [[metadata.sources]]
    hash = "c0231ad18ae23a4da6c62373df5032c3bd284dae922e05362551fe55a6a14c0d"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/gap-packages/datastructures/releases/download/v0.3.3/datastructures-0.3.3.tar.gz"
