augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "GAP_pkg_browse"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "riscv64-linux-gnu"]
script = """cd Browse*\n\n# HACK to fool the Browse build system\nmkdir -p ${prefix}/lib/gap\ncp ${prefix}/bin/gac ${prefix}/lib/gap/gac\nchmod a+x ${prefix}/lib/gap/gac\n\n./configure ${prefix}/lib/gap\nmake -j${nproc} CFLAGS=\"-I$includedir -I$includedir/ncurses\"\n\n# revert the HACK\nrm ${prefix}/lib/gap/gac\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license /usr/share/licenses/GPL-3.0+\n"""
version = "v101.82200.0"

[[dependencies]]
compat = "~400.1600.0"
name = "GAP_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "6.5.1"
name = "Ncurses_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["lib/gap/ncurses.so"]
type = "file"
variable_name = "ncurses"

[[sources]]
hash = "4ff36bb787f7da968a920d657a615d601615a3dc0780d31f7bbdb3ff995748ae"
type = "archive"
unpack_target = ""
url = "https://www.math.rwth-aachen.de/~Browse/Browse-1.8.22.tar.bz2"
