buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3bb7ca9e8618aa308b033a08d0e69f4f9288c387/X/Xyce/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.4.1"

[metadata]
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Xyce"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """export TMPDIR=${WORKSPACE}/tmpdir\nmkdir ${TMPDIR}\ncd $WORKSPACE/srcdir\napk add flex-dev\nupdate_configure_scripts --reconf\ninstall_license ${WORKSPACE}/srcdir/Xyce/COPYING\ncd Xyce\nfor f in ${WORKSPACE}/srcdir/patches/*.patch; do\n    atomic_patch -p1 ${f}\ndone\n./bootstrap\ncd ..\nmkdir buildx\ncd buildx\n/workspace/srcdir/Xyce/./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    --enable-shared --disable-mpi \\\n    LDFLAGS=\"-L${libdir} -lopenblas\" \\\n    CPPFLAGS=\"-I/${includedir} -I/usr/include\"\nmake -j${nprocs}\nmake install\n"""
version = "v7.3.1"

    [[metadata.dependencies]]
    compat = ""
    name = "Trilinos_jll"
    type = "dependency"
    uuid = "b6fd3212-6f87-5999-b9ea-021e9cd21b17"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "SuiteSparse_jll"
    type = "dependency"
    uuid = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "OpenBLAS32_jll"
    type = "dependency"
    uuid = "656ef2d0-ae68-5445-9ca0-591084a874a2"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "FFTW_jll"
    type = "dependency"
    uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libxyce"]
    type = "lib"
    variable_name = "libxyce"
    [[metadata.products]]
    binnames = ["Xyce"]
    type = "exe"
    variable_name = "Xyce"

    [[metadata.sources]]
    hash = "9dd4374f64f272dd9186471fd402fdb7241986c0"
    type = "git"
    unpack_target = ""
    url = "https://github.com/Xyce/Xyce.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
