init_block = ""
lazy_artifacts = false
name = "CUDNN_CUDA110"
platforms = ["x86_64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-w64-mingw32"]
script = """mkdir -p ${libdir} ${prefix}/include\n\ncd ${WORKSPACE}/srcdir\nif [[ ${target} == x86_64-linux-gnu ]]; then\n    cd cuda\n    find .\n\n    install_license NVIDIA_SLA_cuDNN_Support.txt\n\n    mv lib64/libcudnn*.so* ${libdir}\n    mv include/* ${prefix}/include\nelif [[ ${target} == powerpc64le-linux-gnu ]]; then\n    cd cuda/targets/ppc64le-linux\n    find .\n\n    install_license NVIDIA_SLA_cuDNN_Support.txt\n\n    mv lib/libcudnn*.so* ${libdir}\n    mv include/* ${prefix}/include\nelif [[ ${target} == x86_64-w64-mingw32 ]]; then\n    cd cuda\n    find .\n\n    install_license NVIDIA_SLA_cuDNN_Support.txt\n\n    mv bin/cudnn*64_*.dll ${libdir}\n    mv include/* ${prefix}/include\nfi\n"""
version = "v8.0.1"

[[dependencies]]
name = "CUDA_jll"
type = "dependency"
version-major = 11
version-minor = 0
version-patch = 2

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcudnn", "cudnn64_8"]
type = "lib"
variable_name = "libcudnn"

[[sources]]
hash = "03cbe5844ff01b3550ba5d0bbf6eab1c33630f18669978af2a7ebf7366a5c442"
type = "archive"
unpack_target = ""
url = "https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.1.13/11.0_20200626/cudnn-11.0-linux-x64-v8.0.1.13.tgz"
[[sources]]
hash = "2529819229eed31c56562b2791f10cba6ce5c729e1d1816933c8ac2b6535075d"
type = "archive"
unpack_target = ""
url = "https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.1.13/11.0_20200626/cudnn-11.0-linux-ppc64le-v8.0.1.13.tgz"
[[sources]]
hash = "72cbf300a23fa1ef737dc217d93c7cbcf10ed4a3f5d3be2b4261dfab1ba14d8d"
type = "archive"
unpack_target = ""
url = "https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.1.13/11.0_20200626/cudnn-11.0-windows-x64-v8.0.1.13.zip"
