buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3aedb28e9e7cdb931099dda9b213c93c93b855c4/F/FastJet_Julia_Wrapper/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.6"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FastJet_Julia_Wrapper"
platforms = ["i686-linux-gnu-cxx03-julia_version+1.6.3", "i686-linux-gnu-cxx11-julia_version+1.6.3", "x86_64-linux-gnu-cxx03-julia_version+1.6.3", "x86_64-linux-gnu-cxx11-julia_version+1.6.3", "aarch64-linux-gnu-cxx03-julia_version+1.6.3", "aarch64-linux-gnu-cxx11-julia_version+1.6.3", "armv7l-linux-gnueabihf-cxx03-julia_version+1.6.3", "armv7l-linux-gnueabihf-cxx11-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx03-julia_version+1.6.3", "powerpc64le-linux-gnu-cxx11-julia_version+1.6.3", "x86_64-linux-musl-cxx03-julia_version+1.6.3", "x86_64-linux-musl-cxx11-julia_version+1.6.3", "aarch64-linux-musl-cxx03-julia_version+1.6.3", "aarch64-linux-musl-cxx11-julia_version+1.6.3", "armv7l-linux-musleabihf-cxx03-julia_version+1.6.3", "armv7l-linux-musleabihf-cxx11-julia_version+1.6.3", "x86_64-apple-darwin-julia_version+1.6.3", "x86_64-unknown-freebsd-julia_version+1.6.3", "i686-linux-gnu-cxx03-julia_version+1.7.0", "i686-linux-gnu-cxx11-julia_version+1.7.0", "x86_64-linux-gnu-cxx03-julia_version+1.7.0", "x86_64-linux-gnu-cxx11-julia_version+1.7.0", "aarch64-linux-gnu-cxx03-julia_version+1.7.0", "aarch64-linux-gnu-cxx11-julia_version+1.7.0", "armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0", "armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0", "armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0", "armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.7.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.7.0", "x86_64-linux-musl-cxx03-julia_version+1.7.0", "x86_64-linux-musl-cxx11-julia_version+1.7.0", "aarch64-linux-musl-cxx03-julia_version+1.7.0", "aarch64-linux-musl-cxx11-julia_version+1.7.0", "armv6l-linux-musleabihf-cxx03-julia_version+1.7.0", "armv6l-linux-musleabihf-cxx11-julia_version+1.7.0", "armv7l-linux-musleabihf-cxx03-julia_version+1.7.0", "armv7l-linux-musleabihf-cxx11-julia_version+1.7.0", "x86_64-apple-darwin-julia_version+1.7.0", "aarch64-apple-darwin-julia_version+1.7.0", "x86_64-unknown-freebsd-julia_version+1.7.0", "i686-linux-gnu-cxx03-julia_version+1.8.0", "i686-linux-gnu-cxx11-julia_version+1.8.0", "x86_64-linux-gnu-cxx03-julia_version+1.8.0", "x86_64-linux-gnu-cxx11-julia_version+1.8.0", "aarch64-linux-gnu-cxx03-julia_version+1.8.0", "aarch64-linux-gnu-cxx11-julia_version+1.8.0", "armv6l-linux-gnueabihf-cxx03-julia_version+1.8.0", "armv6l-linux-gnueabihf-cxx11-julia_version+1.8.0", "armv7l-linux-gnueabihf-cxx03-julia_version+1.8.0", "armv7l-linux-gnueabihf-cxx11-julia_version+1.8.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.8.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.8.0", "x86_64-linux-musl-cxx03-julia_version+1.8.0", "x86_64-linux-musl-cxx11-julia_version+1.8.0", "aarch64-linux-musl-cxx03-julia_version+1.8.0", "aarch64-linux-musl-cxx11-julia_version+1.8.0", "armv6l-linux-musleabihf-cxx03-julia_version+1.8.0", "armv6l-linux-musleabihf-cxx11-julia_version+1.8.0", "armv7l-linux-musleabihf-cxx03-julia_version+1.8.0", "armv7l-linux-musleabihf-cxx11-julia_version+1.8.0", "x86_64-apple-darwin-julia_version+1.8.0", "aarch64-apple-darwin-julia_version+1.8.0", "x86_64-unknown-freebsd-julia_version+1.8.0", "i686-linux-gnu-cxx03-julia_version+1.9.0", "i686-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-gnu-cxx03-julia_version+1.9.0", "x86_64-linux-gnu-cxx11-julia_version+1.9.0", "aarch64-linux-gnu-cxx03-julia_version+1.9.0", "aarch64-linux-gnu-cxx11-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.9.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.9.0", "x86_64-linux-musl-cxx03-julia_version+1.9.0", "x86_64-linux-musl-cxx11-julia_version+1.9.0", "aarch64-linux-musl-cxx03-julia_version+1.9.0", "aarch64-linux-musl-cxx11-julia_version+1.9.0", "x86_64-apple-darwin-julia_version+1.9.0", "aarch64-apple-darwin-julia_version+1.9.0", "x86_64-unknown-freebsd-julia_version+1.9.0", "i686-linux-gnu-cxx03-julia_version+1.10.0", "i686-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-gnu-cxx03-julia_version+1.10.0", "x86_64-linux-gnu-cxx11-julia_version+1.10.0", "aarch64-linux-gnu-cxx03-julia_version+1.10.0", "aarch64-linux-gnu-cxx11-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx03-julia_version+1.10.0", "powerpc64le-linux-gnu-cxx11-julia_version+1.10.0", "x86_64-linux-musl-cxx03-julia_version+1.10.0", "x86_64-linux-musl-cxx11-julia_version+1.10.0", "aarch64-linux-musl-cxx03-julia_version+1.10.0", "aarch64-linux-musl-cxx11-julia_version+1.10.0", "x86_64-apple-darwin-julia_version+1.10.0", "aarch64-apple-darwin-julia_version+1.10.0", "x86_64-unknown-freebsd-julia_version+1.10.0"]
script = """cd ${WORKSPACE}/srcdir/FastJet_Julia_Wrapper\nmkdir build && cd build\ncmake -DJulia_PREFIX=${prefix} -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_FIND_ROOT_PATH=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release ..\nmake -j${nproc}\nmake install\ninstall_license $WORKSPACE/srcdir/FastJet_Julia_Wrapper/LICENSE.md\n"""
version = "v0.8.7"

    [[metadata.dependencies]]
    compat = ""
    name = "libcxxwrap_julia_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "FastJet_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "libjulia_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libfastjetwrap"]
    type = "lib"
    variable_name = "libfastjetwrap"

    [[metadata.sources]]
    hash = "dc12b746c4ac0ec03e506113d21b53ff02f8e1c0"
    type = "git"
    unpack_target = ""
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper.git"
