buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/0f34b73981a34fb6e8bad3ae6cf91a7409d65b58/P/prrte/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.6"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "prrte"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin"]
script = """cd $WORKSPACE/srcdir/prrte-*\n\n# Autotools doesn't add `${includedir}` as an include directory on some platforms\nexport CPPFLAGS=\"-I${includedir}\"\n\n./configure \\\n    --build=${MACHTYPE} \\\n    --enable-shared \\\n    --host=${target} \\\n    --prefix=${prefix} \\\n    --with-hwloc=${prefix} \\\n    --with-libevent=${prefix} \\\n    --with-pmix=${prefix}\nmake -j${nproc}\nmake install\n"""
version = "v3.0.2"

    [[metadata.dependencies]]
    compat = ""
    name = "Hwloc_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "e33a78d0-f292-5ffc-b300-72abe9b543c8"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "PMIx_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "32165bc3-0280-59bc-8c0b-c33b6203efab"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "libevent_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "1080aeaf-3a6a-583e-a51c-c537b09f60ec"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["prte"]
    type = "exe"
    variable_name = "prte"
    [[metadata.products]]
    binnames = ["prun"]
    type = "exe"
    variable_name = "prun"
    [[metadata.products]]
    binnames = ["prte_info"]
    type = "exe"
    variable_name = "prte_info"
    [[metadata.products]]
    binnames = ["prterun"]
    type = "exe"
    variable_name = "prterun"

    [[metadata.sources]]
    hash = "1aaa1bb930e8e940251ea682b4a6abc24e4849fa9ffbaaaaf2750a38ba4e474a"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/openpmix/prrte/releases/download/v3.0.2/prrte-3.0.2.tar.bz2"
