dependencies = ["Libglvnd_jll", "X11_jll"]
name = "GLFW"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "arm-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "arm-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/glfw-*/\nmkdir build && cd build\ncmake .. -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=\"${CMAKE_TARGET_TOOLCHAIN}\" \\\n    -DBUILD_SHARED_LIBS=ON \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DGLFW_BUILD_EXAMPLES=false \\\n    -DGLFW_BUILD_TESTS=false \\\n    -DGLFW_BUILD_DOCS=OFF\nmake -j${nproc}\nmake install\n"""
version = "v3.3.0"

[[products]]
dir_paths = []
dont_dlopen = false
libnames = ["libglfw", "glfw3"]
type = "lib"
variable_name = "libglfw"

[[sources]]
"https://github.com/glfw/glfw/releases/download/3.3/glfw-3.3.zip" = "36fda4cb173e3eb2928c976b0e9b5014e2e5d12b9b787efa0aa29ffc41c37c4a"
