dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Vulkan_Headers"
script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
version = "v1.2.151"

[[products]]
paths = ["share/vulkan/registry/vk.xml"]
type = "file"
variable_name = "vk_xml"

[[sources]]
hash = "99638d8d7fc64ae9c3fc6a396ec034abd40e675d"
type = "git"
unpack_target = ""
url = "https://github.com/KhronosGroup/Vulkan-Headers.git"
