augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "STRIDE"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/stride*/\n\ncd src\nmake\ninstall -Dvm 755 \"stride\" \"${bindir}/stride${exeext}\"\n\n# build shared library\nmkdir -p \"${libdir}\"\n\"${CC}\" -shared -g -O2 -o \"${libdir}\"/libstride.${dlext} *.o -lm\n\ninstall_license ../LICENSE\n"""
version = "v1.0.0"

[[products]]
binnames = ["stride"]
type = "exe"
variable_name = "stride_exe"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libstride"]
type = "lib"
variable_name = "libstride"

[[sources]]
hash = "71bb229679248b7ee6c39d0e95baca3eb7453427"
type = "git"
unpack_target = ""
url = "https://github.com/m3g/stride"
