augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Pixman"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/pixman-*\n\n# Define `generic_blt`; see\n# <https://lists.freedesktop.org/archives/pixman/2023-February/005002.html>\n# and\n# <https://gitlab.freedesktop.org/rth7680/pixman/-/tree/general>\natomic_patch -p1 ${WORKSPACE}/srcdir/patches/general_blt.patch\n\nmkdir build && cd build\nmeson setup --cross-file=\"${MESON_TARGET_TOOLCHAIN}\" --buildtype=release -Dtests=disabled -Ddemos=disabled ..\nninja -j${nproc}\nninja install\n\ninstall_license ../COPYING\n"""
version = "v0.46.0"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "i686-w64-mingw32", "x86_64-w64-mingw32"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LLVMOpenMP_jll"
platforms = ["x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
top_level = false
type = "dependency"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpixman-1"]
type = "lib"
variable_name = "libpixman"

[[sources]]
hash = "02d9ff7b8458ef61731c3d355f854bbf461fd0a4d3563c51f1c1c7b00638050d"
type = "archive"
unpack_target = ""
url = "https://www.cairographics.org/releases/pixman-0.46.0.tar.gz"
[[sources]]
follow_symlinks = false
path = "bundled"
target = ""
type = "directory"
