dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Pixman"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/pixman-*/\n\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --disable-static\nmake -j${nproc}\nmake install\n"""
version = "v0.40.1"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpixman-1"]
type = "lib"
variable_name = "libpixman"

[[sources]]
hash = "6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc"
type = "archive"
unpack_target = ""
url = "https://www.cairographics.org/releases/pixman-0.40.0.tar.gz"
