augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "BiqCrunch"
platforms = ["x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran5", "x86_64-linux-musl-libgfortran5", "aarch64-linux-musl-libgfortran5", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5", "x86_64-unknown-freebsd-libgfortran5", "aarch64-unknown-freebsd-libgfortran5"]
script = """cd $WORKSPACE/srcdir\ncd BiqCrunch-*/src/\nmake -f Makefile.BinaryBuilder \n"""
version = "v2.0.2"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenBLAS32_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "656ef2d0-ae68-5445-9ca0-591084a874a2"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["max-indep-set_bq"]
type = "exe"
variable_name = "maxindepset_bq"
[[products]]
binnames = ["k-cluster_bq"]
type = "exe"
variable_name = "kcluster_bq"
[[products]]
binnames = ["max-cut_bq"]
type = "exe"
variable_name = "maxcut_bq"
[[products]]
binnames = ["generic_bq"]
type = "exe"
variable_name = "generic_bq"

[[sources]]
hash = "1296e2722a6a76471219bb7a25fda59bc875f9b9ce4cdecc715fc079fc56ba69"
type = "archive"
unpack_target = ""
url = "https://gitlab.inria.fr/mbesanco/BiqCrunch/-/archive/v2.0.2/BiqCrunch-v2.0.2.tar.gz"
