dependencies = []
name = "pprof"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "arm-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "arm-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/pprof/\nmkdir -p ${bindir}\ngo build -o ${bindir}\n"""
version = "v0.0.0-20191205061153"

[[products]]
binnames = ["pprof"]
type = "exe"
variable_name = "pprof"

[[sources]]
"https://github.com/google/pprof.git" = "f9b734f9ee64d0f5b63636a45cc77ed2744997ab"
