augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "GAP_pkg_cvec"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "riscv64-linux-gnu"]
script = """cd cvec*\n./configure ${prefix}/lib/gap\nmake -j${nproc}\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license LICENSE\n"""
version = "v201.80400.0"

[[dependencies]]
compat = "~400.1500.0"
name = "GAP_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["lib/gap/cvec.so"]
type = "file"
variable_name = "cvec"

[[sources]]
hash = "0df5c9d9b5e55002f596e79a4a799d09554d4964683fbd8f813ed2f9d2f5635f"
type = "archive"
unpack_target = ""
url = "https://github.com/gap-packages/cvec/releases/download/v2.8.4/cvec-2.8.4.tar.gz"
