["3.12.0+0"]
artifact_metadata = "artifact_metadata/E/ELFIO_jll/ELFIO-v3.12.0+0.toml"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/ELFIO_jll.jl/releases/download/ELFIO-v3.12.0+0/ELFIO.v3.12.0.any.tar.gz"]
registered = 2024-08-17T15:56:09.000Z
