["0.0.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/exprtk_jll.jl/releases/download/exprtk-v0.0.3+0/exprtk.v0.0.3.any.tar.gz"]
registered = 2025-05-27T14:03:43.000Z

    [["0.0.3+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/exprtk_jll.jl/releases/download/exprtk-v0.0.3+0/exprtk.v0.0.3.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2de807116287f2d5744a6c82741f19bcf9e52ecd/E/exprtk/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/e/exprtk/build_tarballs.jl/2de807116287f2d5744a6c82741f19bcf9e52ecd.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        [["0.0.3+0".artifact_metadata.sources]]
        hash = "a4b17d543f072d2e3ba564e4bc5c3a0d2b05c338"
        type = "git"
        url = "https://github.com/ArashPartow/exprtk"
