init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "PMIx"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin"]
script = """cd $WORKSPACE/srcdir\ncd pmix-*\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    --enable-shared \\\n    --with-libevent=${prefix} \\\n    --with-hwloc=${prefix} \\\n    --without-tests-examples \\\n    --disable-man-pages \\\n    --enable-debug\nmake -j${nproc}\nmake install\n"""
version = "v4.1.0"

[[dependencies]]
compat = ""
name = "libevent_jll"
type = "dependency"
uuid = "1080aeaf-3a6a-583e-a51c-c537b09f60ec"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Hwloc_jll"
type = "dependency"
uuid = "e33a78d0-f292-5ffc-b300-72abe9b543c8"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpmix"]
type = "lib"
variable_name = "libpmix"

[[sources]]
hash = "145f05a6c621bfb3fc434776b615d7e6d53260cc9ba340a01f55b383e07c842e"
type = "archive"
unpack_target = ""
url = "https://github.com/openpmix/openpmix/releases/download/v4.1.0/pmix-4.1.0.tar.bz2"
