augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "at_spi2_core"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/at-spi2-core-*/\nmkdir build && cd build\n\n# Get a local gettext for msgfmt cross-building\napk add gettext\n\n# We need `fixesproto @6`, but the latest release is `fixesproto @5`.\n# (There is a `libXfixes @6`, but no respective `fixesproto @6` exists.)\n# The X11 system is quite stable so this work-around should work.\n# See e.g. <https://forums.dolphin-emu.org/Thread-compiling-on-ubuntu-20-04-fixesproto-6-0-error>.\nmv $libdir/pkgconfig/fixesproto.pc $libdir/pkgconfig/fixesproto.pc.saved\nsed 's/Version: 5.0/Version: 6.0/' $libdir/pkgconfig/fixesproto.pc.saved >$libdir/pkgconfig/fixesproto.pc\n\nmeson .. --cross-file=\"${MESON_TARGET_TOOLCHAIN}\" \\\n    -Dintrospection=disabled \\\n    -Dx11=enabled \\\n    -Dsystemd_user_dir=no\nninja -j${nproc}\nninja install\n\n# Undo change from above\nmv $libdir/pkgconfig/fixesproto.pc.saved $libdir/pkgconfig/fixesproto.pc\n"""
version = "v2.56.2"

[[dependencies]]
compat = ""
name = "Dbus_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "2.84.0"
name = "Glib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libXtst_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_fixesproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_inputproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_kbproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_recordproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xextproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xproto_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libatspi"]
type = "lib"
variable_name = "libatspi"

[[sources]]
hash = "e1b1c9836a8947852f7440c32e23179234c76bd98cd9cc4001f376405f8b783b"
type = "archive"
unpack_target = ""
url = "http://ftp.gnome.org/pub/gnome/sources/at-spi2-core/2.56/at-spi2-core-2.56.2.tar.xz"
