augment_platform_block = ""
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "oneAPI_Level_Zero_Loader_LTS"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11"]
script = """cd level-zero\ninstall_license LICENSE\n\nmkdir build && cd build\ncmake -DCMAKE_INSTALL_PREFIX=$prefix \\\n      -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n      -DCMAKE_BUILD_TYPE=Release ..\nmake -j${nproc}\nmake install\n"""
version = "v1.24.0"

[[dependencies]]
compat = ""
name = "OpenCL_Headers_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "=1.13.0"
name = "oneAPI_Level_Zero_Headers_LTS_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libze_loader"]
type = "lib"
variable_name = "libze_loader"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libze_tracing_layer"]
type = "lib"
variable_name = "libze_tracing_layer"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libze_validation_layer"]
type = "lib"
variable_name = "libze_validation_layer"

[[sources]]
hash = "9402907a3ce6987871325e4e1329e053b8e5cf2b"
type = "git"
unpack_target = ""
url = "https://github.com/oneapi-src/level-zero.git"
