init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libwebp"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/libwebp-*/\nexport CFLAGS=\"-std=c99\"\nexport CPPFLAGS=\"-I${includedir}\"\nexport LDFLAGS=\"-L${libdir}\"\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    --enable-swap-16bit-csp \\\n    --enable-experimental \\\n    --enable-libwebp{mux,demux,decoder,extras} \\\n    --disable-static\nmake -j${nproc}\nmake install\n"""
version = "v1.2.0"

[[dependencies]]
compat = ""
name = "Giflib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "JpegTurbo_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "libpng_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Libtiff_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Libglvnd_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libwebpdecoder"]
type = "lib"
variable_name = "libwebpdecoder"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libwebpdemux"]
type = "lib"
variable_name = "libwebpdemux"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libwebpmux"]
type = "lib"
variable_name = "libwebpmux"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libwebp"]
type = "lib"
variable_name = "libwebp"
[[products]]
binnames = ["cwebp"]
type = "exe"
variable_name = "cwebp"
[[products]]
binnames = ["dwebp"]
type = "exe"
variable_name = "dwebp"
[[products]]
binnames = ["gif2webp"]
type = "exe"
variable_name = "gif2webp"
[[products]]
binnames = ["img2webp"]
type = "exe"
variable_name = "img2webp"
[[products]]
binnames = ["webpinfo"]
type = "exe"
variable_name = "webpinfo"
[[products]]
binnames = ["webpmux"]
type = "exe"
variable_name = "webpmux"

[[sources]]
hash = "2fc8bbde9f97f2ab403c0224fb9ca62b2e6852cbc519e91ceaa7c153ffd88a0c"
type = "archive"
unpack_target = ""
url = "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.0.tar.gz"
