buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/847e94d852e4ac20f28b7549d59d736463d84ae5/E/Epsteinlib/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Epsteinlib"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """pip install cython\ncd $WORKSPACE/srcdir/epsteinlib\nmeson setup build --cross-file=${MESON_TARGET_TOOLCHAIN} --buildtype=release -Dbuild_python=false\nninja -C build -j${nproc}\nninja -C build install\ninstall_license LICENSES/*\n"""
version = "v0.5.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libepstein"]
    type = "lib"
    variable_name = "libepstein"
    [[metadata.products]]
    binnames = ["epsteinlib_c-lattice_sum"]
    type = "exe"
    variable_name = "epsteinlib_c_lattice_sum"

    [[metadata.sources]]
    hash = "de8028eb1c539cd4ef8c5ab229f4398c68577722"
    type = "git"
    unpack_target = ""
    url = "https://github.com/epsteinlib/epsteinlib.git"
