augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FLAC"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/flac-*/\n\nif [[ \"${target}\" == *-mingw* ]]; then\n    # Fix error\n    #     .libs/metadata_iterators.o:metadata_iterators.c:(.text+0x106b): undefined reference to `__memset_chk'\n    # See https://github.com/msys2/MINGW-packages/issues/5868#issuecomment-544107564\n    export LIBS=\"-lssp\"\nelif [[ \"${target}\" == *-musl* ]]; then\n    # Stack protection doesn't seem to work/be needed with Musl\n    FLAGS=(--disable-stack-smash-protection)\nfi\n\n./configure --prefix=$prefix --host=$target  --build=${MACHTYPE} \"${FLAGS[@]}\"\nmake -j${nproc}\nmake install\ninstall_license COPYING.Xiph\n"""
version = "v1.5.0"

[[dependencies]]
compat = ""
name = "Ogg_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libFLAC"]
type = "lib"
variable_name = "libflac"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libFLAC++"]
type = "lib"
variable_name = "libflacpp"
[[products]]
binnames = ["metaflac"]
type = "exe"
variable_name = "metaflac"
[[products]]
binnames = ["flac"]
type = "exe"
variable_name = "flac"

[[sources]]
hash = "f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920"
type = "archive"
unpack_target = ""
url = "https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.5.0.tar.xz"
