buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/c1de5e851bdfd69deb0f0f7cfdda91feab812fe5/I/ImageMagick/ImageMagick@6/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.4"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "ImageMagick"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx03", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/ImageMagick6*/\n\nif [[ \"${target}\" == *86*-linux-gnu ]]; then\n    # For `clock_gettime`\n    atomic_patch -p1 ../patches/utilities-link-rt.patch\nelif [[ \"${target}\" == *-mingw* ]]; then\n    # For `clock_gettime`\n    atomic_patch -p1 ../patches/check-have-clock-realtime.patch\n    # otherwise autotools looks in ${prefix}/lib\n    export LDFLAGS=-L${libdir}\nfi\n\n./configure --prefix=${prefix} \\\n    --build=${MACHTYPE} \\\n    --host=${target} \\\n    --without-x \\\n    --disable-openmp \\\n    --disable-installed \\\n    --disable-dependency-tracking \\\n    --without-frozenpaths \\\n    --without-perl \\\n    --disable-docs \\\n    --disable-static \\\n    --with-gslib\n\nmake -j${nproc}\nmake install\n"""
version = "v6.9.13026"

    [[metadata.dependencies]]
    compat = ""
    name = "Ghostscript_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "JpegTurbo_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "~4.5.1"
    name = "Libtiff_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "OpenJpeg_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.2.12"
    name = "Zlib_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "libpng_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libMagickWand", "libMagickWand-6.Q16"]
    type = "lib"
    variable_name = "libwand"
    [[metadata.products]]
    binnames = ["convert"]
    type = "exe"
    variable_name = "imagemagick_convert"
    [[metadata.products]]
    binnames = ["identify"]
    type = "exe"
    variable_name = "identify"
    [[metadata.products]]
    binnames = ["montage"]
    type = "exe"
    variable_name = "montage"
    [[metadata.products]]
    binnames = ["mogrify"]
    type = "exe"
    variable_name = "mogrify"

    [[metadata.sources]]
    hash = "10f84a86515a7d9ec4c7a11d2249def100266846"
    type = "git"
    unpack_target = ""
    url = "https://github.com/ImageMagick/ImageMagick6"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
