init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "GR"
platforms = ["armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "x86_64-apple-darwin14"]
script = """if test -f \"$prefix/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake\"; then\n    sed -i 's/_qt5gui_find_extra_libs.*AGL.framework.*//' $prefix/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake\nfi\n\nif [[ $target == *\"mingw\"* ]]; then\n    winflags=-DCMAKE_C_FLAGS=\"-D_WIN32_WINNT=0x0f00\"\nfi\n\nmkdir build\ncd build\ncmake $winflags -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_FIND_ROOT_PATH=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release ../gr*\nVERBOSE=ON cmake --build . --config Release --target install -- -j${nproc}\ninstall_license $WORKSPACE/srcdir/gr*/LICENSE.md\n\nif [[ $target == *\"apple-darwin\"* ]]; then\n    cd $prefix/lib\n    ln -s libGR.so libGR.dylib\n    ln -s libGR3.so libGR3.dylib\n    ln -s libGRM.so libGRM.dylib\n    ln -s libGKS.so libGKS.dylib\n    cd ../bin\n    ln -s ../Applications/gksqt.app/Contents/MacOS/gksqt ./\nfi\n"""
version = "v0.51.2"

[[dependencies]]
name = "Bzip2_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Cairo_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "FFMPEG_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Fontconfig_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "GLFW_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "JpegTurbo_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "libpng_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Libtiff_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Pixman_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Qhull_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Qt_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Xorg_libX11_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Xorg_xproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Zlib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGR"]
type = "lib"
variable_name = "libGR"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGR3"]
type = "lib"
variable_name = "libGR3"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGRM"]
type = "lib"
variable_name = "libGRM"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGKS"]
type = "lib"
variable_name = "libGKS"
[[products]]
binnames = ["gksqt"]
type = "exe"
variable_name = "gksqt"

[[sources]]
hash = "ad3fe53dbc5396cba47ad75364da69ad6a1f405f"
type = "git"
unpack_target = ""
url = "https://github.com/sciapp/gr.git"
