augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GR"
platforms = ["armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/gr\n\nif test -f \"$prefix/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake\"; then\n    sed -i 's/_qt5gui_find_extra_libs.*AGL.framework.*//' $prefix/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake\nfi\n\nupdate_configure_scripts\n\nmake -C 3rdparty/qhull -j${nproc}\n\nif [[ $target == *\"mingw\"* ]]; then\n    winflags=-DCMAKE_C_FLAGS=\"-D_WIN32_WINNT=0x0f00\"\n    tifflags=-DTIFF_LIBRARY=${libdir}/libtiff-5.dll\nelse\n    tifflags=-DTIFF_LIBRARY=${libdir}/libtiff.${dlext}\nfi\n\nif [[ \"${target}\" == *apple* ]]; then\n    make -C 3rdparty/zeromq ZEROMQ_EXTRA_CONFIGURE_FLAGS=\"--host=${target}\"\nfi\n\nif [[ \"${target}\" == arm-* ]]; then\n    export CXXFLAGS=\"-Wl,-rpath-link,/opt/${target}/${target}/lib\"\nfi\n\nmkdir build\ncd build\ncmake $winflags -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_FIND_ROOT_PATH=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DGR_USE_BUNDLED_LIBRARIES=ON $tifflags -DCMAKE_BUILD_TYPE=Release ..\n\nVERBOSE=ON cmake --build . --config Release --target install -- -j${nproc}\ncp ../../gr.js ${libdir}/\n\ninstall_license $WORKSPACE/srcdir/gr/LICENSE.md\n\nif [[ $target == *\"apple-darwin\"* ]]; then\n    cd ${bindir}\n    ln -s ../Applications/gksqt.app/Contents/MacOS/gksqt ./\n    ln -s ../Applications/GKSTerm.app/Contents/MacOS/GKSTerm ./\nfi\n"""
version = "v0.64.1"

[[dependencies]]
compat = "1.0.8"
name = "Bzip2_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "1.16.1"
name = "Cairo_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "FFMPEG_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Fontconfig_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "GLFW_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "JpegTurbo_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "libpng_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "4.3.0"
name = "Libtiff_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Pixman_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Qt5Base_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libX11_jll"
platforms = ["any"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xproto_jll"
platforms = ["any"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGR"]
type = "lib"
variable_name = "libGR"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGR3"]
type = "lib"
variable_name = "libGR3"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGRM"]
type = "lib"
variable_name = "libGRM"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libGKS"]
type = "lib"
variable_name = "libGKS"
[[products]]
binnames = ["gksqt"]
type = "exe"
variable_name = "gksqt"

[[sources]]
hash = "41ed7a59d79ded65e603084a021e27049c251dae"
type = "git"
unpack_target = ""
url = "https://github.com/sciapp/gr.git"
[[sources]]
filename = "gr.js"
hash = "3b4105772ac0b41a4cb2fb926afd37c9b1c1eabdadb77aa332da642361aeeeb8"
type = "file"
url = "https://github.com/sciapp/gr/releases/download/v0.64.1/gr-0.64.1.js"
