buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/7b2b4526b40bd5933134958cf065557ff13bf8a5/G/GTK4/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.1"

[metadata]
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GTK4"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/gtk*/\n\n# We need to run some commands with a native Glib\napk add glib-dev\n\n# This is awful, I know\nln -sf /usr/bin/glib-compile-resources ${bindir}/glib-compile-resources\nln -sf /usr/bin/glib-compile-schemas ${bindir}/glib-compile-schemas\nln -sf /usr/bin/gdk-pixbuf-pixdata ${bindir}/gdk-pixbuf-pixdata\n# Remove gio-2.0 pkgconfig file so that it isn't picked up by post-install script.\nrm ${prefix}/lib/pkgconfig/gio-2.0.pc\n\n# llvm-ar seems to generate corrupted static archives:\n#\n#     [974/980] Linking target gtk/libgtk-4.1.dylib\n#     ninja: job failed: [...]\n#     ld: warning: ignoring file gtk/css/libgtk_css.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x74 0x68 0x69 0x6E 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )\n#     ld: warning: ignoring file gtk/libgtk.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x74 0x68 0x69 0x6E 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )\n#     ld: warning: ignoring file gsk/libgsk.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x74 0x68 0x69 0x6E 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )\n#     ld: warning: ignoring file gsk/libgsk_f16c.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x74 0x68 0x69 0x6E 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )\n#     Undefined symbols for architecture x86_64:\n#       \"_gtk_make_symbolic_pixbuf_from_data\", referenced from:\n#           _main in encodesymbolic.c.o\n#     ld: symbol(s) not found for architecture x86_64\nif [[ \"${target}\" == *apple* ]]; then\n    sed -i \"s?^ar = .*?ar = '/opt/${target}/bin/${target}-ar'?g\" \"${MESON_TARGET_TOOLCHAIN}\"\nfi\n\n# https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4443\natomic_patch -p1 ../patches/0001-Include-gdk-private.h-to-fix-error-about-g_source_se.patch\n# https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4445\natomic_patch -p1 ../patches/0001-gdkjpeg-include-stdlib.h-necessary-for-free.patch\n\nFLAGS=()\nif [[ \"${target}\" == *-apple-* ]]; then\n    FLAGS+=(-Dx11-backend=false -Dwayland-backend=false)\nelif [[ \"${target}\" == *-freebsd* ]]; then\n    FLAGS+=(-Dwayland-backend=false)\nelif [[ \"${target}\" == *-mingw* ]]; then\n    # Need to tell we're targeting at least Windows 7 so that `GC_ALLGESTURES` is defined\n    sed -ri \"s/^c_args = \\[(.*)\\]/c_args = [\\1, '-DWINVER=_WIN32_WINNT_WIN7']/\" ${MESON_TARGET_TOOLCHAIN}\nfi\n\nmkdir build-gtk && cd build-gtk\nmeson .. \\\n    --buildtype=release \\\n    -Dmedia-gstreamer=disabled \\\n    -Dintrospection=disabled \\\n    -Ddemos=false \\\n    -Dbuild-examples=false \\\n    -Dbuild-tests=false \\\n    -Dgtk_doc=false \\\n    \"${FLAGS[@]}\" \\\n    --cross-file=\"${MESON_TARGET_TOOLCHAIN}\"\nninja -j${nproc}\nninja install\n\n# Remove temporary links\nrm ${bindir}/gdk-pixbuf-pixdata ${bindir}/glib-compile-{resources,schemas}\n"""
version = "v4.6.0"

    [[metadata.dependencies]]
    compat = ""
    name = "SassC_jll"
    platforms = ["any"]
    type = "hostdependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Wayland_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "hostdependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_xorgproto_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "2.68.3"
    name = "Glib_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.10.6"
    name = "Graphene_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Cairo_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.50.3"
    name = "Pango_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "FriBidi_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "FreeType2_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "gdk_pixbuf_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Libepoxy_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "HarfBuzz_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "xkbcommon_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "iso_codes_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Wayland_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.23"
    name = "Wayland_protocols_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXrandr_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libX11_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXrender_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXi_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXext_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXcursor_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXdamage_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXfixes_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Xorg_libXinerama_jll"
    platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Fontconfig_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgtk-4"]
    type = "lib"
    variable_name = "libgtk4"

    [[metadata.sources]]
    hash = "782d5951fbfd585fc9ec76c09d07e28e6014c72db001fb567fff217fb96e4d8c"
    type = "archive"
    unpack_target = ""
    url = "https://download.gnome.org/sources/gtk/4.6/gtk-4.6.0.tar.xz"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
