dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "XPA"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/xpa\nif [[ \"${target}\" == *-freebsd* ]]; then\n    export CFLAGS=-fPIC\nfi\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-shared=yes\nmake -j${nproc}\nif [[ ${target} == *mingw* ]]; then\n    make mingw-dll\n    mkdir -p ${libdir}\n    cp libxpa.dll ${libdir}/libxpa.dll\nfi\nmake install\n"""
version = "v2.1.21"

[[products]]
binnames = ["xpamb"]
type = "exe"
variable_name = "xpamb"
[[products]]
binnames = ["xpaget"]
type = "exe"
variable_name = "xpaget"
[[products]]
binnames = ["xpainfo"]
type = "exe"
variable_name = "xpainfo"
[[products]]
binnames = ["xpans"]
type = "exe"
variable_name = "xpans"
[[products]]
binnames = ["xpaset"]
type = "exe"
variable_name = "xpaset"
[[products]]
binnames = ["xpaaccess"]
type = "exe"
variable_name = "xpaaccess"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libxpa"]
type = "lib"
variable_name = "libxpa"

[[sources]]
hash = "923cc1bc7e761424b87049b1a20853eefe921388"
type = "git"
unpack_target = ""
url = "https://github.com/ericmandel/xpa.git"
