buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/050c0fad809d73e2de48f8c1c784df0fd2f3d0b2/C/CUDA/libNVVM/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.8"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libNVVM"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu-cuda_platform+jetson", "aarch64-linux-gnu-cuda_platform+sbsa", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/cuda_nvcc-*\ninstall_license LICENSE\n\nmkdir -p ${bindir} ${libdir} ${prefix}/include ${prefix}/share\nif [[ ${target} == *-linux-gnu ]]; then\n    mv nvvm/lib64/libnvvm.so* ${libdir}\nelif [[ ${target} == x86_64-w64-mingw32 ]]; then\n    mv nvvm/bin/nvvm64_*.dll ${bindir}\n    chmod +x ${bindir}/*.dll\nfi\nmv nvvm/include/* ${prefix}/include/\nmv nvvm/libdevice ${prefix}/share/\n"""
version = "v4.0.3"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libnvvm", "nvvm64_40_0"]
    type = "lib"
    variable_name = "libnvvm"

    [[metadata.sources]]
    hash = "68bf29e090b3e41c3711eee9892f1c0ba70b7829dd1df6601bc0f3d451aaaf5e"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-x86_64/cuda_nvcc-linux-x86_64-12.5.40-archive.tar.xz"
    [[metadata.sources]]
    hash = "2027c3988f9c39721c34a0273b37c4b492e8dd5da5e778a443b09bf2c8a4f55c"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-aarch64/cuda_nvcc-linux-aarch64-12.5.40-archive.tar.xz"
    [[metadata.sources]]
    hash = "28eb5da875c783e3c62c23c8949f02f632d3fa1567000045a18c6d83a5439cfc"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-sbsa/cuda_nvcc-linux-sbsa-12.5.40-archive.tar.xz"
    [[metadata.sources]]
    hash = "dedcf8b84b244932bc34c8d2372eddcacf8103e8f16d820df03ee2ed98b43ce6"
    type = "archive"
    unpack_target = ""
    url = "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/windows-x86_64/cuda_nvcc-windows-x86_64-12.5.40-archive.zip"
