augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Xorg_randrproto"
products = []
script = """cd $WORKSPACE/srcdir/randrproto-*/\n# When compiling for things like ppc64le, we need newer `config.sub` files\nupdate_configure_scripts\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-malloc0returnsnull=no\nmake -j${nproc}\nmake install\n"""
version = "v1.5.0"

[[sources]]
hash = "4c675533e79cd730997d232c8894b6692174dce58d3e207021b8f860be498468"
type = "archive"
unpack_target = ""
url = "https://www.x.org/archive/individual/proto/randrproto-1.5.0.tar.bz2"
