augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "HOHQMesh"
platforms = ["i686-linux-gnu-libgfortran3", "i686-linux-gnu-libgfortran4", "i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran3", "aarch64-linux-gnu-libgfortran4", "aarch64-linux-gnu-libgfortran5", "armv7l-linux-gnueabihf-libgfortran3", "armv7l-linux-gnueabihf-libgfortran4", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran3", "powerpc64le-linux-gnu-libgfortran4", "powerpc64le-linux-gnu-libgfortran5", "i686-linux-musl-libgfortran3", "i686-linux-musl-libgfortran4", "i686-linux-musl-libgfortran5", "x86_64-linux-musl-libgfortran3", "x86_64-linux-musl-libgfortran4", "x86_64-linux-musl-libgfortran5", "x86_64-apple-darwin-libgfortran3", "x86_64-apple-darwin-libgfortran4", "x86_64-apple-darwin-libgfortran5", "x86_64-unknown-freebsd-libgfortran3", "x86_64-unknown-freebsd-libgfortran4", "x86_64-unknown-freebsd-libgfortran5", "i686-w64-mingw32-libgfortran3", "i686-w64-mingw32-libgfortran4", "i686-w64-mingw32-libgfortran5", "x86_64-w64-mingw32-libgfortran3", "x86_64-w64-mingw32-libgfortran4", "x86_64-w64-mingw32-libgfortran5", "aarch64-apple-darwin-libgfortran5", "armv6l-linux-gnueabihf-libgfortran3", "armv6l-linux-gnueabihf-libgfortran4", "armv6l-linux-gnueabihf-libgfortran5"]
script = """cd $WORKSPACE/srcdir/HOHQMesh-*\n\n# Build HOHQMesh\nmake -j${nproc} F90=$FC\n\n# Copy executable to binary directory\nmkdir -p ${bindir}\nif [[ \"${bb_full_target}\" == *-w64-mingw32-libgfortran[34]* ]]; then\n  # For some reason, on i686 with libgfortran3 or libgfortran4,\n  # the executable is created without the `.exe` extension\n  cp HOHQMesh ${bindir}/HOHQMesh${exeext}\nelse\n  cp HOHQMesh${exeext} ${bindir}\nfi\n"""
version = "v1.4.0"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["HOHQMesh"]
type = "exe"
variable_name = "HOHQMesh"

[[sources]]
hash = "47015b2a58f41db84f86adfd0349a4f08949206eaa9b2a275e138e5fff219e5e"
type = "archive"
unpack_target = ""
url = "https://github.com/trixi-framework/HOHQMesh/releases/download/v1.4.0/HOHQMesh-v1.4.0.tar.gz"
