dependencies = []
init_block = """@static if VERSION < v\"1.7.0-DEV.641\"\n        ccall((:lbt_forward, libblastrampoline), Int32, (Cstring, Int32, Int32, Ptr{Cvoid}),\n              Libdl.dlpath(Base.libblas_name), 1, 0, C_NULL)\n    end\n"""
julia_compat = "1.6"
lazy_artifacts = false
name = "libblastrampoline"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libblastrampoline/src\n\nmake -j${nproc} prefix=${prefix} install\ninstall_license /usr/share/licenses/MIT\n"""
version = "v4.0.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libblastrampoline"]
type = "lib"
variable_name = "libblastrampoline"

[[sources]]
hash = "af89551c9a50d762f747dd822c0290164f9c7077"
type = "git"
unpack_target = ""
url = "https://github.com/JuliaLinearAlgebra/libblastrampoline.git"
