buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/fc468bb68d81aa24ad2ed0c816aac30d61f7588c/G/GstPluginsBase/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GstPluginsBase"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\nmeson --cross-file=${MESON_TARGET_TOOLCHAIN} --buildtype=release gst-plugins-base-*\nninja -j${nproc}\nninja install\ninstall_license gst-plugins-base-*/COPYING\n"""
version = "v1.20.3"

    [[metadata.dependencies]]
    compat = ""
    name = "Gettext_jll"
    platforms = ["any"]
    top_level = false
    type = "hostdependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.20.3"
    name = "GStreamer_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "aaaaf01e-2457-52c6-9fe8-886f7267d736"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "Opus_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "91d4177d-7536-5919-b921-800302f37372"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstpbtypes"]
    type = "lib"
    variable_name = "libgstpbtypes"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstoverlaycomposition"]
    type = "lib"
    variable_name = "libgstoverlaycomposition"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstaudiotestsrc"]
    type = "lib"
    variable_name = "libgstaudiotestsrc"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstaudiomixer"]
    type = "lib"
    variable_name = "libgstaudiomixer"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstadder"]
    type = "lib"
    variable_name = "libgstadder"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstvideorate"]
    type = "lib"
    variable_name = "libgstvideorate"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstvideoconvert"]
    type = "lib"
    variable_name = "libgstvideoconvert"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstopus"]
    type = "lib"
    variable_name = "libgstopus"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstrawparse"]
    type = "lib"
    variable_name = "libgstrawparse"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgsttcp"]
    type = "lib"
    variable_name = "libgsttcp"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstvolume"]
    type = "lib"
    variable_name = "libgstvolume"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstvideotestsrc"]
    type = "lib"
    variable_name = "libgstvideotestsrc"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgsttypefindfunctions"]
    type = "lib"
    variable_name = "libgsttypefindfunctions"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstencoding"]
    type = "lib"
    variable_name = "libgstencoding"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstcompositor"]
    type = "lib"
    variable_name = "libgstcompositor"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstaudiorate"]
    type = "lib"
    variable_name = "libgstaudiorate"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstsubparse"]
    type = "lib"
    variable_name = "libgstsubparse"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstaudioconvert"]
    type = "lib"
    variable_name = "libgstaudioconvert"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstplayback"]
    type = "lib"
    variable_name = "libgstplayback"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstgio"]
    type = "lib"
    variable_name = "libgstgio"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstvideoscale"]
    type = "lib"
    variable_name = "libgstvideoscale"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstaudioresample"]
    type = "lib"
    variable_name = "libgstaudioresample"
    [[metadata.products]]
    dir_paths = ["lib/gstreamer-1.0"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgstapp"]
    type = "lib"
    variable_name = "libgstapp"
    [[metadata.products]]
    binnames = ["gst-device-monitor-1.0"]
    type = "exe"
    variable_name = "gstdevicemonitor"
    [[metadata.products]]
    binnames = ["gst-play-1.0"]
    type = "exe"
    variable_name = "gstplay"
    [[metadata.products]]
    binnames = ["gst-discoverer-1.0"]
    type = "exe"
    variable_name = "gstdiscoverer"

    [[metadata.sources]]
    hash = "7e30b3dd81a70380ff7554f998471d6996ff76bbe6fc5447096f851e24473c9f"
    type = "archive"
    unpack_target = ""
    url = "https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.20.3.tar.xz"
