dependencies = ["Glib_jll", "XML2_jll"]
name = "SharedMimeInfo"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "arm-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "arm-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/shared-mime-info-*/\napk add intltool\n./configure --prefix=$prefix --host=$target\nmake -j${nproc}\nmake install\n"""
version = "v1.12.0"

[[products]]
dir_paths = []
dont_dlopen = false
libnames = ["libsharedmime"]
type = "lib"
variable_name = "libsharedmime"

[[sources]]
"https://gitlab.freedesktop.org/xdg/shared-mime-info/uploads/80c7f1afbcad2769f38aeb9ba6317a51/shared-mime-info-1.12.tar.xz" = "18b2f0fe07ed0d6f81951a5fd5ece44de9c8aeb4dc5bb20d4f595f6cc6bd403e"
