augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "mmtk_julia"
platforms = ["x86_64-linux-gnu"]
script = """cd $WORKSPACE/srcdir\ncd mmtk-julia/\nmake release\n\n# Install\ninstall -Dvm 755 \"mmtk/target/${rust_target}/release/libmmtk_julia.${dlext}\" -t \"${libdir}\"\ninstall -Dvm 644 \"mmtk/api/mmtk.h\" \"${includedir}/mmtk.h\"\ninstall -Dvm 644 \"mmtk/api/mmtkMutator.h\" \"${includedir}/mmtkMutator.h\"\n"""
version = "v0.30.2"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmmtk_julia"]
type = "lib"
variable_name = "libmmtk_julia"
[[products]]
paths = ["include/mmtk.h"]
type = "file"
variable_name = "mmtk_h"
[[products]]
paths = ["include/mmtkMutator.h"]
type = "file"
variable_name = "mmtkMutator_h"

[[sources]]
hash = "b69acf5af7a7dd97c1cc6fd99f7c2d51b477f214"
type = "git"
unpack_target = ""
url = "https://github.com/mmtk/mmtk-julia.git"
