augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Xorg_libpthread_stubs"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
products = []
script = """cd $WORKSPACE/srcdir/libpthread-stubs-*/\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v0.5.0"

[[sources]]
hash = "59da566decceba7c2a7970a4a03b48d9905f1262ff94410a649224e33d2442bc"
type = "archive"
unpack_target = ""
url = "https://www.x.org/archive/individual/lib/libpthread-stubs-0.5.tar.xz"
