buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/c9f2c4021660210c5450824f22dd85130ebd4571/S/stb/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.6"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.7"
lazy_artifacts = false
name = "stb"
products = []
script = """cd ${WORKSPACE}/srcdir/stb*/\nmkdir -p \"${includedir}\"\ncp -vr *.h \"${includedir}/.\"\n"""
version = "v0.0.20221025"

    [[metadata.sources]]
    hash = "93a16ee3e866e719feec459f6f132cce932c5ec751eb38e3ec1975f911353d2e"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/nothings/stb/archive/8b5f1f37b5b75829fc72d38e7b5d4bcbf8a26d55.zip"
