["0.1.4"]
artifact_urls = []
registered = 2019-09-23T10:30:53.000Z

["0.1.5"]
artifact_urls = []
registered = 2020-01-21T19:33:47.000Z

["0.1.6"]
artifact_urls = []
registered = 2020-01-29T21:09:35.000Z

["0.1.7"]
artifact_urls = []
registered = 2020-03-04T15:21:11.000Z

["0.1.8"]
artifact_urls = []
registered = 2020-03-23T22:21:19.000Z

["0.1.9"]
artifact_urls = []
registered = 2020-04-19T00:56:58.000Z

["0.1.10"]
artifact_urls = []
registered = 2020-05-19T16:21:24.000Z

["0.1.11"]
artifact_urls = []
registered = 2021-05-21T13:51:43.000Z

["0.1.12"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2021-08-11T21:04:57.000Z

["0.1.13"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2021-10-22T14:53:03.000Z

["0.1.14"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2021-11-05T20:31:51.000Z

["0.1.15"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2022-08-16T23:00:57.000Z

["0.2.0"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2024-03-27T22:45:31.000Z

["0.2.1"]
artifact_urls = ["https://github.com/gaelforget/nctiles-testcases/archive/refs/tags/v0.1.tar.gz"]
registered = 2024-05-04T18:33:44.000Z
