["25.18.33578+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/NEO_LTS_jll.jl/releases/download/NEO_LTS-v25.18.33578+0/NEO_LTS.v25.18.33578.x86_64-linux-gnu-cxx11-debug+false.tar.gz", "https://github.com/JuliaBinaryWrappers/NEO_LTS_jll.jl/releases/download/NEO_LTS-v25.18.33578+0/NEO_LTS.v25.18.33578.x86_64-linux-gnu-cxx11-debug+true.tar.gz"]
registered = 2026-05-04T21:18:22.000Z

    [["25.18.33578+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/NEO_LTS_jll.jl/releases/download/NEO_LTS-v25.18.33578+0/NEO_LTS.v25.18.33578.x86_64-linux-gnu-cxx11-debug+false.tar.gz", "https://github.com/JuliaBinaryWrappers/NEO_LTS_jll.jl/releases/download/NEO_LTS-v25.18.33578+0/NEO_LTS.v25.18.33578.x86_64-linux-gnu-cxx11-debug+true.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/2e2e9fd553d1960e04948188d0f56685d6592101/N/NEO/NEO@LTS/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/n/neo/neo@lts/build_tarballs.jl/2e2e9fd553d1960e04948188d0f56685d6592101.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["25.18.33578+0".artifact_metadata.sources]]
        hash = "9fe190adbbaf1765e83a8cb94e406c9266b80b25"
        type = "git"
        url = "https://github.com/intel/compute-runtime.git"

            ["25.18.33578+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/intel-compute-runtime"
            version = "25.18.33578.42"
        [["25.18.33578+0".artifact_metadata.sources]]
        type = "directory"
        url = "https://github.com/JuliaPackaging/Yggdrasil/tree/2e2e9fd553d1960e04948188d0f56685d6592101/N/NEO/NEO@LTS/bundled"
