["1.0.0"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-09-21T22:46:39.000Z

["1.1.2"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-09-22T20:32:10.000Z

["1.1.3"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-09-22T20:54:45.000Z

["1.1.4"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-09-25T18:18:20.000Z

["1.1.5"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-10-14T00:53:45.000Z

["1.1.6"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2024-10-14T04:06:03.000Z

["1.1.7"]
artifact_urls = ["https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"]
registered = 2025-08-19T04:04:01.000Z
