["3.11.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/nlohmann_json_jll.jl/releases/download/nlohmann_json-v3.11.3+0/nlohmann_json.v3.11.3.any.tar.gz"]
registered = 2024-03-22T22:59:52.000Z

["3.12.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/nlohmann_json_jll.jl/releases/download/nlohmann_json-v3.12.0+0/nlohmann_json.v3.12.0.any.tar.gz"]
registered = 2025-06-23T14:27:59.000Z
