init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "spectra"
products = []
script = """cd $WORKSPACE/srcdir/spectra-*\nmkdir build && cd build/\n\ncmake .. \\\n-DCMAKE_INSTALL_PREFIX=$prefix \\\n-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n-DCMAKE_BUILD_TYPE=Release\n\nmake -j${nproc}\nmake install\n"""
version = "v1.0.0"

[[dependencies]]
compat = ""
name = "Eigen_jll"
platforms = ["any"]
type = "builddependency"
uuid = "bc6bbf8a-a594-5541-9c57-10b0d0312c70"
version-major = 0
version-minor = 0
version-patch = 0

[[sources]]
hash = "45228b7d77b916b5384245eb13aa24bc994f3b0375013a8ba6b85adfd2dafd67"
type = "archive"
unpack_target = ""
url = "https://github.com/yixuan/spectra/archive/refs/tags/v1.0.0.tar.gz"
