buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/9760778c33270aee0c084c95de1951d352e0e1f6/F/FLEXPART/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.3"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "FLEXPART"
platforms = ["x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5"]
script = """cd flexpart\natomic_patch -p1 /workspace/srcdir/patches/flexpart-makefile.patch\natomic_patch -p1 /workspace/srcdir/patches/flexpart-parmod.patch\ncd src\nmake ncf=yes\ncp FLEXPART $bindir\ninstall_license ../LICENSE\n"""
version = "v10.4.0"

    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "eccodes_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "NetCDFF_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["FLEXPART"]
    type = "exe"
    variable_name = "FLEXPART"

    [[metadata.sources]]
    hash = "3d7eebf7c4909f59db5ec32c524f88fb846e9fe5"
    type = "git"
    unpack_target = ""
    url = "https://www.flexpart.eu/gitmob/flexpart"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
