augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Shaderc"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx03", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx03", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/shaderc*/\n./utils/git-sync-deps \nmkdir build && cd build\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DSHADERC_SKIP_TESTS=1 \\\n    -DSHADERC_SKIP_EXAMPLES=1 \\\n    -DSHADERC_SKIP_COPYRIGHT_CHECK=1 \\\n    -S .. \\\n    -B .\nmake -j${nproc}\nmake install\n"""
version = "v2022.1.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libshaderc_shared"]
type = "lib"
variable_name = "libshaderc_shared"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libSPIRV-Tools-shared"]
type = "lib"
variable_name = "libSPIRV_Tools_shared"
[[products]]
binnames = ["spirv-dis"]
type = "exe"
variable_name = "spirv_dis"
[[products]]
binnames = ["spirv-lint"]
type = "exe"
variable_name = "spirv_lint"
[[products]]
binnames = ["spirv-opt"]
type = "exe"
variable_name = "spirv_opt"
[[products]]
binnames = ["glslangValidator"]
type = "exe"
variable_name = "glslangValidator"
[[products]]
binnames = ["spirv-cfg"]
type = "exe"
variable_name = "spirv_cfg"
[[products]]
binnames = ["spirv-link"]
type = "exe"
variable_name = "spirv_link"
[[products]]
binnames = ["glslc"]
type = "exe"
variable_name = "glslc"
[[products]]
binnames = ["spirv-remap"]
type = "exe"
variable_name = "spirv_remap"
[[products]]
binnames = ["spirv-val"]
type = "exe"
variable_name = "spirv_val"
[[products]]
binnames = ["spirv-reduce"]
type = "exe"
variable_name = "spirv_reduce"
[[products]]
binnames = ["spirv-as"]
type = "exe"
variable_name = "spirv_as"

[[sources]]
hash = "e4722b0ad49ee60c143d43baae8390f75ba27d2d"
type = "git"
unpack_target = ""
url = "https://github.com/google/shaderc.git"
