dependencies = []
lazy_artifacts = false
name = "glmnet"
platforms = ["i686-linux-gnu-libgfortran3", "i686-linux-gnu-libgfortran4", "i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran3", "aarch64-linux-gnu-libgfortran4", "aarch64-linux-gnu-libgfortran5", "armv7l-linux-gnueabihf-libgfortran3", "armv7l-linux-gnueabihf-libgfortran4", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran3", "powerpc64le-linux-gnu-libgfortran4", "powerpc64le-linux-gnu-libgfortran5", "i686-linux-musl-libgfortran3", "i686-linux-musl-libgfortran4", "i686-linux-musl-libgfortran5", "x86_64-linux-musl-libgfortran3", "x86_64-linux-musl-libgfortran4", "x86_64-linux-musl-libgfortran5", "aarch64-linux-musl-libgfortran3", "aarch64-linux-musl-libgfortran4", "aarch64-linux-musl-libgfortran5", "armv7l-linux-musleabihf-libgfortran3", "armv7l-linux-musleabihf-libgfortran4", "armv7l-linux-musleabihf-libgfortran5", "x86_64-apple-darwin14-libgfortran3", "x86_64-apple-darwin14-libgfortran4", "x86_64-apple-darwin14-libgfortran5", "x86_64-unknown-freebsd11.1-libgfortran3", "x86_64-unknown-freebsd11.1-libgfortran4", "x86_64-unknown-freebsd11.1-libgfortran5", "i686-w64-mingw32-libgfortran3", "i686-w64-mingw32-libgfortran4", "i686-w64-mingw32-libgfortran5", "x86_64-w64-mingw32-libgfortran3", "x86_64-w64-mingw32-libgfortran4", "x86_64-w64-mingw32-libgfortran5"]
script = """cd $WORKSPACE/srcdir/GLMNet.jl/deps/\n\nflags=\"-fdefault-real-8 -ffixed-form -shared -O3\"\nif [[ ${target} != *mingw* ]]; then\n    flags=\"${flags} -fPIC\"\nfi\nif [[ ${target} != aarch64* ]] && [[ ${target} != arm* ]]; then\n    flags=\"${flags} -m${nbits}\"\nfi\n\n${FC} ${LDFLAGS} ${flags} glmnet5.f90 -o libglmnet.${dlext}\n\nmkdir -p $libdir\nmv libglmnet.${dlext} $libdir/\n"""
version = "v5.0.0"

[[products]]
dir_paths = []
dont_dlopen = false
libnames = ["libglmnet"]
type = "lib"
variable_name = "libglmnet"

[[sources]]
hash = "d8cab55556a8c184a879446476efcc35e68a3eee"
type = "git"
unpack_target = ""
url = "https://github.com/JuliaStats/GLMNet.jl.git"
