buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/24f76105f7db474fd2d90709220d7cae2f57ea5b/D/D3/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.0"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "D3"
script = """version=7.9.0\napk add --update nodejs npm\ncd ${prefix}\nnpm install d3@${version}\ninstall_license ${prefix}/node_modules/d3/LICENSE\n"""
sources = []
version = "v7.9.0"

    [[metadata.products]]
    paths = ["node_modules/d3/dist/d3.js"]
    type = "file"
    variable_name = "d3"
