init_block = ""
lazy_artifacts = false
name = "gdk_pixbuf"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/gdk-pixbuf-*/\nmkdir build && cd build\n\n# Get a local gettext for msgfmt cross-building\napk add gettext\n\nFLAGS=()\nif [[ \"${target}\" == *-apple-* ]] || [[ \"${target}\" == *-mingw* ]]; then\n    FLAGS+=(-Dx11=false)\nfi\n\nmeson .. \\\n    -Dgir=false \\\n    -Dman=false \\\n    -Dinstalled_tests=false \\\n    -Dgio_sniffing=false \\\n    \"${FLAGS[@]}\" \\\n    --cross-file=\"${MESON_TARGET_TOOLCHAIN}\"\nninja -j${nproc}\nninja install\n\n# Cleanup `loaders.cache` file, we're going to generate a new one on the user's machine\nrm -f ${prefix}/lib/gdk-pixbuf-2.0/2.10.0/loaders/loaders.cache\n"""
version = "v2.38.2"

[[dependencies]]
name = "Glib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "JpegTurbo_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "libpng_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Libtiff_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Xorg_libX11_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Xorg_xproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Xorg_kbproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libgdk_pixbuf-2", "libgdk_pixbuf-2.0"]
type = "lib"
variable_name = "libgdkpixbuf"
[[products]]
binnames = ["gdk-pixbuf-query-loaders"]
type = "exe"
variable_name = "gdk_pixbuf_query_loaders"
[[products]]
paths = ["lib/gdk-pixbuf-2.0/2.10.0/loaders"]
type = "file"
variable_name = "gdk_pixbuf_loaders_dir"

[[sources]]
hash = "9fad057e8c51bc4373948a02c8ee7d8afe254b361fb4abc43767fce43982dd25"
type = "archive"
unpack_target = ""
url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/3c7740498fd31b6746dd7e04601886766a6644b7/gdk-pixbuf-3c7740498fd31b6746dd7e04601886766a6644b7.tar.bz2"
