augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "gdk_pixbuf"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/gdk-pixbuf-*/\nmkdir build && cd build\n\n# As seen in the GTK4 build, llvm-ar seems to generate corrupted static archives:\n#\n#   [119/165] Linking target gdk-pixbuf/pixops/timescale\n#   ninja: job failed: [...]\n#   ld: warning: ignoring file gdk-pixbuf/pixops/libpixops.a, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x74 0x68 0x69 0x6E 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )\n#   Undefined symbols for architecture arm64:\n#     \"__pixops_composite\", referenced from:\n#         _main in timescale.c.o\n#     \"__pixops_composite_color\", referenced from:\n#         _main in timescale.c.o\n#     \"__pixops_scale\", referenced from:\n#         _main in timescale.c.o\n#   ld: symbol(s) not found for architecture arm64\n\nif [[ \"${target}\" == *apple* ]]; then\n    sed -i \"s?^ar = .*?ar = '/opt/${target}/bin/${target}-ar'?g\" \"${MESON_TARGET_TOOLCHAIN}\"\nfi\n\nFLAGS=()\nif [[ \"${target}\" == x86_64-linux-gnu ]]; then\n    FLAGS+=(-Dintrospection=enabled)\nfi\n\nmeson .. \\\n    -Dman=false \\\n    -Dinstalled_tests=false \\\n    -Dgio_sniffing=false \\\n    \"${FLAGS[@]}\" \\\n    --cross-file=\"${MESON_TARGET_TOOLCHAIN}\"\nninja -j${nproc}\nninja install\n\n# Cleanup `loaders.cache` file, we're going to generate a new one on the user's machine\nfind ${prefix}/lib -name loaders.cache -delete\n"""
version = "v2.42.8"

[[dependencies]]
compat = ""
name = "Gettext_jll"
platforms = ["any"]
type = "hostdependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Glib_jll"
platforms = ["any"]
type = "hostdependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "2.68.3"
name = "Glib_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "JpegTurbo_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "libpng_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "4.3.0"
name = "Libtiff_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libX11_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xproto_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_kbproto_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "gobject_introspection_jll"
platforms = ["x86_64-linux-gnu"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libgdk_pixbuf-2", "libgdk_pixbuf-2.0"]
type = "lib"
variable_name = "libgdkpixbuf"
[[products]]
binnames = ["gdk-pixbuf-query-loaders"]
type = "exe"
variable_name = "gdk_pixbuf_query_loaders"
[[products]]
paths = ["lib/gdk-pixbuf-2.0/2.10.0/loaders"]
type = "file"
variable_name = "gdk_pixbuf_loaders_dir"

[[sources]]
hash = "d122cb5d0ef32349c52c37f1dfd936c734886643b49a37706acccfe3af6aba77"
type = "archive"
unpack_target = ""
url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/2.42.8/gdk-pixbuf-2.42.8.tar.bz2"
