buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/0748bf9c6eabeb56571fc24c1bf55d72206427dc/S/Sundials/Sundials@7/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.6.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Sundials"
platforms = ["i686-linux-gnu-libgfortran3", "i686-linux-gnu-libgfortran4", "i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran3", "x86_64-linux-gnu-libgfortran4", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran3", "aarch64-linux-gnu-libgfortran4", "aarch64-linux-gnu-libgfortran5", "armv6l-linux-gnueabihf-libgfortran3", "armv6l-linux-gnueabihf-libgfortran4", "armv6l-linux-gnueabihf-libgfortran5", "armv7l-linux-gnueabihf-libgfortran3", "armv7l-linux-gnueabihf-libgfortran4", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran5", "riscv64-linux-gnu-libgfortran5", "i686-linux-musl-libgfortran3", "i686-linux-musl-libgfortran4", "i686-linux-musl-libgfortran5", "x86_64-linux-musl-libgfortran3", "x86_64-linux-musl-libgfortran4", "x86_64-linux-musl-libgfortran5", "aarch64-linux-musl-libgfortran3", "aarch64-linux-musl-libgfortran4", "aarch64-linux-musl-libgfortran5", "armv6l-linux-musleabihf-libgfortran3", "armv6l-linux-musleabihf-libgfortran4", "armv6l-linux-musleabihf-libgfortran5", "armv7l-linux-musleabihf-libgfortran3", "armv7l-linux-musleabihf-libgfortran4", "armv7l-linux-musleabihf-libgfortran5", "x86_64-apple-darwin-libgfortran3", "x86_64-apple-darwin-libgfortran4", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5", "x86_64-unknown-freebsd-libgfortran3", "x86_64-unknown-freebsd-libgfortran4", "x86_64-unknown-freebsd-libgfortran5", "aarch64-unknown-freebsd-libgfortran5", "i686-w64-mingw32-libgfortran3", "i686-w64-mingw32-libgfortran4", "i686-w64-mingw32-libgfortran5", "x86_64-w64-mingw32-libgfortran3", "x86_64-w64-mingw32-libgfortran4", "x86_64-w64-mingw32-libgfortran5"]
script = """apk del cmake\n\ncd $WORKSPACE/srcdir/sundials*/cmake/tpl\nif [[ \"${target}\" == *-mingw* ]]; then\n    # Work around https://github.com/LLNL/sundials/issues/29\n    # When looking for KLU libraries, CMake searches only for import libraries,\n    # this patch ensures we look also for shared libraries.\n    atomic_patch -p3 $WORKSPACE/srcdir/patches/Sundials_findklu_suffixes.patch\nfi\n\n# Build\ncd $WORKSPACE/srcdir/sundials*\nmkdir build && cd build\n\nCMAKE_FLAGS=(-DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=\"${CMAKE_TARGET_TOOLCHAIN}\" -DEXAMPLES_ENABLE_C=OFF -DENABLE_KLU=ON -DKLU_INCLUDE_DIR=\"${includedir}/suitesparse\" -DKLU_LIBRARY_DIR=\"${libdir}\" -DKLU_WORKS=ON -DENABLE_LAPACK=ON -DLAPACK_WORKS=ON -DBLA_VENDOR=\"OpenBLAS\")\n    cmake \"${CMAKE_FLAGS[@]}\" ..\n    cmake --build . --parallel ${nproc}\n    cmake --install .\n"""
version = "v7.4.1"

    [[metadata.dependencies]]
    compat = ""
    name = "CMake_jll"
    platforms = ["any"]
    top_level = false
    type = "hostdependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "OpenBLAS32_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "SuiteSparse32_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_arkode"]
    type = "lib"
    variable_name = "libsundials_arkode"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_cvode"]
    type = "lib"
    variable_name = "libsundials_cvode"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_cvodes"]
    type = "lib"
    variable_name = "libsundials_cvodes"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_ida"]
    type = "lib"
    variable_name = "libsundials_ida"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_idas"]
    type = "lib"
    variable_name = "libsundials_idas"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_kinsol"]
    type = "lib"
    variable_name = "libsundials_kinsol"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_nvecmanyvector"]
    type = "lib"
    variable_name = "libsundials_nvecmanyvector"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_nvecserial"]
    type = "lib"
    variable_name = "libsundials_nvecserial"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolband"]
    type = "lib"
    variable_name = "libsundials_sunlinsolband"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsoldense"]
    type = "lib"
    variable_name = "libsundials_sunlinsoldense"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolklu"]
    type = "lib"
    variable_name = "libsundials_sunlinsolklu"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsollapackband"]
    type = "lib"
    variable_name = "libsundials_sunlinsollapackband"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsollapackdense"]
    type = "lib"
    variable_name = "libsundials_sunlinsollapackdense"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolpcg"]
    type = "lib"
    variable_name = "libsundials_sunlinsolpcg"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolspbcgs"]
    type = "lib"
    variable_name = "libsundials_sunlinsolspbcgs"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolspfgmr"]
    type = "lib"
    variable_name = "libsundials_sunlinsolspfgmr"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolspgmr"]
    type = "lib"
    variable_name = "libsundials_sunlinsolspgmr"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunlinsolsptfqmr"]
    type = "lib"
    variable_name = "libsundials_sunlinsolsptfqmr"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunmatrixband"]
    type = "lib"
    variable_name = "libsundials_sunmatrixband"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunmatrixdense"]
    type = "lib"
    variable_name = "libsundials_sunmatrixdense"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunmatrixsparse"]
    type = "lib"
    variable_name = "libsundials_sunmatrixsparse"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunnonlinsolfixedpoint"]
    type = "lib"
    variable_name = "libsundials_sunnonlinsolfixedpoint"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_sunnonlinsolnewton"]
    type = "lib"
    variable_name = "libsundials_sunnonlinsolnewton"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libsundials_core"]
    type = "lib"
    variable_name = "libsundials_core"

    [[metadata.sources]]
    hash = "8e17876d3b4d682b4098684b07a85b005a122f81"
    type = "git"
    unpack_target = ""
    url = "https://github.com/LLNL/sundials.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
