augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "ReferenceBLAS"
platforms = ["i686-linux-gnu-libgfortran5", "x86_64-linux-gnu-libgfortran5", "aarch64-linux-gnu-libgfortran5", "armv6l-linux-gnueabihf-libgfortran5", "armv7l-linux-gnueabihf-libgfortran5", "powerpc64le-linux-gnu-libgfortran5", "riscv64-linux-gnu-libgfortran5", "i686-linux-musl-libgfortran5", "x86_64-linux-musl-libgfortran5", "aarch64-linux-musl-libgfortran5", "armv6l-linux-musleabihf-libgfortran5", "armv7l-linux-musleabihf-libgfortran5", "x86_64-apple-darwin-libgfortran5", "aarch64-apple-darwin-libgfortran5", "x86_64-unknown-freebsd-libgfortran5", "aarch64-unknown-freebsd-libgfortran5", "i686-w64-mingw32-libgfortran5", "x86_64-w64-mingw32-libgfortran5"]
script = """BLAS32=false\ncd $WORKSPACE/srcdir/lapack*\n\nif [[ ${nbits} == 64 ]] && [[ \"${BLAS32}\" != \"true\" ]]; then\n  INDEX64=\"ON\"\nelse\n  INDEX64=\"OFF\"\nfi\n\n# Remove the stop command from the xerbla function to prevent\n# us from exiting Julia on bad arguments\nsed -i '/^[ \\t]*STOP/d' SRC/xerbla.f\n\n# FortranCInterface_VERIFY fails on macOS, but it's not actually needed for the current build\nsed -i 's/FortranCInterface_VERIFY/# FortranCInterface_VERIFY/g' ./CBLAS/CMakeLists.txt\nsed -i 's/FortranCInterface_VERIFY/# FortranCInterface_VERIFY/g' ./LAPACKE/include/CMakeLists.txt\n\n# Use -fno-optimize-sibling-calls to guard against issues with Fortran ABI with character arguments\n# Discussed in https://github.com/JuliaLang/LinearAlgebra.jl/issues/650\nmkdir build && cd build\ncmake .. \\\n   -DCMAKE_INSTALL_PREFIX=\"$prefix\" \\\n   -DCMAKE_FIND_ROOT_PATH=\"$prefix\" \\\n   -DCMAKE_TOOLCHAIN_FILE=\"${CMAKE_TARGET_TOOLCHAIN}\" \\\n   -DCMAKE_Fortran_FLAGS=\"-fno-optimize-sibling-calls\" \\\n   -DCMAKE_BUILD_TYPE=Release \\\n   -DBUILD_SHARED_LIBS=ON \\\n   -DTEST_FORTRAN_COMPILER=OFF \\\n   -DBUILD_INDEX64_EXT_API=${INDEX64}\n\nmake -j${nproc}\nmake install\nif [[ ${target} == *mingw* ]]; then\n  rm ${prefix}/lib/liblapack.dll.a\nfi\nrm ${libdir}/liblapack.*\ninstall_license $WORKSPACE/srcdir/lapack/LICENSE\n\nif [[ \"${BLAS32}\" == \"true\" ]]; then\n    mv -v ${libdir}/libblas.${dlext} ${libdir}/libblas32.${dlext}\n    # If there were links that are now broken, fix them up\n    for l in $(find ${prefix}/lib -xtype l); do\n      if [[ $(basename $(readlink ${l})) == libblas ]]; then\n        ln -vsf libblas32.${dlext} ${l}\n      fi\n    done\n    PATCHELF_FLAGS=()\n    # ppc64le and aarch64 have 64 kB page sizes, don't muck up the ELF section load alignment\n    if [[ ${target} == aarch64-* || ${target} == powerpc64le-* ]]; then\n      PATCHELF_FLAGS+=(--page-size 65536)\n    fi\n    if [[ ${target} == *linux* ]] || [[ ${target} == *freebsd* ]]; then\n      patchelf ${PATCHELF_FLAGS[@]} --set-soname libblas32.${dlext} ${libdir}/libblas32.${dlext}\n    elif [[ ${target} == *apple* ]]; then\n      install_name_tool -id libblas32.${dlext} ${libdir}/libblas32.${dlext}\n    fi\nfi\n"""
version = "v3.12.1"

[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libblas"]
type = "lib"
variable_name = "libblas"

[[sources]]
hash = "6ec7f2bc4ecf4c4a93496aa2fa519575bc0e39ca"
type = "git"
unpack_target = ""
url = "https://github.com/Reference-LAPACK/lapack"
