dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libaio"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd libaio\n\nmake -j${nproc} install prefix=${prefix}\n"""
version = "v0.3.112"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libaio"]
type = "lib"
variable_name = "libaio"

[[sources]]
hash = "d025927efa75a0d1b46ca3a5ef331caa2f46ee0e"
type = "git"
unpack_target = ""
url = "https://pagure.io/libaio.git"
