augment_platform_block = ""
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "adwaita_icon_theme"
script = """cd $WORKSPACE/srcdir/adwaita-icon-theme-*/\n\n# Install native gtk+3.0 so that we get `gtk-encode-symbolic-svg`\napk add gtk+3.0 librsvg\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v43.0.0"

[[dependencies]]
compat = ""
name = "hicolor_icon_theme_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["share/icons"]
type = "file"
variable_name = "adwaita_icons_dir"

[[sources]]
hash = "2e3ac77d32a6aa5554155df37e8f0a0dd54fc5a65fd721e88d505f970da32ec6"
type = "archive"
unpack_target = ""
url = "https://download.gnome.org/sources/adwaita-icon-theme/43/adwaita-icon-theme-43.tar.xz"
