augment_platform_block = ""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = false
name = "SuiteSparse"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/SuiteSparse\n\n# Needs cmake >= 3.22 provided by jll\napk del cmake\n\n# Disable OpenMP as it will probably interfere with blas threads and Julia threads\nFLAGS+=(INSTALL=\"${prefix}\" INSTALL_LIB=\"${libdir}\" INSTALL_INCLUDE=\"${prefix}/include\" CFOPENMP=)\n\nif [[ \"${target}\" == *-mingw* ]]; then\n    BLAS_NAME=blastrampoline-5\nelse\n    BLAS_NAME=blastrampoline\nfi\n\nif [[ ${bb_full_target} == *-sanitize+memory* ]]; then\n    # Install msan runtime (for clang)\n    cp -rL ${libdir}/linux/* /opt/x86_64-linux-musl/lib/clang/*/lib/linux/\nfi\n\nif [[ ${nbits} == 64 ]]; then\n    CMAKE_OPTIONS=(\n        -DBLAS64_SUFFIX=\"_64\"\n        -DALLOW_64BIT_BLAS=YES\n    )\nelse\n    CMAKE_OPTIONS=(\n        -DALLOW_64BIT_BLAS=NO\n    )\nfi\n\nfor proj in SuiteSparse_config AMD BTF CAMD CCOLAMD COLAMD CHOLMOD LDL KLU UMFPACK RBio SPQR; do\n    cd ${proj}/build\n    cmake .. -DCMAKE_BUILD_TYPE=Release \\\n             -DCMAKE_INSTALL_PREFIX=${prefix} \\\n             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n             -DENABLE_CUDA=0 \\\n             -DNFORTRAN=1 \\\n             -DNOPENMP=1 \\\n             -DNPARTITION=0 \\\n             -DNSTATIC=1 \\\n             -DBLAS_FOUND=1 \\\n             -DBLAS_LIBRARIES=\"${libdir}/lib${BLAS_NAME}.${dlext}\" \\\n             -DBLAS_LINKER_FLAGS=\"${BLAS_NAME}\" \\\n             -DBLAS_UNDERSCORE=ON \\\n             -DBLA_VENDOR=\"${BLAS_NAME}\" \\\n             -DLAPACK_FOUND=1 \\\n             -DLAPACK_LIBRARIES=\"${libdir}/lib${BLAS_NAME}.${dlext}\" \\\n             -DLAPACK_LINKER_FLAGS=\"${BLAS_NAME}\" \\\n             \"${CMAKE_OPTIONS[@]}\"\n    make -j${nproc}\n    make install\n    cd ../..\ndone\n\n# For now, we'll have to adjust the name of the Lbt library on macOS and FreeBSD.\n# Eventually, this should be fixed upstream\nif [[ ${target} == *-apple-* ]] || [[ ${target} == *freebsd* ]]; then\n    echo \"-- Modifying library name for libblastrampoline\"\n\n    for nm in libcholmod libspqr libumfpack; do\n        # Figure out what version it probably latched on to:\n        if [[ ${target} == *-apple-* ]]; then\n            LBT_LINK=$(otool -L ${libdir}/${nm}.dylib | grep lib${BLAS_NAME} | awk '{ print $1 }')\n            install_name_tool -change ${LBT_LINK} @rpath/lib${BLAS_NAME}.dylib ${libdir}/${nm}.dylib\n        elif [[ ${target} == *freebsd* ]]; then\n            LBT_LINK=$(readelf -d ${libdir}/${nm}.so | grep lib${BLAS_NAME} | sed -e 's/.*\\[\\(.*\\)\\].*/\\1/')\n            patchelf --replace-needed ${LBT_LINK} lib${BLAS_NAME}.so ${libdir}/${nm}.so\n        fi\n    done\nfi\n\n# Delete the extra soversion libraries built. https://github.com/JuliaPackaging/Yggdrasil/issues/7\nif [[ \"${target}\" == *-mingw* ]]; then\n    rm -f ${libdir}/lib*.*.${dlext}\n    rm -f ${libdir}/lib*.*.*.${dlext}\nfi\n\ninstall_license LICENSE.txt\n"""
version = "v7.2.1"

[[dependencies]]
compat = "5.8.0"
name = "libblastrampoline_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LLVMCompilerRT_jll"
platforms = ["x86_64-linux-gnu-sanitize+memory"]
top_level = false
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CMake_jll"
platforms = ["any"]
top_level = false
type = "hostdependency"
version-major = 3
version-minor = 24
version-patch = 3

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libsuitesparseconfig"]
type = "lib"
variable_name = "libsuitesparseconfig"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libamd"]
type = "lib"
variable_name = "libamd"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libbtf"]
type = "lib"
variable_name = "libbtf"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcamd"]
type = "lib"
variable_name = "libcamd"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libccolamd"]
type = "lib"
variable_name = "libccolamd"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcolamd"]
type = "lib"
variable_name = "libcolamd"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcholmod"]
type = "lib"
variable_name = "libcholmod"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libldl"]
type = "lib"
variable_name = "libldl"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libklu"]
type = "lib"
variable_name = "libklu"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libumfpack"]
type = "lib"
variable_name = "libumfpack"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["librbio"]
type = "lib"
variable_name = "librbio"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libspqr"]
type = "lib"
variable_name = "libspqr"

[[sources]]
hash = "d6c84f7416eaee0d23d61c6c49ad1b73235d2ea2"
type = "git"
unpack_target = ""
url = "https://github.com/DrTimothyAldenDavis/SuiteSparse.git"
