init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "czmq"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/czmq\nsh autogen.sh\n\n# Hint to find libstc++, required to link against C++ libs when using C compiler\nif [[ \"${target}\" == *-linux-* ]]; then\n    if [[ \"${nbits}\" == 32 ]]; then\n        export CFLAGS=\"-Wl,-rpath-link,/opt/${target}/${target}/lib\"\n    else\n        export CFLAGS=\"-Wl,-rpath-link,/opt/${target}/${target}/lib64\"\n    fi\nfi\n\natomic_patch -p1 ../patches/ntohll.patch\n\n./configure --prefix=$prefix \\\n    --host=${target} \\\n    --enable-drafts \\\n    --disable-static \\\n    CXXFLAGS=\"-O2 -fms-extensions\"\nmake -j${nproc}\nmake install\n"""
version = "v4.2.1"

[[dependencies]]
name = "ZeroMQ_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libczmq"]
type = "lib"
variable_name = "libczmq"

[[sources]]
hash = "4a50c2153586cf510d6cc3fcfbb9f5ea2e02c419"
type = "git"
unpack_target = ""
url = "https://github.com/zeromq/czmq.git"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
