["2.11.29+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/libigc_LTS_jll.jl/releases/download/libigc_LTS-v2.11.29+0/libigc_LTS.v2.11.29.x86_64-linux-gnu-cxx11-debug+false.tar.gz", "https://github.com/JuliaBinaryWrappers/libigc_LTS_jll.jl/releases/download/libigc_LTS-v2.11.29+0/libigc_LTS.v2.11.29.x86_64-linux-gnu-cxx11-debug+true.tar.gz"]
registered = 2026-05-04T15:32:39.000Z

    [["2.11.29+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/libigc_LTS_jll.jl/releases/download/libigc_LTS-v2.11.29+0/libigc_LTS.v2.11.29.x86_64-linux-gnu-cxx11-debug+false.tar.gz", "https://github.com/JuliaBinaryWrappers/libigc_LTS_jll.jl/releases/download/libigc_LTS-v2.11.29+0/libigc_LTS.v2.11.29.x86_64-linux-gnu-cxx11-debug+true.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e4ad2559d72b2bb3113607ddcc460f73805ad56b/L/libigc/libigc@LTS/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/l/libigc/libigc@lts/build_tarballs.jl/e4ad2559d72b2bb3113607ddcc460f73805ad56b.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["2.11.29+0".artifact_metadata.sources]]
        hash = "9e4e2b37d637805c037c59be23335b9ea5833fc1"
        type = "git"
        url = "https://github.com/intel/intel-graphics-compiler.git"

            ["2.11.29+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/intel-graphics-compiler"
            version = "2.11.29"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "58242977b4092cf5eb94a10dd144691c12c87001"
        type = "git"
        url = "https://github.com/intel/opencl-clang.git"

            ["2.11.29+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/opencl-clang"
            version = "15.0.1"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "2d4f2e7a7968392de017fcd3e4b503a75f0c12d2"
        type = "git"
        url = "https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git"

            ["2.11.29+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/spirv-llvm-translator"
            version = "15.0.11"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "f289d047f49fb60488301ec62bafab85573668cc"
        type = "git"
        url = "https://github.com/KhronosGroup/SPIRV-Tools.git"

            ["2.11.29+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/spirv-tools"
            version = "2025.1"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "0e710677989b4326ac974fd80c5308191ed80965"
        type = "git"
        url = "https://github.com/KhronosGroup/SPIRV-Headers.git"

            ["2.11.29+0".artifact_metadata.sources.upstream]
            project = "repology.org/project/spirv-headers"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "9d255266e1df8f1dc5d11e1fbb03213acfaa4fc7"
        type = "git"
        url = "https://github.com/intel/vc-intrinsics.git"
        [["2.11.29+0".artifact_metadata.sources]]
        hash = "8dfdcc7b7bf66834a761bd8de445840ef68e4d1a"
        type = "git"
        url = "https://github.com/llvm/llvm-project.git"
        [["2.11.29+0".artifact_metadata.sources]]
        type = "directory"
        url = "https://github.com/JuliaPackaging/Yggdrasil/tree/e4ad2559d72b2bb3113607ddcc460f73805ad56b/L/libigc/libigc@LTS/bundled"
