["0.1.0"]
artifact_urls = []
registered = 2025-07-13T17:51:55.000Z

["0.1.1"]
artifact_urls = []
registered = 2025-07-14T19:07:14.000Z

["1.0.0"]
artifact_urls = ["https://github.com/krishnaveti/LlamaCppOutlines.jl/releases/download/v1.0.0/LlamaCppOutlines.v1.0.0.x86_64-w64-mingw32-cuda+12.9.tar.gz", "https://github.com/krishnaveti/LlamaCppOutlines.jl/releases/download/v1.0.0/LlamaCppOutlines.v1.0.0.x86_64-w64-mingw32.tar.gz"]
registered = 2025-07-20T19:19:04.000Z
