["1.18.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.arm-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.arm-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+0/Wayland_protocols.v1.18.0.x86_64-linux-musl.tar.gz"]
registered = 2019-09-29T20:03:59.000Z

["1.18.0+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.arm-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.arm-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+1/Wayland_protocols.v1.18.0.x86_64-linux-musl.tar.gz"]
registered = 2019-10-24T21:14:13.000Z

["1.18.0+2"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+2/Wayland_protocols.v1.18.0.any.tar.gz"]
registered = 2020-08-14T09:54:45.000Z

    [["1.18.0+2".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+2/Wayland_protocols.v1.18.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3e498fceda4e4f00a4864c56f3a96216868e807c/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/3e498fceda4e4f00a4864c56f3a96216868e807c.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["1.18.0+3"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+3/Wayland_protocols.v1.18.0.any.tar.gz"]
registered = 2020-08-26T17:34:54.000Z

    [["1.18.0+3".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+3/Wayland_protocols.v1.18.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/815de56a4440f4e05333c5295d74f1dc9b73ebe3/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/815de56a4440f4e05333c5295d74f1dc9b73ebe3.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["1.18.0+4"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+3/Wayland_protocols.v1.18.0.any.tar.gz"]
registered = 2020-10-17T01:58:17.000Z

    [["1.18.0+4".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+3/Wayland_protocols.v1.18.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/815de56a4440f4e05333c5295d74f1dc9b73ebe3/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/815de56a4440f4e05333c5295d74f1dc9b73ebe3.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["1.23.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.23.0+0/Wayland_protocols.v1.23.0.any.tar.gz"]
registered = 2021-11-21T19:56:22.000Z

    [["1.23.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.23.0+0/Wayland_protocols.v1.23.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/544776ae3285058dc34398d133a7078f150dba44/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/544776ae3285058dc34398d133a7078f150dba44.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.4.2"

["1.24.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.24.0+0/Wayland_protocols.v1.24.0.any.tar.gz"]
registered = 2022-02-23T18:26:43.000Z

    [["1.24.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.24.0+0/Wayland_protocols.v1.24.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/b2ba30d92a351f84deb239e915093b4d029625fb/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/b2ba30d92a351f84deb239e915093b4d029625fb.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.2"

["1.25.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.25.0+0/Wayland_protocols.v1.25.0.any.tar.gz"]
registered = 2022-02-23T19:09:15.000Z

    [["1.25.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.25.0+0/Wayland_protocols.v1.25.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/fcf41ad49508261d48048a5fddd2c6ff758494e1/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/fcf41ad49508261d48048a5fddd2c6ff758494e1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.2"

["1.31.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.31.0+0/Wayland_protocols.v1.31.0.any.tar.gz"]
registered = 2024-01-01T23:12:58.000Z

    [["1.31.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.31.0+0/Wayland_protocols.v1.31.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/fbd66688f6324ce128a42409b1532bfcb0cbb48d/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/fbd66688f6324ce128a42409b1532bfcb0cbb48d.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.7"

["1.36.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.36.0+0/Wayland_protocols.v1.36.0.any.tar.gz"]
registered = 2024-12-24T15:11:37.000Z

    [["1.36.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.36.0+0/Wayland_protocols.v1.36.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d11f78c091946a1021d80ac80b2c50c7dbe3ef8f/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/d11f78c091946a1021d80ac80b2c50c7dbe3ef8f.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.2"

["1.44.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.44.0+0/Wayland_protocols.v1.44.0.any.tar.gz"]
registered = 2025-06-11T22:08:53.000Z

    [["1.44.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.44.0+0/Wayland_protocols.v1.44.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/aafdf9f0f1f7c8a9a39a498b9589d64af383c3d1/W/Wayland_protocols/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/w/wayland_protocols/build_tarballs.jl/aafdf9f0f1f7c8a9a39a498b9589d64af383c3d1.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"
