buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/843f0e9b1b466247914010181c47b03fa067bc4a/N/Nettle/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.0"

[metadata]
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Nettle"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/nettle-*/\natomic_patch -p1 ../patches/alloca.patch\n\n# Force c99 mode\nexport CFLAGS=\"${CFLAGS} -std=c99\"\n\nupdate_configure_scripts\n./configure --prefix=$prefix --host=$target --with-include-path=$prefix/include\nmake -j${nproc}\nmake install\ninstall_license COPYING*\n"""
version = "v3.4.1"

    [[metadata.dependencies]]
    name = "GMP_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libnettle"]
    type = "lib"
    variable_name = "libnettle"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libhogweed"]
    type = "lib"
    variable_name = "libhogweed"
    [[metadata.products]]
    binnames = ["nettle-hash"]
    type = "exe"
    variable_name = "nettle_hash"

    [[metadata.sources]]
    hash = "f941cf1535cd5d1819be5ccae5babef01f6db611f9b5a777bae9c7604b8a92ad"
    type = "archive"
    unpack_target = ""
    url = "https://ftp.gnu.org/gnu/nettle/nettle-3.4.1.tar.gz"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
