dependencies = []
lazy_artifacts = false
name = "EarCut"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/EarCutBuilder/\nmkdir \"${libdir}\"\n${CXX} -std=c++11 -fPIC -shared -o \"${libdir}/libearcut.${dlext}\" cwrapper.cpp\n"""
version = "v2.1.5"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libearcut"]
type = "lib"
variable_name = "libearcut"

[[sources]]
hash = "cfa4233e26ac785a89954a72b4e2e84312b389c2"
type = "git"
unpack_target = ""
url = "https://github.com/SimonDanisch/EarCutBuilder.git"
