["1.2.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/vtzero_jll.jl/releases/download/vtzero-v1.2.0+0/vtzero.v1.2.0.any.tar.gz"]
registered = 2026-06-05T20:48:02.000Z

    [["1.2.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/vtzero_jll.jl/releases/download/vtzero-v1.2.0+0/vtzero.v1.2.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/032efc0c606bfda6612a1977408179baa62c8338/V/vtzero/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/v/vtzero/build_tarballs.jl/032efc0c606bfda6612a1977408179baa62c8338.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.6"

        [["1.2.0+0".artifact_metadata.sources]]
        hash = "c86e378d466950337f203e2dd5ee6aa743cabb3c"
        type = "git"
        url = "https://github.com/mapbox/vtzero.git"
