["1.2.151+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.2.151+0/Vulkan_Headers.v1.2.151.any.tar.gz"]
registered = 2020-09-02T12:46:43.000Z

["1.2.177+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.2.177+0/Vulkan_Headers.v1.2.177.any.tar.gz"]
registered = 2021-04-28T15:44:03.000Z

    [["1.2.177+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.2.177+0/Vulkan_Headers.v1.2.177.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/bf12d214a4ac313d1df10e7a4c00b91a2ded194a/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.2"

        ["1.2.177+0".artifact_metadata.metadata]
        dependencies = []
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.2.177"

            [["1.2.177+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"

            [["1.2.177+0".artifact_metadata.metadata.sources]]
            hash = "3f437c4a94ae35af1eb93700d073e9d0e7adab3d"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.3.207+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.207+0/Vulkan_Headers.v1.3.207.any.tar.gz"]
registered = 2022-03-09T11:16:12.000Z

    [["1.3.207+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.207+0/Vulkan_Headers.v1.3.207.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/e68393138c458b9d7c41a6cba2a313d3d9bbb486/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.2"

        ["1.3.207+0".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.3.207"

            [["1.3.207+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"

            [["1.3.207+0".artifact_metadata.metadata.sources]]
            hash = "2c45218b9008dd80f6004b419777758e6459ac16"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.3.240+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.240+0/Vulkan_Headers.v1.3.240.any.tar.gz"]
registered = 2023-02-10T13:43:43.000Z

    [["1.3.240+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.240+0/Vulkan_Headers.v1.3.240.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/48c788415cfcc90e7b146bc0bcc141e0f810e28a/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        ["1.3.240+0".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.3.240"

            [["1.3.240+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"

            [["1.3.240+0".artifact_metadata.metadata.sources]]
            hash = "9f93cbe76abe9f6cb4a36df10b08fa3b78ae0027"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.3.243+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.243+0/Vulkan_Headers.v1.3.243.any.tar.gz"]
registered = 2023-05-12T11:45:18.000Z

    [["1.3.243+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.243+0/Vulkan_Headers.v1.3.243.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3744cc0a137bd2fca1f18975433a1ec36f7c20da/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        ["1.3.243+0".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.3.243"

            [["1.3.243+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"

            [["1.3.243+0".artifact_metadata.metadata.sources]]
            hash = "65ad768d8603671fc1085fe115019e72a595ced8"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.3.243+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.243+1/Vulkan_Headers.v1.3.243.any.tar.gz"]
registered = 2023-07-28T20:02:46.000Z

    [["1.3.243+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.243+1/Vulkan_Headers.v1.3.243.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/8b73afd27270912b7fc2bf4a657ab25c248e0808/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        ["1.3.243+1".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """cd Vulkan-Headers\ninstall_license LICENSE.txt\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.3.243"

            [["1.3.243+1".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"
            [["1.3.243+1".artifact_metadata.metadata.products]]
            paths = ["include/vulkan/vulkan.hpp"]
            type = "file"
            variable_name = "vulkan_hpp"

            [["1.3.243+1".artifact_metadata.metadata.sources]]
            hash = "65ad768d8603671fc1085fe115019e72a595ced8"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.4.312+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.4.312+0/Vulkan_Headers.v1.4.312.any.tar.gz"]
registered = 2025-04-18T19:57:38.000Z

    [["1.4.312+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.4.312+0/Vulkan_Headers.v1.4.312.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/c3c3e7f9c5ea84f1849d68489d5a98ef201b82e2/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        ["1.4.312+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """apk del cmake\n\ncd Vulkan-Headers\ninstall_license LICENSE.md\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.4.312"

            [["1.4.312+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "CMake_jll"
            platforms = ["any"]
            top_level = false
            type = "hostdependency"
            version-major = 3
            version-minor = 31
            version-patch = 6

            [["1.4.312+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"
            [["1.4.312+0".artifact_metadata.metadata.products]]
            paths = ["include/vulkan/vulkan.hpp"]
            type = "file"
            variable_name = "vulkan_hpp"

            [["1.4.312+0".artifact_metadata.metadata.sources]]
            hash = "5ceb9ed481e58e705d0d9b5326537daedd06b97d"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"

["1.4.321+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.4.321+0/Vulkan_Headers.v1.4.321.any.tar.gz"]
registered = 2025-07-06T14:51:03.000Z

    [["1.4.321+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.4.321+0/Vulkan_Headers.v1.4.321.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/dc8b7100333602798e97f2194903790b4cd213bc/V/Vulkan_Headers/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.4"

        ["1.4.321+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.0"
        lazy_artifacts = false
        name = "Vulkan_Headers"
        script = """apk del cmake\n\ncd Vulkan-Headers\ninstall_license LICENSE.md\n\nCMAKE_FLAGS=()\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_PREFIX=${prefix})\n\n# Install things into $prefix\nCMAKE_FLAGS+=(-DCMAKE_INSTALL_LIBDIR=${libdir})\n\ncmake -B build -S . -GNinja ${CMAKE_FLAGS[@]}\nninja -C build -j ${nproc} install\n"""
        version = "v1.4.321"

            [["1.4.321+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "CMake_jll"
            platforms = ["any"]
            top_level = false
            type = "hostdependency"
            version-major = 3
            version-minor = 31
            version-patch = 6

            [["1.4.321+0".artifact_metadata.metadata.products]]
            paths = ["share/vulkan/registry/vk.xml"]
            type = "file"
            variable_name = "vk_xml"
            [["1.4.321+0".artifact_metadata.metadata.products]]
            paths = ["include/vulkan/vulkan.hpp"]
            type = "file"
            variable_name = "vulkan_hpp"

            [["1.4.321+0".artifact_metadata.metadata.sources]]
            hash = "2cd90f9d20df57eac214c148f3aed885372ddcfe"
            type = "git"
            unpack_target = ""
            url = "https://github.com/KhronosGroup/Vulkan-Headers.git"
