augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Clingo"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/clingo\n\n# Upstreamed at https://github.com/potassco/clingo/pull/654\natomic_patch -p1 ../patches/0001-Use-lowercase-windows-h.patch\n\nmkdir build && cd build\ncmake -DCMAKE_INSTALL_PREFIX=$prefix \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    ..\nmake -j${nproc}\nmake install\n"""
toplevel_block = ""
version = "v5.8.2"

[[products]]
binnames = ["lpconvert"]
type = "exe"
variable_name = "lpconvert"
[[products]]
binnames = ["clingo"]
type = "exe"
variable_name = "clingo"
[[products]]
binnames = ["gringo"]
type = "exe"
variable_name = "gringo"
[[products]]
binnames = ["reify"]
type = "exe"
variable_name = "reify"
[[products]]
binnames = ["clasp"]
type = "exe"
variable_name = "clasp"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libclingo"]
type = "lib"
variable_name = "libclingo"

[[sources]]
hash = "a99ffb2a58293c68b28fcc283a1d1c9ccad900fe"
type = "git"
unpack_target = ""
url = "https://github.com/potassco/clingo.git"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
