buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/59a590c9d4ddab2c61bc554f95df9136095f84a2/C/Chafa/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.2.4"

[metadata]
lazy_artifacts = false
name = "Chafa"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1"]
script = """cd ${WORKSPACE}/srcdir/chafa-*/\n\nif [[ \"${target}\" == *darwin* ]]; then\n    # For some reason building with Clang for macOS doesn't work\n    export CC=gcc\nfi\nif [[ \"${proc_family}\" == intel ]]; then\n    BUILTIN_FUNCS=yes\nelse\n    BUILTIN_FUNCS=no\nfi\n./autogen.sh \\\n    --prefix=${prefix} \\\n    --build=${MACHTYPE} \\\n    --host=${target} \\\n    ax_cv_gcc_check_x86_cpu_init=\"${BUILTIN_FUNCS}\" \\\n    ax_cv_gcc_check_x86_cpu_supports=\"${BUILTIN_FUNCS}\"\nmake -j${nproc}\nmake install\n"""
version = "v1.4.1"

    [[metadata.dependencies]]
    name = "FreeType2_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "Glib_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "ImageMagick_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libchafa"]
    type = "lib"
    variable_name = "libchafa"
    [[metadata.products]]
    binnames = ["chafa"]
    type = "exe"
    variable_name = "chafa"

    [[metadata.sources]]
    hash = "46d34034f4c96d120e0639f87a26590427cc29e95fe5489e903a48ec96402ba3"
    type = "archive"
    unpack_target = ""
    url = "https://hpjansson.org/chafa/releases/chafa-1.4.1.tar.xz"
