init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "qwtw"
platforms = ["x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11"]
script = """apk add g++\ncd $WORKSPACE/srcdir\ncd qwtw\nmkdir build\ncd build\ncmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release ../.\nmake -j${nproc}\nmake install\n"""
version = "v2.0.5"

[[dependencies]]
name = "Libglvnd_jll"
type = "dependency"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "boost_jll"
type = "dependency"
uuid = "28df3c45-c428-5900-9ff8-a3135698ca75"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "Qt_jll"
type = "dependency"
uuid = "ede63266-ebff-546c-83e0-1c6fb6d0efc8"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "qwt_jll"
type = "dependency"
uuid = "ed0789fa-10db-50b3-94da-03266d70be0f"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "CompilerSupportLibraries_jll"
type = "dependency"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "FreeType2_jll"
type = "dependency"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libqwtw"]
type = "lib"
variable_name = "qwtw"
[[products]]
binnames = ["qwproc"]
type = "exe"
variable_name = "qwproc"
[[products]]
binnames = ["qttest"]
type = "exe"
variable_name = "qttest"

[[sources]]
hash = "b1aab8873cfb38abc9e35d1dd9ffb8c9497eb80b"
type = "git"
unpack_target = ""
url = "https://github.com/ig-or/qwtw.git"
