["0.1.0+0"]
artifact_metadata = "cmt_jll/cmt-v0.1.0+0"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/cmt_jll.jl/releases/download/cmt-v0.1.0+0/cmt.v0.1.0.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/cmt_jll.jl/releases/download/cmt-v0.1.0+0/cmt.v0.1.0.x86_64-apple-darwin.tar.gz"]
registered = 2022-06-21T11:43:27.000Z

["0.2.0+0"]
artifact_metadata = "cmt_jll/cmt-v0.2.0+0"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/cmt_jll.jl/releases/download/cmt-v0.2.0+0/cmt.v0.2.0.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/cmt_jll.jl/releases/download/cmt-v0.2.0+0/cmt.v0.2.0.x86_64-apple-darwin.tar.gz"]
registered = 2023-03-03T11:15:57.000Z
