["8.1.0+0"]
artifact_metadata = "CUDNN_CUDA112_jll/CUDNN_CUDA112-v8.1.0+0"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.x86_64-w64-mingw32.tar.gz"]
registered = 2021-02-02T10:33:48.000Z
