["1.1.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.1.0+0/CUTENSOR_CUDA110.v1.1.0.x86_64-linux-gnu.tar.gz"]
registered = 2020-07-10T12:57:13.000Z

    [["1.1.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.1.0+0/CUTENSOR_CUDA110.v1.1.0.x86_64-linux-gnu.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d114ec384eb08f36ef1b4c73746a1950e5775119/./C/CUTENSOR/CUTENSOR_CUDA110/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/./c/cutensor/cutensor_cuda110/build_tarballs.jl/d114ec384eb08f36ef1b4c73746a1950e5775119.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["1.2.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-w64-mingw32.tar.gz"]
registered = 2020-07-27T10:46:11.000Z

    [["1.2.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-w64-mingw32.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/8b672eaab69e0bfcd98c9eb59858567603e9a1ab/./C/CUTENSOR/CUTENSOR_CUDA110/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/./c/cutensor/cutensor_cuda110/build_tarballs.jl/8b672eaab69e0bfcd98c9eb59858567603e9a1ab.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.5"

["1.2.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-w64-mingw32.tar.gz"]
registered = 2020-10-23T09:29:24.000Z

    [["1.2.1+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-w64-mingw32.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/43ebe0f45eb4c88adbb10cfdb3e00c072deaf223/./C/CUTENSOR/CUTENSOR_CUDA110/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/./c/cutensor/cutensor_cuda110/build_tarballs.jl/43ebe0f45eb4c88adbb10cfdb3e00c072deaf223.toml"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.0"

["1.2.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-w64-mingw32.tar.gz"]
registered = 2021-02-10T22:22:55.000Z

    [["1.2.2+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-w64-mingw32.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/fc3bcbf1bf170609b311843b57b9c39fcad8aa1f/C/CUTENSOR/CUTENSOR_CUDA110/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/c/cutensor/cutensor_cuda110/build_tarballs.jl/fc3bcbf1bf170609b311843b57b9c39fcad8aa1f.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.3.0"
