["1.1.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.1.0+0/CUTENSOR_CUDA110.v1.1.0.x86_64-linux-gnu.tar.gz"]
registered = 2020-07-10T12:57:13.000Z

["1.2.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-w64-mingw32.tar.gz"]
registered = 2020-07-27T10:46:11.000Z

["1.2.1+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-w64-mingw32.tar.gz"]
registered = 2020-10-23T09:29:24.000Z

["1.2.2+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-w64-mingw32.tar.gz"]
registered = 2021-02-10T22:22:55.000Z
