augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "algoim"
products = []
script = """cd ${WORKSPACE}/srcdir/algoim\ninstall_license LICENSE\nmkdir -p \"${includedir}\"\ncp -vr algoim \"${includedir}/.\"\n"""
version = "v0.1.0"

[[sources]]
hash = "979cb3b7860b53751291352a929754d525b7fde1"
type = "git"
unpack_target = ""
url = "https://github.com/algoim/algoim.git"
