augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libcap"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/libcap-*/\n\nmake -j${nproc} BUILD_CC=${BUILD_CC} COPTS=\"-O2 -std=c99\"\nmake install DESTDIR=${prefix} prefix=/ lib=lib\n"""
version = "v2.51.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcap"]
type = "lib"
variable_name = "libcap"
[[products]]
paths = ["include/sys/capability.h"]
type = "file"
variable_name = "capability_h"

[[sources]]
hash = "f146cf1fa282483673df969b76ccd392697b903ac27ab7924c0fda103f5a0d26"
type = "archive"
unpack_target = ""
url = "https://mirrors.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.51.tar.gz"
