augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libcap"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/libcap-*/\n\nmake -j${nproc}\nmake install DESTDIR=${prefix} prefix=/ lib=lib\n"""
version = "v2.76.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libcap"]
type = "lib"
variable_name = "libcap"
[[products]]
paths = ["include/sys/capability.h"]
type = "file"
variable_name = "capability_h"

[[sources]]
hash = "629da4ab29900d0f7fcc36227073743119925fd711c99a1689bbf5c9b40c8e6f"
type = "archive"
unpack_target = ""
url = "https://mirrors.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.76.tar.xz"
