buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ee0ef62b2873a69126f8635c7d7c821f55f48565/P/Prjtrellis/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.4.0"

[metadata]
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Prjtrellis"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx11"]
script = """cd prjtrellis/libtrellis\nmkdir build && cd build\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    ..\nmake -j${nproc}\nmake install\n"""
version = "v0.1.0"

    [[metadata.dependencies]]
    compat = "~3.8.1"
    name = "Python_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "=1.76.0"
    name = "boost_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    binnames = ["ecpunpack"]
    type = "exe"
    variable_name = "ecpunpack"
    [[metadata.products]]
    binnames = ["ecppll"]
    type = "exe"
    variable_name = "ecppll"
    [[metadata.products]]
    binnames = ["ecpbram"]
    type = "exe"
    variable_name = "ecpbram"
    [[metadata.products]]
    binnames = ["ecppack"]
    type = "exe"
    variable_name = "ecppack"
    [[metadata.products]]
    binnames = ["ecpmulti"]
    type = "exe"
    variable_name = "ecpmulti"
    [[metadata.products]]
    binnames = ["ecpmulti"]
    type = "exe"
    variable_name = "ecpmulti"
    [[metadata.products]]
    dir_paths = ["lib/trellis", "lib64/trellis"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libtrellis"]
    type = "lib"
    variable_name = "libtrellis"
    [[metadata.products]]
    dir_paths = ["lib/trellis", "lib64/trellis"]
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["pytrellis"]
    type = "lib"
    variable_name = "pytrellis"

    [[metadata.sources]]
    hash = "dff1cbcb1bd30de7e96f8a059f2e19be1bb2e44d"
    type = "git"
    unpack_target = ""
    url = "https://github.com/YosysHQ/prjtrellis.git"
