dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Deno"
platforms = ["x86_64-linux-gnu", "x86_64-apple-darwin", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/\ninstall_license deno/LICENSE.md\nmkdir \"${bindir}\"\ninstall -m 755 \"${target}/deno${exeext}\" \"${bindir}\"\n"""
version = "v1.11.4"

[[products]]
binnames = ["deno"]
type = "exe"
variable_name = "deno"

[[sources]]
hash = "277fc71be8ecd04b9ae9e4867291b2765ad2f1a2983e94221594a59672e0c5ec"
type = "archive"
unpack_target = "x86_64-linux-gnu"
url = "https://github.com/denoland/deno/releases/download/v1.11.4/deno-x86_64-unknown-linux-gnu.zip"
[[sources]]
hash = "e46fb730cff11e2adb77e94cf2e83e4c9a491ef49a5396f512327afef99c1217"
type = "archive"
unpack_target = "x86_64-apple-darwin14"
url = "https://github.com/denoland/deno/releases/download/v1.11.4/deno-x86_64-apple-darwin.zip"
[[sources]]
hash = "b8bfa173e31ee120e7afb180580f9c80fe20d46cc24eeb3455b8b62f982fd408"
type = "archive"
unpack_target = "x86_64-w64-mingw32"
url = "https://github.com/denoland/deno/releases/download/v1.11.4/deno-x86_64-pc-windows-msvc.zip"
[[sources]]
hash = "f760a9fdc61ab2aed904015e8393d625f4d387f04279ae93a3966dbd12f1a8fe"
type = "archive"
unpack_target = ""
url = "https://github.com/denoland/deno/releases/download/v1.11.4/deno_src.tar.gz"
