dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Deno"
platforms = ["x86_64-linux-gnu", "x86_64-apple-darwin", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/\ninstall_license deno/LICENSE.md\nmkdir \"${bindir}\"\ninstall -m 755 \"${target}/deno${exeext}\" \"${bindir}\"\n"""
version = "v1.15.2"

[[products]]
binnames = ["deno"]
type = "exe"
variable_name = "deno"

[[sources]]
hash = "dd64ab38c5d0a70f83ad63c0297c8cdbb4ac667d43eb6e48731dce5bd4635bfd"
type = "archive"
unpack_target = "x86_64-linux-gnu"
url = "https://github.com/denoland/deno/releases/download/v1.15.2/deno-x86_64-unknown-linux-gnu.zip"
[[sources]]
hash = "7eead3d9ecebd08048657805028d744ae87a2d341f18f4c2db76213dead0931d"
type = "archive"
unpack_target = "x86_64-apple-darwin14"
url = "https://github.com/denoland/deno/releases/download/v1.15.2/deno-x86_64-apple-darwin.zip"
[[sources]]
hash = "f28e5fb999aeb48ae18f4d81d08414ad2b6879378c7f2c6a2181db1e40675f64"
type = "archive"
unpack_target = "x86_64-w64-mingw32"
url = "https://github.com/denoland/deno/releases/download/v1.15.2/deno-x86_64-pc-windows-msvc.zip"
[[sources]]
hash = "16862a52a7c359e001b69c1252cb7fc37fdccb956350fb211956f59dab489b3b"
type = "archive"
unpack_target = ""
url = "https://github.com/denoland/deno/releases/download/v1.15.2/deno_src.tar.gz"
