buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d22a3fb026e68965f007138bca07d43d79b209ef/E/Elfutils/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.2.4"

[metadata]
lazy_artifacts = false
name = "Elfutils"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu"]
script = """cd $WORKSPACE/srcdir/elfutils-*/\nexport CC=gcc\nexport CXX=g++\nCFLAGS=\"-Wno-error=unused-result\" CPPFLAGS=\"-I${prefix}/include\" ./configure --prefix=${prefix} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v0.177.0"

    [[metadata.dependencies]]
    name = "Zlib_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "Bzip2_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "XZ_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libasm"]
    type = "lib"
    variable_name = "libasm"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libdw"]
    type = "lib"
    variable_name = "libdw"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libelf"]
    type = "lib"
    variable_name = "libelf"

    [[metadata.sources]]
    hash = "fa489deccbcae7d8c920f60d85906124c1989c591196d90e0fd668e3dc05042e"
    type = "archive"
    unpack_target = ""
    url = "https://sourceware.org/elfutils/ftp/0.177/elfutils-0.177.tar.bz2"
