augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GAP_pkg_json"
platforms = ["x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
script = """# HACK WORKAROUND GAP_jll deficiencies\n# TODO: tweak for mac build\nif [[ \"${target}\" == *darwin* ]]; then\n  cp gac-darwin ${prefix}/share/gap/gac\nelse\n  cp gac ${prefix}/share/gap/gac\nfi\nchmod a+x ${prefix}/share/gap/gac\ncp sysinfo.gap ${prefix}/share/gap/\n\n# ensure #including src/compiled.h or src/profile.h from GAP_jll works\nln -s . ${prefix}/include/gap/src\ncd json*\n./configure ${prefix}/share/gap\nmake -j${nproc}\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license LICENSE\nrm -rf ${prefix}/include\nrm -rf ${prefix}/share/gap\n"""
version = "v200.0.201"

[[dependencies]]
compat = "~400.1192.0"
name = "GAP_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "~400.1192.0"
name = "GAP_lib_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["lib/gap/json.so"]
type = "file"
variable_name = "json"

[[sources]]
follow_symlinks = false
path = "../bundled"
target = ""
type = "directory"
[[sources]]
hash = "da69122fc99c412ebeca0635439a74498797834696c54e1b27efebe921b6a66a"
type = "archive"
unpack_target = ""
url = "https://github.com/gap-packages/json/releases/download/v2.0.2/json-2.0.2.tar.gz"
