buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f99f62061e9add8e288fca35673f267318d470df/M/Musl/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.3"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Musl"
platforms = ["i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf"]
script = """cd ${WORKSPACE}/srcdir/musl-*\natomic_patch -p1 ../patches/qsort_r.patch\n\nmkdir ${WORKSPACE}/srcdir/musl_build\ncd ${WORKSPACE}/srcdir/musl_build\nmusl_arch()\n{\n    case \"${target}\" in\n        i686*)\n            echo i386 ;;\n        arm*)\n            echo armhf ;;\n        *)\n            echo ${target%%-*} ;;\n    esac\n}\n\nexport LDFLAGS=\"${LDFLAGS} -Wl,-soname,libc.musl-$(musl_arch).so.1\"\n${WORKSPACE}/srcdir/musl-*/configure --prefix=/usr \\\n    --build=${MACHTYPE} \\\n    --host=${target} \\\n    --disable-multilib \\\n    --disable-werror \\\n    --enable-optimize \\\n    --enable-debug\n\nmake -j${nproc}\n\n# Install to fake directory\nmake install DESTDIR=${WORKSPACE}/srcdir/musl_deploy\n\n# In reality, all we want is what we need to run Musl programs, so\n# we just copy the dynamic loader directly over.\nmkdir -p ${prefix}/lib\nloader=$(echo ${WORKSPACE}/srcdir/musl_deploy/lib/*.so*)\nmv ${WORKSPACE}/srcdir/musl_deploy/usr/lib/libc.so ${prefix}/lib/$(basename \"${loader}\")\n\ninstall_license ${WORKSPACE}/srcdir/musl-*/COPYRIGHT\n"""
version = "v1.2.2"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = true
    libnames = ["ld-musl-x86_64", "ld-musl-i386", "ld-musl-armhf", "ld-musl-aarch64"]
    type = "lib"
    variable_name = "libc"

    [[metadata.sources]]
    hash = "9b969322012d796dc23dda27a35866034fa67d8fb67e0e2c45c913c3d43219dd"
    type = "archive"
    unpack_target = ""
    url = "https://www.musl-libc.org/releases/musl-1.2.2.tar.gz"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
