augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "libpng"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/libpng-*/\nmkdir build && cd build\nif [[ \"${target}\" == aarch64-apple-darwin* ]]; then\n    # Let CMake know this platform supports NEON extension\n    FLAGS=(-DPNG_ARM_NEON=on)\nfi\ncmake -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=\"${CMAKE_TARGET_TOOLCHAIN}\" \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DPNG_STATIC=OFF \\\n    \"${FLAGS[@]}\" \\\n    ..\nmake -j${nproc}\nmake install\n"""
version = "v1.6.40"

[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpng16"]
type = "lib"
variable_name = "libpng"

[[sources]]
hash = "8f720b363aa08683c9bf2a563236f45313af2c55d542b5481ae17dd8d183bb42"
type = "archive"
unpack_target = ""
url = "https://sourceforge.net/projects/libpng/files/libpng16/1.6.40/libpng-1.6.40.tar.gz"
