["2.3.3+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.arm-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.arm-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+0/Xorg_libXft.v2.3.3.x86_64-unknown-freebsd11.1.tar.gz"]
registered = 2019-10-22T23:56:21.000Z

["2.3.3+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-unknown-freebsd11.1.tar.gz"]
registered = 2020-04-04T05:46:38.000Z

    [["2.3.3+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.3+1/Xorg_libXft.v2.3.3.x86_64-unknown-freebsd11.1.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d22a3fb026e68965f007138bca07d43d79b209ef/X/Xorg_libXft/build_tarballs.jl"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.2.4"

        ["2.3.3+1".artifact_metadata.metadata]
        lazy_artifacts = false
        name = "Xorg_libXft"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd11.1"]
        script = """cd $WORKSPACE/srcdir/libXft-*/\nCPPFLAGS=\"-I${prefix}/include\"\n# When compiling for things like ppc64le, we need newer `config.sub` files\nupdate_configure_scripts\n./configure --prefix=${prefix} --host=${target} --enable-malloc0returnsnull=no\nmake -j${nproc}\nmake install\n"""
        version = "v2.3.3"

            [["2.3.3+1".artifact_metadata.metadata.dependencies]]
            name = "Xorg_kbproto_jll"
            type = "builddependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.3+1".artifact_metadata.metadata.dependencies]]
            name = "Fontconfig_jll"
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.3+1".artifact_metadata.metadata.dependencies]]
            name = "Xorg_libXrender_jll"
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["2.3.3+1".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libXft"]
            type = "lib"
            variable_name = "libXft"

            [["2.3.3+1".artifact_metadata.metadata.sources]]
            hash = "225c68e616dd29dbb27809e45e9eadf18e4d74c50be43020ef20015274529216"
            type = "archive"
            unpack_target = ""
            url = "https://www.x.org/archive/individual/lib/libXft-2.3.3.tar.bz2"

["2.3.9+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-unknown-freebsd.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv6l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv6l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.riscv64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-unknown-freebsd.tar.gz"]
registered = 2025-08-31T09:17:52.000Z

    [["2.3.9+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.aarch64-unknown-freebsd.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv6l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv6l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.riscv64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Xorg_libXft_jll.jl/releases/download/Xorg_libXft-v2.3.9+0/Xorg_libXft.v2.3.9.x86_64-unknown-freebsd.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/ad17d4dc8cd05d479dd4924b666b7853dc8dbc82/X/Xorg_libXft/build_tarballs.jl"
    metadata_source = "retrospective (by timestamp)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.6.5"

        ["2.3.9+0".artifact_metadata.metadata]
        augment_platform_block = ""
        init_block = ""
        julia_compat = "1.6"
        lazy_artifacts = false
        name = "Xorg_libXft"
        platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
        script = """cd $WORKSPACE/srcdir/libXft-*\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --enable-static=no\nmake -j${nproc}\nmake install\n"""
        version = "v2.3.9"

            [["2.3.9+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Xorg_kbproto_jll"
            platforms = ["any"]
            top_level = false
            type = "builddependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.9+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Xorg_renderproto_jll"
            platforms = ["any"]
            top_level = false
            type = "builddependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.9+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Xorg_xproto_jll"
            platforms = ["any"]
            top_level = false
            type = "builddependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.9+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Fontconfig_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0
            [["2.3.9+0".artifact_metadata.metadata.dependencies]]
            compat = ""
            name = "Xorg_libXrender_jll"
            platforms = ["any"]
            top_level = false
            type = "dependency"
            version-major = 0
            version-minor = 0
            version-patch = 0

            [["2.3.9+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libXft"]
            type = "lib"
            variable_name = "libXft"

            [["2.3.9+0".artifact_metadata.metadata.sources]]
            hash = "60a25b78945ed6932635b3bb1899a517d31df7456e69867ffba27f89ff3976f5"
            type = "archive"
            unpack_target = ""
            url = "https://www.x.org/archive/individual/lib/libXft-2.3.9.tar.xz"
