["13.0.0+0"]
artifact_metadata = "artifact_metadata/x/xsimd_jll/xsimd-v13.0.0+0.toml"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/xsimd_jll.jl/releases/download/xsimd-v13.0.0+0/xsimd.v13.0.0.any.tar.gz"]
registered = 2024-05-16T19:59:54.000Z

["13.0.0+1"]
artifact_metadata = "artifact_metadata/x/xsimd_jll/xsimd-v13.0.0+1.toml"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/xsimd_jll.jl/releases/download/xsimd-v13.0.0+1/xsimd.v13.0.0.any.tar.gz"]
registered = 2024-05-27T12:37:36.000Z
