["0.13.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_io_jll.jl/releases/download/xtensor_io-v0.13.0+0/xtensor_io.v0.13.0.any.tar.gz"]
registered = 2024-05-23T14:02:17.000Z

    [["0.13.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_io_jll.jl/releases/download/xtensor_io-v0.13.0+0/xtensor_io.v0.13.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/1629364f7b482f706f8826203a168d9e5f28bb8b/X/xtensor_io/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/x/xtensor_io/build_tarballs.jl/1629364f7b482f706f8826203a168d9e5f28bb8b.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.8"
