["0.25.0+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_jll.jl/releases/download/xtensor-v0.25.0+0/xtensor.v0.25.0.any.tar.gz"]
registered = 2024-05-16T20:00:07.000Z

    [["0.25.0+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_jll.jl/releases/download/xtensor-v0.25.0+0/xtensor.v0.25.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/4d176fa53068420f06ec8fb06c0c1029e8f892a6/X/xtensor/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/x/xtensor/build_tarballs.jl/4d176fa53068420f06ec8fb06c0c1029e8f892a6.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.8"

        [["0.25.0+0".artifact_metadata.sources]]
        hash = "3634f2ded19e0cf38208c8b86cea9e1d7c8e397d"
        type = "git"
        url = "https://github.com/xtensor-stack/xtensor"
        [["0.25.0+0".artifact_metadata.sources]]
        package = "xtl_jll"
        type = "builddependency"

["0.25.0+1"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_jll.jl/releases/download/xtensor-v0.25.0+1/xtensor.v0.25.0.any.tar.gz"]
registered = 2024-05-27T12:37:49.000Z

    [["0.25.0+1".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/xtensor_jll.jl/releases/download/xtensor-v0.25.0+1/xtensor.v0.25.0.any.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/7c979d3101976a916f3e4fad0516daccb20da5cf/X/xtensor/build_tarballs.jl"
    metadata = "reconstructed_artifact_metadata/Yggdrasil/x/xtensor/build_tarballs.jl/7c979d3101976a916f3e4fad0516daccb20da5cf.toml"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.8"

        [["0.25.0+1".artifact_metadata.sources]]
        hash = "3634f2ded19e0cf38208c8b86cea9e1d7c8e397d"
        type = "git"
        url = "https://github.com/xtensor-stack/xtensor"
