buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/066716570b474332d9ee90ac22d9d1f0d0787811/A/ATK/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.3.2"

[metadata]
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "ATK"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/atk-*/\nmkdir build && cd build\n\n# Get a local gettext for msgfmt cross-building\napk add gettext\n\nmeson .. -Dintrospection=false --cross-file=\"${MESON_TARGET_TOOLCHAIN}\"\nninja -j${nproc}\nninja install\n"""
version = "v2.36.0"

    [[metadata.dependencies]]
    compat = ""
    name = "Glib_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libatk-1", "libatk-1.0"]
    type = "lib"
    variable_name = "libatk"

    [[metadata.sources]]
    hash = "395894d43f0628497f919dff1b769f5482af99a8991127277e365f9374f46d57"
    type = "archive"
    unpack_target = ""
    url = "https://gitlab.gnome.org/GNOME/atk/-/archive/ATK_2_36_0/atk-ATK_2_36_0.tar.bz2"
