augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "HelloWorldOCaml"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-w64-mingw32"]
script = """mkdir -p ${bindir}\necho 'let () = print_endline \"hello world\"' > hello.ml\nocamlopt -o ${bindir}/hello_world${exeext} hello.ml\ninstall_license /usr/share/licenses/MIT\n"""
sources = []
version = "v1.0.0"

[[products]]
binnames = ["hello_world"]
type = "exe"
variable_name = "hello_world"
