buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/bfa9d531a29a49cb73f17a64242318255ca6cc47/Q/Qt5Svg/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.3"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Qt5Svg"
platforms = ["aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-unknown-freebsd", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin"]
script = """cd $WORKSPACE/srcdir\nmkdir build\ncd build/\n\nqtsrcdir=`ls -d ../qtsvg-*`\n\nqmake $qtsrcdir\nmake -j${nproc}\n\n# It appends the root path here with the qmake dir, which is /workspace/artifacts/blah...\nmake INSTALL_ROOT=$PWD/dummyroot install\nrsync -ua dummyroot/workspace/*/artifacts/*/* $prefix\n\nsed -i \"s?^prefix=.*?prefix=$prefix?\" $prefix/lib/pkgconfig/Qt5Svg.pc\n\ninstall_license $qtsrcdir/LICENSE.LGPL3\n"""
version = "v5.15.3"

    [[metadata.dependencies]]
    compat = ""
    name = "Qt5Base_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["Qt5Svg", "libQt5Svg", "QtSvg"]
    type = "lib"
    variable_name = "libqt5svg"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["QtSvg"]
    type = "framework"
    variable_name = "libqt5svg"

    [[metadata.sources]]
    hash = "3adc41dfcc67bbe3b8ff553bdac30ee75e270745536a58e54cdb741fa0505d89"
    type = "archive"
    unpack_target = ""
    url = "https://download.qt.io/official_releases/qt/5.15/5.15.3/submodules/qtsvg-everywhere-opensource-src-5.15.3.tar.xz"
