buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/6f7e798349aa8f5fbc05226cfdf01848849f67dd/X/Xorg_xkeyboard_config/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.2.5"

[metadata]
init_block = ""
lazy_artifacts = false
name = "Xorg_xkeyboard_config"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd11.1"]
products = []
script = """cd $WORKSPACE/srcdir/xkeyboard-config-*\napk add libxslt\n./configure --prefix=${prefix} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v2.27.0"

    [[metadata.dependencies]]
    name = "Xorg_xproto_jll"
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "Xorg_kbproto_jll"
    type = "builddependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    name = "Xorg_xkbcomp_jll"
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.sources]]
    hash = "690daec8fea63526c07620c90e6f3f10aae34e94b6db6e30906173480721901f"
    type = "archive"
    unpack_target = ""
    url = "https://www.x.org/archive/individual/data/xkeyboard-config/xkeyboard-config-2.27.tar.bz2"
