augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "ROOT_julia"
platforms = ["x86_64-linux-gnu-julia_version+1.10.0", "x86_64-linux-gnu-julia_version+1.11.1", "x86_64-linux-gnu-julia_version+1.12.0"]
script = """cat > \"$WORKSPACE/recipe.sh\" <<END_OF_SCRIPT\n\necho \"USE_CCACHE: $USE_CCACHE\"\n\ncd \"$WORKSPACE/srcdir/ROOT.jl/deps\"\n\nmake -j `nproc` LDLIBS=\"-lcxxwrap_julia -lcxxwrap_julia_stl\" LDFLAGS=\"-rdynamic\" CXXFLAGS+=\"-I $WORKSPACE/destdir/include/julia -std=c++17 -fPIC\"\n\ncp -a build/libroot_julia.so \"$prefix/lib/\"\n\ninstall_license $WORKSPACE/srcdir/ROOT.jl/LICENSE\n\nEND_OF_SCRIPT\nchmod a+x \"$WORKSPACE/recipe.sh\"\n\necho \"USE_CCACHE: $USE_CCACHE\"\n\ncd \"$WORKSPACE/srcdir/ROOT.jl/deps\"\n\nmake -j `nproc` LDLIBS=\"-lcxxwrap_julia -lcxxwrap_julia_stl\" LDFLAGS=\"-rdynamic\" CXXFLAGS+=\"-I $WORKSPACE/destdir/include/julia -std=c++17 -fPIC\"\n\ncp -a build/libroot_julia.so \"$prefix/lib/\"\n\ninstall_license $WORKSPACE/srcdir/ROOT.jl/LICENSE\n\n"""
version = "v1.1.0"

[[dependencies]]
compat = ""
name = "libjulia_jll"
platforms = ["any"]
top_level = false
type = "builddependency"
uuid = "5ad3ddd2-0711-543a-b040-befd59781bbf"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "0.14.3"
name = "libcxxwrap_julia_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "6.32.8"
name = "ROOT_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "45b42145-bbac-5752-8807-01f8b2702242"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = true
libnames = ["libroot_julia"]
type = "lib"
variable_name = "libroot_julia"

[[sources]]
hash = "cf68f4ec3409f3fd37805726fb7f7180acfbf62e"
type = "git"
unpack_target = ""
url = "https://github.com/JuliaHEP/ROOT.jl.git"
