augment_platform_block = ""
init_block = ""
julia_compat = "1.8"
lazy_artifacts = false
name = "ROCmDeviceLibs"
platforms = ["x86_64-linux-gnu-cxx11", "x86_64-linux-musl-cxx11"]
script = """cd ${WORKSPACE}/srcdir/ROCm-Device-Libs*/\nmkdir build && cd build\n\ncmake \\\n    -DCMAKE_PREFIX_PATH=${prefix} \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    ..\n\nmake -j${nproc}\nmake install\n"""
version = "v4.5.2"

[[dependencies]]
compat = ""
name = "ROCmLLVM_jll"
platforms = ["any"]
type = "builddependency"
version-major = 4
version-minor = 5
version-patch = 2
[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["amdgcn/bitcode/"]
type = "file"
variable_name = "bitcode_path"

[[sources]]
hash = "50e9e87ecd6b561cad0d471295d29f7220e195528e567fcabe2ec73838979f61"
type = "archive"
unpack_target = ""
url = "https://github.com/RadeonOpenCompute/ROCm-Device-Libs//archive/rocm-4.5.2.tar.gz"
