buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/d3c681b034a10c0561ce0dc515e8f45e8a74fbcf/A/azurite/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "azurite"
script = """version=3.18.0\napk add --update nodejs npm\ncd ${prefix}\nnpm install azurite@${version}\n"""
sources = []
version = "v3.18.0"

    [[metadata.dependencies]]
    compat = ""
    name = "NodeJS_16_jll"
    platforms = ["any"]
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0

    [[metadata.products]]
    paths = ["node_modules/azurite/dist/src/azurite.js"]
    type = "file"
    variable_name = "azurite"
