buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/a7ef6240d90dee272f2f9e7af29e4d7a036f9bb6/G/Gzip/build_tarballs.jl"
metadata_source = "retrospective (by timestamp)"
system = "Yggdrasil"
version = "0.2.4"

[metadata]
dependencies = []
lazy_artifacts = false
name = "Gzip"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir\ncd gzip-1.10/\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v1.10.0"

    [[metadata.products]]
    binnames = ["gzip"]
    type = "exe"
    variable_name = "gzip"

    [[metadata.sources]]
    hash = "8425ccac99872d544d4310305f915f5ea81e04d0f437ef1a230dc9d1c819d7c0"
    type = "archive"
    unpack_target = ""
    url = "https://ftp.gnu.org/gnu/gzip/gzip-1.10.tar.xz"
