augment_platform_block = """    using Base.BinaryPlatforms\n        # Can't use Preferences since we might be running this very early with a non-existing Manifest\n    MPIPreferences_UUID = Base.UUID(\"3da0fdf6-3ccc-4f1b-acd9-58baa6c99267\")\n    const preferences = Base.get_preferences(MPIPreferences_UUID)\n\n    # Keep logic in sync with MPIPreferences.jl\n    function augment_mpi!(platform)\n        # Doesn't need to be `const` since we depend on MPIPreferences so we\n        # invalidate the cache when it changes.\n        binary = get(preferences, \"binary\", Sys.iswindows() ? \"MicrosoftMPI_jll\" : \"MPICH_jll\")\n\n        abi = if binary == \"system\"\n            let abi = get(preferences, \"abi\", nothing)\n                if abi === nothing\n                    error(\"MPIPreferences: Inconsistent state detected, binary set to system, but no ABI set.\")\n                else\n                    abi\n                end\n            end\n        elseif binary == \"MicrosoftMPI_jll\"\n            \"MicrosoftMPI\"\n        elseif binary == \"MPICH_jll\"\n            \"MPICH\"\n        elseif binary == \"OpenMPI_jll\"\n            \"OpenMPI\"\n        elseif binary == \"MPItrampoline_jll\"\n            \"MPItrampoline\"\n        else\n            error(\"Unknown binary: $binary\")\n        end\n\n        if !haskey(platform, \"mpi\")\n            platform[\"mpi\"] = abi\n        end\n        return platform\n    end\n\n    augment_platform!(platform::Platform) = augment_mpi!(platform)\n"""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = true
name = "PTSCOTCH"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich", "i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline"]
script = """cd $WORKSPACE/srcdir/scotch*\natomic_patch -p1 \"${WORKSPACE}/srcdir/patches/native_build.patch\"\natomic_patch -p1 \"${WORKSPACE}/srcdir/patches/Makefile.patch\"\nif [[ \"${target}\" == *apple* || \"${target}\" == *freebsd* ]]; then\n    atomic_patch -p1 \"${WORKSPACE}/srcdir/patches/OSX_FreeBSD.patch\"\nfi\nif [[ \"${target}\" == *mingw* ]]; then\n    atomic_patch -p1 \"${WORKSPACE}/srcdir/patches/Windows.patch\"\nfi\natomic_patch -p1 \"${WORKSPACE}/srcdir/patches/mpi-constants.patch\"\ncd src\nmake ptscotch\nmake ptesmumps\ncp ../lib/libpt* ${libdir}\ncp ../include/p* ${includedir}\ninstall_license ../LICENSE_en.txt\n"""
version = "v6.1.4"

[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
type = "dependency"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "SCOTCH_jll"
platforms = ["any"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MPICH_jll"
platforms = ["i686-linux-gnu-mpi+mpich", "x86_64-linux-gnu-mpi+mpich", "aarch64-linux-gnu-mpi+mpich", "armv6l-linux-gnueabihf-mpi+mpich", "armv7l-linux-gnueabihf-mpi+mpich", "powerpc64le-linux-gnu-mpi+mpich", "i686-linux-musl-mpi+mpich", "x86_64-linux-musl-mpi+mpich", "aarch64-linux-musl-mpi+mpich", "armv6l-linux-musleabihf-mpi+mpich", "armv7l-linux-musleabihf-mpi+mpich", "x86_64-apple-darwin-mpi+mpich", "aarch64-apple-darwin-mpi+mpich", "x86_64-unknown-freebsd-mpi+mpich"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenMPI_jll"
platforms = ["i686-linux-gnu-mpi+openmpi", "x86_64-linux-gnu-mpi+openmpi", "aarch64-linux-gnu-mpi+openmpi", "armv6l-linux-gnueabihf-mpi+openmpi", "armv7l-linux-gnueabihf-mpi+openmpi", "powerpc64le-linux-gnu-mpi+openmpi", "i686-linux-musl-mpi+openmpi", "x86_64-linux-musl-mpi+openmpi", "aarch64-linux-musl-mpi+openmpi", "armv6l-linux-musleabihf-mpi+openmpi", "armv7l-linux-musleabihf-mpi+openmpi", "x86_64-apple-darwin-mpi+openmpi", "aarch64-apple-darwin-mpi+openmpi", "x86_64-unknown-freebsd-mpi+openmpi"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MicrosoftMPI_jll"
platforms = []
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "MPItrampoline_jll"
platforms = ["i686-linux-gnu-mpi+mpitrampoline", "x86_64-linux-gnu-mpi+mpitrampoline", "aarch64-linux-gnu-mpi+mpitrampoline", "armv6l-linux-gnueabihf-mpi+mpitrampoline", "armv7l-linux-gnueabihf-mpi+mpitrampoline", "powerpc64le-linux-gnu-mpi+mpitrampoline", "i686-linux-musl-mpi+mpitrampoline", "x86_64-linux-musl-mpi+mpitrampoline", "aarch64-linux-musl-mpi+mpitrampoline", "armv6l-linux-musleabihf-mpi+mpitrampoline", "armv7l-linux-musleabihf-mpi+mpitrampoline", "x86_64-apple-darwin-mpi+mpitrampoline", "aarch64-apple-darwin-mpi+mpitrampoline", "x86_64-unknown-freebsd-mpi+mpitrampoline"]
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "0.1"
name = "MPIPreferences"
platforms = ["any"]
type = "dependency"
uuid = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libptscotcherr"]
type = "lib"
variable_name = "libptscotcherr"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libptscotcherrexit"]
type = "lib"
variable_name = "libptscotcherrexit"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libptscotchparmetis"]
type = "lib"
variable_name = "libptscotchparmetis"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = true
libnames = ["libptscotch"]
type = "lib"
variable_name = "libptscotch"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libptesmumps"]
type = "lib"
variable_name = "libptesmumps"

[[sources]]
hash = "4e54f056199e6c23d46581d448fcfe2285987e5554a0aa527f7931684ef2809e"
type = "archive"
unpack_target = ""
url = "https://gitlab.inria.fr/scotch/scotch/-/archive/v6.1.3/scotch-v6.1.3.tar.gz"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
