buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f887eb3f824e881dceeadb960a77a4c38d8e69af/C/CVRPSEP/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.4.4"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "CVRPSEP"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "aarch64-apple-darwin", "armv6l-linux-gnueabihf", "armv6l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/CVRPSEP/\nautoreconf -fiv\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target}\nmake -j${nproc}\nmake install\n"""
version = "v0.1.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libcvrpsep"]
    type = "lib"
    variable_name = "libcvrpsep"

    [[metadata.sources]]
    hash = "c4d1720ffafcc174e39f65c7a90146cb82b68e44"
    type = "git"
    unpack_target = ""
    url = "https://github.com/chkwon/CVRPSEP.git"
