buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/f226f54cf5224a5c85a4eeb21fa5e91fc50efa8a/L/legate/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = """using Base.BinaryPlatforms\n\ntry\n    using CUDA_Runtime_jll\ncatch\n    # during initial package installation, CUDA_Runtime_jll may not be available.\n    # in that case, we just won't select an artifact.\nend\n\n# can't use Preferences for the same reason\nconst CUDA_Runtime_jll_uuid = Base.UUID(\"76a88914-d11a-5bdc-97e0-2f5a05c973a2\")\nconst preferences = Base.get_preferences(CUDA_Runtime_jll_uuid)\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"version\")\nBase.record_compiletime_preference(CUDA_Runtime_jll_uuid, \"local\")\nconst local_toolkit = something(tryparse(Bool, get(preferences, \"local\", \"false\")), false)\n\nfunction cuda_comparison_strategy(_a::String, _b::String, a_requested::Bool, b_requested::Bool)\n    # if we're using a local toolkit, we can't use artifacts\n    if local_toolkit\n        return false\n    end\n\n    # if either isn't a version number (e.g. \"none\"), perform a simple equality check\n    a = tryparse(VersionNumber, _a)\n    b = tryparse(VersionNumber, _b)\n    if a === nothing || b === nothing\n        return _a == _b\n    end\n\n    # if both b and a requested, then we fall back to equality\n    if a_requested && b_requested\n        return Base.thisminor(a) == Base.thisminor(b)\n    end\n\n    # otherwise, do the comparison between the the single version cap and the single version:\n    function is_compatible(artifact::VersionNumber, host::VersionNumber)\n        if host >= v\"11.0\"\n            # enhanced compatibility, semver-style\n            artifact.major == host.major &&\n            Base.thisminor(artifact) <= Base.thisminor(host)\n        else\n            Base.thisminor(artifact) == Base.thisminor(host)\n        end\n    end\n    if a_requested\n        is_compatible(b, a)\n    else\n        is_compatible(a, b)\n    end\nend\n\nfunction augment_platform!(platform::Platform)\n    if !@isdefined(CUDA_Runtime_jll)\n        # don't set to nothing or Pkg will download any artifact\n        platform[\"cuda\"] = \"none\"\n    end\n\n    if !haskey(platform, \"cuda\")\n        CUDA_Runtime_jll.augment_platform!(platform)\n    end\n    BinaryPlatforms.set_compare_strategy!(platform, \"cuda\", cuda_comparison_strategy)\n\n    return platform\nend"""
init_block = ""
julia_compat = "1.10"
lazy_artifacts = true
name = "legate"
platforms = ["x86_64-linux-gnu-cxx11-cuda+none", "x86_64-linux-gnu-cxx11-cuda+13.0"]
script = ["""\n# We will build with clang\nexport CC=\"clang\"\nexport CXX=\"clang++\"\nexport BUILD_CXX=$(which clang++)\nexport BUILD_CC=$(which clang)\n\n# Put new CMake first on path\nexport PATH=${host_bindir}:$PATH\n\n# Install Python 3.11 (via miniconda)\ncd ${WORKSPACE}/srcdir\nbash miniconda.sh -b -p ${host_bindir}/miniconda\n\n# Create venv and install configure script dependencies\n${host_bindir}/miniconda/bin/python -m venv ./venv\nsource ./venv/bin/activate\npip install --upgrade pip\npip install rich typing_extensions packaging\n\npython -c \"import rich, typing_extensions, packaging; print('Python deps installed and working!')\"\n\ncd ${WORKSPACE}/srcdir/legate\n\n### Set Up CUDA ENV Vars\n\nexport CPPFLAGS=\"${CPPFLAGS} -I${prefix}/include\"\nexport CFLAGS=\"${CFLAGS} -I${prefix}/include\"\nexport LDFLAGS=\"${LDFLAGS} -L${prefix}/lib -L${prefix}/lib64\"\n\n./configure \\\n    --prefix=${prefix} \\\n    --with-cuda=0 \\\n    --with-mpiexec-executable=${bindir}/mpiexec \\\n    --with-mpi-dir=${prefix} \\\n    --with-hdf5-vfd-gds=0 \\\n    --with-hdf5-dir=${prefix} \\\n    --num-threads=${nproc} \\\n    --with-cxx=${CXX} \\\n    --with-cc=${CC} \\\n    --CXXFLAGS=\"${CPPFLAGS}\" \\\n    --CFLAGS=\"${CFLAGS}\" \\\n    --with-clean \\\n    --cmake-executable=${host_bindir}/cmake \\\n    -- \"-DCMAKE_TOOLCHAIN_FILE=/opt/toolchains/${bb_full_target}/target_${target}_clang.cmake\" \\\n        \"-DCMAKE_CUDA_HOST_COMPILER=$(which clang++)\" \\\n\n\n# Patch redop header that is installed by configure script\n# Patch in macro to export specific symbols \ncd ${WORKSPACE}/srcdir\natomic_patch -p1 ./legion_redop.patch\natomic_patch -p1 ./proc_local_h.patch\natomic_patch -p1 ./proc_local_inl.patch\n\n# Go back to main dir\ncd ${WORKSPACE}/srcdir/legate\n\nmake install -j ${nproc} PREFIX=${prefix}\ninstall_license ${WORKSPACE}/srcdir/legate/LICENSE\n\n""", """\n# We will build with clang\nexport CC=\"clang\"\nexport CXX=\"clang++\"\nexport BUILD_CXX=$(which clang++)\nexport BUILD_CC=$(which clang)\n\n# Necessary operations to cross compile CUDA from x86_64 to aarch64\nif [[ \"${target}\" == aarch64-linux-* ]]; then\n\n# Add /usr/lib/csl-musl-x86_64 to LD_LIBRARY_PATH to be able to use host nvcc\nexport LD_LIBRARY_PATH=\"/usr/lib/csl-musl-x86_64:/usr/lib/csl-glibc-x86_64:${LD_LIBRARY_PATH}\"\n\n# Make sure we use host CUDA executable by copying from the x86_64 CUDA redist\nNVCC_DIR=(/workspace/srcdir/cuda_nvcc-*-archive)\nrm -rf ${prefix}/cuda/bin\ncp -r ${NVCC_DIR}/bin ${prefix}/cuda/bin\n\nrm -rf ${prefix}/cuda/nvvm/bin\ncp -r ${NVCC_DIR}/nvvm/bin ${prefix}/cuda/nvvm/bin\n\nexport NVCC_PREPEND_FLAGS=\"-ccbin='${CXX}'\"\nfi\n\n# Put new CMake first on path\nexport PATH=${host_bindir}:$PATH\n\n# Install Python 3.11 (via miniconda)\ncd ${WORKSPACE}/srcdir\nbash miniconda.sh -b -p ${host_bindir}/miniconda\n\n# Create venv and install configure script dependencies\n${host_bindir}/miniconda/bin/python -m venv ./venv\nsource ./venv/bin/activate\npip install --upgrade pip\npip install rich typing_extensions packaging\n\npython -c \"import rich, typing_extensions, packaging; print('Python deps installed and working!')\"\n\ncd ${WORKSPACE}/srcdir/legate\n\n### Set Up CUDA ENV Vars\n\nexport CPPFLAGS=\"${CPPFLAGS} -I${prefix}/include\"\nexport CFLAGS=\"${CFLAGS} -I${prefix}/include\"\nexport LDFLAGS=\"${LDFLAGS} -L${prefix}/lib -L${prefix}/lib64\"\n\nexport CUDA_HOME=${prefix}/cuda;\nexport PATH=$PATH:$CUDA_HOME/bin\nexport CUDACXX=$CUDA_HOME/bin/nvcc\nexport CUDA_LIB=${CUDA_HOME}/lib\n\nln -s ${CUDA_HOME}/lib ${CUDA_HOME}/lib64\n\n./configure \\\n    --prefix=${prefix} \\\n    --with-cudac=${CUDACXX} \\\n    --with-cuda-dir=${CUDA_HOME} \\\n    --with-nccl-dir=${prefix} \\\n    --with-mpiexec-executable=${bindir}/mpiexec \\\n    --with-mpi-dir=${prefix} \\\n    --with-hdf5-vfd-gds=0 \\\n    --with-hdf5-dir=${prefix} \\\n    --num-threads=${nproc} \\\n    --with-cxx=${CXX} \\\n    --with-cc=${CC} \\\n    --CXXFLAGS=\"${CPPFLAGS}\" \\\n    --CFLAGS=\"${CFLAGS}\" \\\n    --with-clean \\\n    --cmake-executable=${host_bindir}/cmake \\\n    -- \"-DCMAKE_TOOLCHAIN_FILE=/opt/toolchains/${bb_full_target}/target_${target}_clang.cmake\" \\\n        \"-DCMAKE_CUDA_HOST_COMPILER=$(which clang++)\" \\\n\n\n# Patch redop header that is installed by configure script\n# Patch in macro to export specific symbols \ncd ${WORKSPACE}/srcdir\natomic_patch -p1 ./legion_redop.patch\natomic_patch -p1 ./proc_local_h.patch\natomic_patch -p1 ./proc_local_inl.patch\n\n# Go back to main dir\ncd ${WORKSPACE}/srcdir/legate\n\nmake install -j ${nproc} PREFIX=${prefix}\ninstall_license ${WORKSPACE}/srcdir/legate/LICENSE\n\nif [[ \"${target}\" == aarch64-linux-* ]]; then\n# ensure products directory is clean\nrm -rf ${prefix}/cuda\nfi\n"""]
version = "v25.10.2"

    [[metadata.dependencies]]
    compat = "~1.14.6"
    name = "HDF5_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "4.3.0"
    name = "MPICH_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = "1.2.12"
    name = "Zlib_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CompilerSupportLibraries_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CMake_jll"
    platforms = ["any"]
    top_level = false
    type = "hostdependency"
    version-major = 3
    version-minor = 31
    version-patch = 9
    [[metadata.dependencies]]
    compat = "2.27.7"
    name = "NCCL_jll"
    platforms = ["any"]
    top_level = false
    type = "dependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_SDK_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 13
    version-minor = 0
    version-patch = 2
    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_Runtime_jll"
    platforms = ["any"]
    top_level = false
    type = "runtimedependency"
    version-major = 0
    version-minor = 0
    version-patch = 0
    [[metadata.dependencies]]
    compat = ""
    name = "CUDA_SDK_static_jll"
    platforms = ["any"]
    top_level = false
    type = "builddependency"
    version-major = 13
    version-minor = 0
    version-patch = 2

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["liblegate"]
    type = "lib"
    variable_name = "liblegate"

    [[metadata.sources]]
    hash = "b0a20719ce9c5f63e8b1c3ddd1e592af5e7a3df6"
    type = "git"
    unpack_target = ""
    url = "https://github.com/nv-legate/legate.git"
    [[metadata.sources]]
    follow_symlinks = false
    path = "./bundled"
    target = ""
    type = "directory"
    [[metadata.sources]]
    filename = "miniconda.sh"
    hash = "4da8dde69eca0d9bc31420349a204851bfa2a1c87aeb87fe0c05517797edaac4"
    type = "file"
    url = "https://repo.anaconda.com/miniconda/Miniconda3-py311_24.3.0-0-Linux-x86_64.sh"
