augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "DataEcon"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/DataEcon/\nmake -j${nproc} all LIBDE=\"bin/libdaec.${dlext}\"\ninstall_license LICENSE.md\ninstall -Dvm 755 \"bin/sqlite3${exeext}\" \"${bindir}/sqlite3${exeext}\"\ninstall -Dvm 755 \"bin/libdaec.${dlext}\" \"${libdir}/libdaec.${dlext}\"\ninstall -Dvm 644 src/daec.h \"${includedir}/daec.h\"\n"""
version = "v0.1.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libdaec", "daec"]
type = "lib"
variable_name = "libdaec"
[[products]]
binnames = ["sqlite3"]
type = "exe"
variable_name = "sqlite3shell"
[[products]]
paths = ["include/daec.h"]
type = "file"
variable_name = "daec_header"

[[sources]]
hash = "c99b6b8ea8a5d500ba8d091b384d58a815b7db01"
type = "git"
unpack_target = ""
url = "https://github.com/bankofcanada/DataEcon.git"
