augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "minimap2"
platforms = ["aarch64-apple-darwin", "x86_64-w64-mingw32", "x86_64-linux-gnu", "aarch64-linux-musl", "x86_64-apple-darwin", "x86_64-linux-musl", "x86_64-unknown-freebsd", "aarch64-linux-gnu"]
script = """cd $WORKSPACE/srcdir\ncd minimap2\nif [[ ${target} == x86_64* ]]; then\n    make\nelse\n    make arm_neon=1 aarch64=1\nfi\ninstall -Dvm 755 minimap2 \"${bindir}/minimap2${exeext}\"\n"""
version = "v2.24.0"

[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
type = "dependency"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["minimap2"]
type = "exe"
variable_name = "minimap2"

[[sources]]
hash = "fe35e679e95d936698e9e937acc48983f16253d6"
type = "git"
unpack_target = ""
url = "https://github.com/lh3/minimap2.git"
