["2023.8.21+0"]
artifact_urls = ["https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-unknown-freebsd.tar.gz"]
registered = 2023-09-30T21:09:01.000Z

    [["2023.8.21+0".artifact_metadata]]
    artifact_urls = ["https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/Intel_XED_jll.jl/releases/download/Intel_XED-v2023.8.21+0/Intel_XED.v2023.8.21.x86_64-unknown-freebsd.tar.gz"]
    buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/3cc37ff28d00b4b2fc09711e2617fcbee9c99ce6/I/Intel_XED/build_tarballs.jl"
    metadata_source = "retrospective (by README link)"
    metadata_type = "BinaryBuilder --meta-json"
    metadata_version = "0.5.6"

        ["2023.8.21+0".artifact_metadata.metadata]
        augment_platform_block = ""
        dependencies = []
        init_block = ""
        julia_compat = "1.6"
        lazy_artifacts = false
        name = "Intel_XED"
        platforms = ["x86_64-linux-gnu", "x86_64-linux-musl", "x86_64-unknown-freebsd"]
        script = """cd ${WORKSPACE}/srcdir/xed\n\n# This file is binary (?), and Python tries to decode it as UTF-8 and fails, and aborts\n# This file exists when I build locally, but not when Yggdrasil builds.\nrm -f /usr/lib/python3.9/site-packages/._distutils-precedence.pth\n\npython3 mfile.py --clean\npython3 mfile.py -j${nproc} --cc=${CC} --opt=2 --shared --no-werror\n# We could also build the CLI.\n\nmkdir -p ${includedir}\nmkdir -p ${libdir}\ninstall -Dvm 755 obj/wkit/include/xed/*.h ${includedir}\ninstall -Dvm 755 obj/wkit/lib/*.so ${libdir}\ninstall_license LICENSE\n"""
        version = "v2023.8.21"

            [["2023.8.21+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libxed"]
            type = "lib"
            variable_name = "libxed"
            [["2023.8.21+0".artifact_metadata.metadata.products]]
            dir_paths = []
            dlopen_flags = []
            dont_dlopen = false
            libnames = ["libxed-ild"]
            type = "lib"
            variable_name = "libxed_ild"

            [["2023.8.21+0".artifact_metadata.metadata.sources]]
            hash = "01a6da8090af84cd52f6c1070377ae6e885b078f"
            type = "git"
            unpack_target = ""
            url = "https://github.com/intelxed/xed"
            [["2023.8.21+0".artifact_metadata.metadata.sources]]
            hash = "75cb46e6536758f1a3cdb3d6bd83a4a9fd0338bb"
            type = "git"
            unpack_target = ""
            url = "https://github.com/intelxed/mbuild"
