init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "Qt6Base"
platforms = ["x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11"]
script = """cd $WORKSPACE/srcdir\n\nBIN_DIR=\"/opt/bin/${bb_full_target}\"\n\nmkdir build\ncd build/\n\nqtsrcdir=`ls -d ../qtbase-everywhere-src-*`\n\ncommonoptions=\" \\\n-opensource -confirm-license \\\n-openssl-linked  -nomake examples -release \\\n\"\n\nexport OPENSSL_LIBS=\"-L${libdir} -lssl -lcrypto\"\n\nsed -i 's/-march=haswell/-mavx2/' $qtsrcdir/cmake/QtCompilerOptimization.cmake\n\ncase \"$target\" in\n\n    x86_64-linux-musl*)\n        ../qtbase-everywhere-src-*/configure -prefix $prefix $commonoptions -fontconfig -- -DCMAKE_PREFIX_PATH=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_HOST_TOOLCHAIN}\n    ;;\nesac\n\ncmake --build . --parallel\ncmake --install .\n$BUILD_STRIP $bindir/qmake\ninstall_license $WORKSPACE/srcdir/qtbase-everywhere-src-*/LICENSE.LGPLv3\n"""
version = "v6.0.3"

[[dependencies]]
compat = ""
name = "Xorg_libX11_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libXext_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_glproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libxcb_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xcb_util_wm_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xcb_util_image_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xcb_util_keysyms_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_xcb_util_renderutil_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_kbproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_renderproto_jll"
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Xorg_libXrender_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "xkbcommon_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Libglvnd_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Fontconfig_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Glib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zlib_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "CompilerSupportLibraries_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "OpenSSL_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Concurrent", "libQt6Concurrent", "QtConcurrent"]
type = "lib"
variable_name = "libqt6concurrent"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Core", "libQt6Core", "QtCore"]
type = "lib"
variable_name = "libqt6core"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6DBus", "libQt6DBus", "QtDBus"]
type = "lib"
variable_name = "libqt6dbus"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Gui", "libQt6Gui", "QtGui"]
type = "lib"
variable_name = "libqt6gui"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Network", "libQt6Network", "QtNetwork"]
type = "lib"
variable_name = "libqt6network"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6OpenGL", "libQt6OpenGL", "QtOpenGL"]
type = "lib"
variable_name = "libqt6opengl"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6PrintSupport", "libQt6PrintSupport", "QtPrintSupport"]
type = "lib"
variable_name = "libqt6printsupport"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Sql", "libQt6Sql", "QtSql"]
type = "lib"
variable_name = "libqt6sql"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Test", "libQt6Test", "QtTest"]
type = "lib"
variable_name = "libqt6test"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Widgets", "libQt6Widgets", "QtWidgets"]
type = "lib"
variable_name = "libqt6widgets"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["Qt6Xml", "libQt6Xml", "QtXml"]
type = "lib"
variable_name = "libqt6xml"

[[sources]]
hash = "1a45b61c2a349964625c50e3ea40cbb309e269762dd0786397e0e18e7e10d394"
type = "archive"
unpack_target = ""
url = "https://download.qt.io/official_releases/qt/6.0/6.0.3/submodules/qtbase-everywhere-src-6.0.3.tar.xz"
[[sources]]
hash = "0f03869f72df8705b832910517b47dd5b79eb4e160512602f593ed243b28715f"
type = "archive"
unpack_target = ""
url = "https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz"
