dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "kubectl"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-apple-darwin", "x86_64-w64-mingw32"]
script = """cd ${WORKSPACE}/srcdir/\nmkdir -p ${bindir}\n\ninstall_license LICENSE\n\nmv \"${target}-kubectl\" \"${bindir}/kubectl${exeext}\"\nchmod 755 \"${bindir}/kubectl${exeext}\"\n"""
version = "v1.20.0"

[[products]]
binnames = ["kubectl"]
type = "exe"
variable_name = "kubectl"

[[sources]]
filename = "x86_64-linux-gnu-kubectl"
hash = "a5895007f331f08d2e082eb12458764949559f30bcc5beae26c38f3e2724262c"
type = "file"
url = "https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl"
[[sources]]
filename = "aarch64-linux-gnu-kubectl"
hash = "25e4465870c99167e6c466623ed8f05a1d20fbcb48cab6688109389b52d87623"
type = "file"
url = "https://dl.k8s.io/release/v1.20.0/bin/linux/arm64/kubectl"
[[sources]]
filename = "x86_64-apple-darwin14-kubectl"
hash = "82046a4abb056005edec097a42cc3bb55d1edd562d6f6f38c07318603fcd9fca"
type = "file"
url = "https://dl.k8s.io/release/v1.20.0/bin/darwin/amd64/kubectl"
[[sources]]
filename = "x86_64-w64-mingw32-kubectl"
hash = "ee7be8e93349fb0fd1db7f5cdb5985f5698cef69b7b7be012fc0e6bed06b254d"
type = "file"
url = "https://dl.k8s.io/release/v1.20.0/bin/windows/amd64/kubectl.exe"
[[sources]]
filename = "LICENSE"
hash = "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"
type = "file"
url = "https://raw.githubusercontent.com/kubernetes/kubernetes/v1.20.0/LICENSE"
