dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "UserNSSandbox"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf"]
script = """cd $WORKSPACE/srcdir/\nmkdir -p ${bindir}\n$CC -std=c99 -O2 -g -o ${bindir}/sandbox ./sandbox.c\ninstall_license /usr/share/licenses/MIT\n"""
version = "v2021.1.15"

[[products]]
binnames = ["sandbox"]
type = "exe"
variable_name = "sandbox"

[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
