buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/45c9f3fb776f62e56c2eeb1411df4772f1126e09/G/GoogleTest/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.3.0"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "GoogleTest"
platforms = ["i686-linux-gnu-cxx03", "i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx03", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx03", "aarch64-linux-gnu-cxx11", "armv7l-linux-gnueabihf-cxx03", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx03", "powerpc64le-linux-gnu-cxx11", "i686-linux-musl-cxx03", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx03", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx03", "aarch64-linux-musl-cxx11", "armv7l-linux-musleabihf-cxx03", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "x86_64-unknown-freebsd", "i686-w64-mingw32-cxx03", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx03", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir/googletest\nmkdir build && cd build\ncmake -DBUILD_SHARED_LIBS=ON \\\n    -DCMAKE_INSTALL_PREFIX=${prefix} \\\n    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \\\n    -DCMAKE_BUILD_TYPE=Release \\\n    -DBUILD_GMOCK=OFF \\\n    ..\nmake -j${nproc}\nmake install\n"""
version = "v1.10.0"

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgtest_main"]
    type = "lib"
    variable_name = "libgtest_main"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libgtest"]
    type = "lib"
    variable_name = "libgtest"

    [[metadata.sources]]
    hash = "703bd9caab50b139428cea1aaff9974ebee5742e"
    type = "git"
    unpack_target = ""
    url = "https://github.com/google/googletest.git"
