init_block = ""
lazy_artifacts = false
name = "CMake"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "x86_64-linux-musl-cxx11"]
script = """cd $WORKSPACE/srcdir/cmake-*/\n\ncmake -DCMAKE_INSTALL_PREFIX=$prefix\n\nmake -j${nproc}\nmake install\n"""
version = "v3.17.1"

[[dependencies]]
name = "OpenSSL_jll"
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["cmake"]
type = "exe"
variable_name = "cmake"

[[sources]]
hash = "3aa9114485da39cbd9665a0bfe986894a282d5f0882b1dea960a739496620727"
type = "archive"
unpack_target = ""
url = "https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1.tar.gz"
