augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "SDL2_mixer"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/SDL*/\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --with-pic --disable-static\nmake -j${nproc}\nmake install\ninstall_license LICENSE.txt\n"""
version = "v2.8.1"

[[dependencies]]
compat = ""
name = "SDL2_jll"
platforms = ["any"]
top_level = false
type = "dependency"
uuid = "ab825dc5-c88e-5901-9575-1e5e20358fcf"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libSDL2_mixer", "SDL2_mixer"]
type = "lib"
variable_name = "libsdl2_mixer"

[[sources]]
hash = "171eb2d420d5643e4ee11514a06e04a41a463bbd"
type = "git"
unpack_target = ""
url = "https://github.com/libsdl-org/SDL_mixer.git"
