buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/0727d320ff15e22acb5c68166b59a43dcfd62f10/M/MKL_Headers/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.2"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "MKL_Headers"
platforms = ["x86_64-linux-gnu", "i686-linux-gnu", "x86_64-apple-darwin", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd $WORKSPACE/srcdir/mkl-include-$target\nif [[ $target == *-mingw* ]]; then\n    rsync -av Library/include/ ${includedir}\nelse\n    rsync -av include/ ${includedir}\nfi\ninstall_license info/licenses/*.txt\n"""
version = "v2022.0.0"

    [[metadata.products]]
    paths = ["include/mkl.h"]
    type = "file"
    variable_name = "include_mkl_h"

    [[metadata.sources]]
    hash = "e664eb639faf03d5a4e76b435deb28a67ef7f59f3c55adaeeef771a7c94b56e3"
    type = "archive"
    unpack_target = "mkl-include-x86_64-linux-gnu"
    url = "https://anaconda.org/intel/mkl-include/2022.0.1/download/linux-64/mkl-include-2022.0.1-intel_117.tar.bz2"
    [[metadata.sources]]
    hash = "411f636d3e95f75453de80a5574273454b67181c7c30d3276c6cb18a91ef3eeb"
    type = "archive"
    unpack_target = "mkl-include-i686-linux-gnu"
    url = "https://anaconda.org/intel/mkl-include/2022.0.1/download/linux-32/mkl-include-2022.0.1-intel_117.tar.bz2"
    [[metadata.sources]]
    hash = "d7aa8f0c7904045c6f569462c0d04cc34250ee991855f5a3ab2fba8bbc5a0d81"
    type = "archive"
    unpack_target = "mkl-include-x86_64-apple-darwin14"
    url = "https://anaconda.org/intel/mkl-include/2022.0.0/download/osx-64/mkl-include-2022.0.0-intel_105.tar.bz2"
    [[metadata.sources]]
    hash = "2d9999a92959be25b5dabbd5b69a4b7f738b87215254c776d59c6b2f8b2addf3"
    type = "archive"
    unpack_target = "mkl-include-i686-w64-mingw32"
    url = "https://anaconda.org/intel/mkl-include/2022.0.0/download/win-32/mkl-include-2022.0.0-intel_115.tar.bz2"
    [[metadata.sources]]
    hash = "eb8f6187d8e4ded8c48b701d00658ef49adc2180e42f1ff52f43c1fecc79a870"
    type = "archive"
    unpack_target = "mkl-include-x86_64-w64-mingw32"
    url = "https://anaconda.org/intel/mkl-include/2022.0.0/download/win-64/mkl-include-2022.0.0-intel_115.tar.bz2"
