init_block = ""
julia_compat = "1.0"
lazy_artifacts = false
name = "GAP_lib"
products = []
script = """cd ${WORKSPACE}/srcdir/gap*\n\nmv ../pkg .\nfind pkg -name '._*' -exec rm \\{\\} \\; # unwanted files\n\n# run autogen.sh if compiling from it source and/or if configure was patched\n./autogen.sh\n\n# compile a native version of GAP so we can use it to generate the manual\n# (the manual is only in FULL gap release tarballs, not in the -core tarball\n# nor in git snapshots)\nmkdir native-build\ncd native-build\n#apk add gmp-dev zlib-dev\n../configure --build=${MACHTYPE} --host=${MACHTYPE} CC=${CC_BUILD} CXX=${CXX_BUILD} --with-zlib=${prefix} --with-gmp=${prefix}\nmake -j${nproc}\nmake html   # build the manual (only HTML and txt; for PDF we'd need LaTeX)\ncd ..\n\n# remove the native build, it has done its job\nrm -rf native-build\n\n# the license\ninstall_license LICENSE\n\n# \"install\" most of the files\nrm -rf autom4te.cache dev etc extern hpcgap/extern pkg\nmkdir -p ${prefix}/share/gap/\nmv * ${prefix}/share/gap/\n"""
version = "v400.1192.0"

[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "GMP_jll"
platforms = ["any"]
type = "builddependency"
version-major = 0
version-minor = 0
version-patch = 0

[[sources]]
hash = "c67fb7d89cafeb9231facd80f85426199e0d62db"
type = "git"
unpack_target = ""
url = "https://github.com/gap-system/gap.git"
[[sources]]
hash = "5f66ac4053db34e4c0ebca25dd7666b891c812c084082db6cc28c551c57a3792"
type = "archive"
unpack_target = "pkg"
url = "https://github.com/gap-system/gap/releases/download/v4.11.1/packages-required-v4.11.1.tar.gz"
