augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "LibPQ"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """cd zic-build\nmake CC=$BUILD_CC VERSION_DEPS= zic\nmv zic ../ && cd ../ && rm -rf zic-build\nexport ZIC=$WORKSPACE/srcdir/zic\nexport PATH=$WORKSPACE/srcdir:$PATH\n# We need `__STDC_WANT_LIB_EXT1__` for `memset_s` on macOS\nexport CFLAGS=\"-std=c11 -D__STDC_WANT_LIB_EXT1__\"\n\ncd postgres\n\nif [[ ${target} == *-apple-* ]]; then\n    ./configure --prefix=${prefix} \\\n        --build=${MACHTYPE} \\\n        --host=${target} \\\n        --with-includes=${includedir} \\\n        --with-libraries=${libdir} \\\n        --without-readline \\\n        --without-zlib \\\n        --with-ssl=openssl \\\n        \"${FLAGS[@]}\"\n\n    make -C src/interfaces/libpq -j${nproc}\n    make -C src/interfaces/libpq install\n    make -C src/include install\n\nelse\n    meson setup meson_build --prefix=$prefix \\\n        --cross-file=\"${MESON_TARGET_TOOLCHAIN}\" \\\n        --bindir=${bindir} \\\n        --libdir=${libdir} \\\n        --includedir=${includedir} \\\n        -Dssl=openssl \\\n        -Dzlib=disabled \\\n        -Dreadline=disabled \\\n        -Dtap_tests=disabled \\\n        -Dplpython=disabled \\\n        -Dplperl=disabled \\\n        -Dnls=disabled\n\n    cd meson_build\n    ninja -j${nproc}\n    ninja install\n    cd ../\n\n    if [[ ${target} == *-w64-mingw32 ]]; then\n        mv -v meson_build/src/interfaces/libpq/* ${prefix}/lib\n    fi    \nfi\n\n\n# Delete static library\nrm ${prefix}/lib/libpq.a\ninstall_license COPYRIGHT\n"""
version = "v16.13.0"

[[dependencies]]
compat = ""
name = "Bison_jll"
platforms = ["any"]
top_level = false
type = "hostdependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "3.0.16"
name = "OpenSSL_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "1.21.3"
name = "Kerberos_krb5_jll"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "76.1"
name = "ICU_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "1.5.7"
name = "Zstd_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libpq"]
type = "lib"
variable_name = "LIBPQ_HANDLE"

[[sources]]
hash = "776479eed63aac4185e57adaf7db1ce0810a4d3e"
type = "git"
unpack_target = ""
url = "https://github.com/postgres/postgres.git"
[[sources]]
hash = "f80a17a2eddd2b54041f9c98d75b0aa8038b016d7c5de72892a146d9938740e1"
type = "archive"
unpack_target = "zic-build"
url = "https://data.iana.org/time-zones/releases/tzcode2026a.tar.gz"
