augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "GAP_pkg_io"
platforms = ["x86_64-linux-gnu", "aarch64-linux-gnu", "powerpc64le-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd"]
script = """cd io*\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --with-gaproot=${prefix}/lib/gap\nmake -j${nproc}\n\n# copy the loadable module\nmkdir -p ${prefix}/lib/gap\ncp bin/*/*.so ${prefix}/lib/gap/\n\ninstall_license LICENSE\n"""
version = "v400.800.200"

[[dependencies]]
compat = "~400.1300.0"
name = "GAP_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = "~400.1300.0"
name = "GAP_lib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
paths = ["lib/gap/io.so"]
type = "file"
variable_name = "io"

[[sources]]
hash = "858bccff87fc149a5db66af49e9b071f397c3fe8840d6f972f0b24f81b59f69d"
type = "archive"
unpack_target = ""
url = "https://github.com/gap-packages/io/releases/download/v4.8.2/io-4.8.2.tar.gz"
