augment_platform_block = ""
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "squashfs_tools"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd"]
script = """cd $WORKSPACE/srcdir/squashfs-tools/squashfs-tools\n\n# Reported as <https://github.com/plougher/squashfs-tools/issues/324>\natomic_patch -p1 $WORKSPACE/srcdir/patches/nprocessors_compat.patch\n\nargs=(XZ_SUPPORT=1 LZO_SUPPORT=1 LZ4_SUPPORT=1 ZSTD_SUPPORT=1)\nif [[ \"${target}\" == *-mingw* ]] || [[ \"${target}\" == *-freebsd* ]]; then\n    args+=(XATTR_OS_SUPPORT=0)\nfi\n\nenv CONFIG=1 make -j${nproc} ${args[@]}\ncp mksquashfs unsquashfs ${bindir}\n"""
version = "v4.7.2"

[[dependencies]]
compat = ""
name = "Zlib_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "XZ_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "LZO_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Lz4_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
compat = ""
name = "Zstd_jll"
platforms = ["any"]
top_level = false
type = "dependency"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
binnames = ["unsquashfs"]
type = "exe"
variable_name = "unsquashfs"
[[products]]
binnames = ["mksquashfs"]
type = "exe"
variable_name = "mksquashfs"

[[sources]]
hash = "99d23a31b471433c51e9c145aeba2ab1536e34df"
type = "git"
unpack_target = ""
url = "https://github.com/plougher/squashfs-tools.git"
[[sources]]
follow_symlinks = false
path = "bundled"
target = ""
type = "directory"
