buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/db23b4c8d4bec230c46532dc1f67542f9930ff70/Z/Zellij/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
metadata_type = "BinaryBuilder --meta-json"
metadata_version = "0.5.2"

[metadata]
augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Zellij"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin"]
script = """cd $WORKSPACE/srcdir/zellij*/\ncargo build --release\ninstall -Dvm 755 \"target/${rust_target}/release/zellij${exeext}\" \"${bindir}/zellij${exeext}\"\n"""
version = "v0.25.0"

    [[metadata.products]]
    binnames = ["zellij"]
    type = "exe"
    variable_name = "zellij"

    [[metadata.sources]]
    hash = "5bd4e6a726cf32e096f9c90d7dc414e63dee0613a56f5b665f4bfc6376dcf20a"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/zellij-org/zellij/archive/refs/tags/v0.25.0.tar.gz"
