buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/9e15629ed0657488322428b47e0ffa28c2fdcc8c/Z/Zellij/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.5.2"

[metadata]
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "Zellij"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-linux-musl", "aarch64-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin"]
script = """cd $WORKSPACE/srcdir/zellij*/\ncargo build --release\ninstall -Dvm 755 \"target/${rust_target}/release/zellij${exeext}\" \"${bindir}/zellij${exeext}\"\n"""
version = "v0.24.0"

    [[metadata.products]]
    binnames = ["zellij"]
    type = "exe"
    variable_name = "zellij"

    [[metadata.sources]]
    hash = "a7f2d1fa1dd9c55d37d1daebdf6af3c6666d144ee1e85ac7f805544ae03e3b1e"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/zellij-org/zellij/archive/refs/tags/v0.24.0.tar.gz"
