lazy_artifacts = false
name = "MPFI"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv7l-linux-musleabihf", "x86_64-apple-darwin14", "x86_64-unknown-freebsd11.1", "i686-w64-mingw32", "x86_64-w64-mingw32"]
script = """    cd $WORKSPACE/srcdir/mpfi-*\n\n    # The autotools scripts are not provided setup, so we must configure the configure script\n    ./autogen.sh\n\n    # Don't build the static library, documentation, or test set\n    ./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} --with-gmp=${prefix} --with-mpfr=${prefix} --disable-static\n    make -j${nproc} SUBDIRS=\"src\"\n    make install SUBDIRS=\"src\"\n\n    # Remove the libtool files that are created\n    rm -f ${prefix}/lib/*.la\n"""
version = "v1.5.4"

[[dependencies]]
name = "GMP_jll"
type = "dependency"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version-major = 0
version-minor = 0
version-patch = 0
[[dependencies]]
name = "MPFR_jll"
type = "dependency"
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version-major = 0
version-minor = 0
version-patch = 0

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libmpfi"]
type = "lib"
variable_name = "libmpfi"

[[sources]]
hash = "3b3938595d720af17973deaf727cfc0dd41c8b16c20adc103a970f4a43ae3a56"
type = "archive"
unpack_target = ""
url = "https://gforge.inria.fr/frs/download.php/file/38111/mpfi-1.5.4.tgz"
