augment_platform_block = ""
dependencies = []
init_block = ""
julia_compat = "1.6"
lazy_artifacts = false
name = "tree_sitter_ocaml"
platforms = ["i686-linux-gnu-cxx11", "x86_64-linux-gnu-cxx11", "aarch64-linux-gnu-cxx11", "armv6l-linux-gnueabihf-cxx11", "armv7l-linux-gnueabihf-cxx11", "powerpc64le-linux-gnu-cxx11", "riscv64-linux-gnu-cxx11", "i686-linux-musl-cxx11", "x86_64-linux-musl-cxx11", "aarch64-linux-musl-cxx11", "armv6l-linux-musleabihf-cxx11", "armv7l-linux-musleabihf-cxx11", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32-cxx11", "x86_64-w64-mingw32-cxx11"]
script = """cd $WORKSPACE/srcdir\nmv tree-sitter-* tree-sitter\n\nBUILD_FLAGS=(-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN})\nmkdir build && cd build\ncmake .. \"${BUILD_FLAGS[@]}\"\nmake -j${nproc}\nmake install\n\ncd ..\nif [ -d tree-sitter/queries ]; then\n    cp -r tree-sitter/queries $WORKSPACE/destdir/\nfi\nif [ -f tree-sitter/LICENSE ]; then\n    install_license tree-sitter/LICENSE\nfi\n"""
version = "v0.25.0"

[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtreesitter_ocaml"]
type = "lib"
variable_name = "libtreesitter_ocaml"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtreesitter_ocaml_interface"]
type = "lib"
variable_name = "libtreesitter_ocaml_interface"
[[products]]
dir_paths = []
dlopen_flags = []
dont_dlopen = false
libnames = ["libtreesitter_ocaml_type"]
type = "lib"
variable_name = "libtreesitter_ocaml_type"

[[sources]]
hash = "6902a86ab5b3b80c622030210aae2d8cb95eb775"
type = "git"
unpack_target = ""
url = "https://github.com/tree-sitter/tree-sitter-ocaml.git"
[[sources]]
follow_symlinks = false
path = "./bundled"
target = ""
type = "directory"
